apiVersion: arc.bwi.de/v1alpha1
kind: ClusterArtifactType
metadata:
  name: blob
spec:
  rules:
    srcTypes: # Endpoint Types
      - http
      - s3
    dstTypes:
      - s3
  parameters:
    - name: storageQuota
      value: "4096" # bytes
  workflowTemplateRef: # argo.ClusterWorkflowTemplate
    name: blob-pipeline
