apiVersion: arc.opendefense.cloud/v1alpha1
kind: ClusterArtifactType
metadata:
  name: blob
spec:
  rules:
    srcTypes: # Endpoint Types
      - http
      - s3
    dstTypes:
      - s3
  parameters:
    - name: storageQuota
      value: "1073741824" # bytes
  workflowTemplateRef: # argo.ClusterWorkflowTemplate
    name: blob-pipeline
