apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: blob-pipeline
spec:
  retryStrategy:
    retryPolicy: OnError
    limit: 1

  serviceAccountName: arc-workflow
  securityContext:
    fsGroup: 65532
    runAsUser: 65532

  # Mount certificate bundle
  volumes:
    - name: ca-certificates
      configMap:
        name: "root-bundle"
        defaultMode: 0644
        optional: false
        items:
          - key: trust-bundle.pem
            path: trust-bundle.pem

  # --- Input Parameters ---
  arguments:
    parameters:
      - name: srcType
      - name: srcRemoteURL
      - name: srcSecret
      - name: dstType
      - name: dstRemoteURL
      - name: dstSecret
      - name: specKey # The source file path (e.g., file.txt)
      - name: specOverride # The target file path (e.g., some/other.txt)
      - name: specMd5 # The md5 checksum of the source file (e.g., 5eb63bbbe01eeed093cb22bb8f5acdc3), optional
      - name: storageQuota # Additional parameter coming from ArtifactType

  entrypoint: pipeline

  templates:
    # --- Main Pipeline Entrypoint ---
    - name: pipeline
      steps:
        - - name: check-availability
            template: check-availability

        - - name: determine-size-s3
            template: determine-size-s3
            when: "{{workflow.parameters.srcType}} == 's3'"

        - - name: generate-volume-s3
            template: generate-volume
            when: " {{workflow.parameters.srcType}} == 's3'"
            arguments:
              parameters:
                - name: file-size
                  value: "{{steps.determine-size-s3.outputs.result}}"

        - - name: pull-s3
            template: pull-s3
            when: "{{workflow.parameters.srcType}} == 's3'"

        - - name: determine-size-http
            template: determine-size-http
            when: " {{workflow.parameters.srcType}} == 'http'"

        - - name: generate-volume-http
            template: generate-volume
            when: "{{workflow.parameters.srcType}} == 'http'"
            arguments:
              parameters:
                - name: file-size
                  value: "{{steps.determine-size-http.outputs.result}}"

        - - name: pull-http
            template: pull-http
            when: "{{workflow.parameters.srcType}} == 'http'"

        - - name: scan-clamav
            template: scan-clamav

        - - name: push
            template: push

    # --- Check Availability in Destination (aws-cli) ---
    - name: check-availability
      retryStrategy:
        limit: "2"

      script:
        image: amazon/aws-cli:latest
        command: [sh, -c]

        envFrom:
          - secretRef:
              name: s3-secret

        source: |
          if [[ ! -z ${{workflow.parameters.specMd5}} ]]; then
            BUCKET=$(echo "{{workflow.parameters.specKey}}" | cut -d/ -f1)
            KEY=$(echo "{{workflow.parameters.specKey}}" | cut -d/ -f2-)

            MD5=$(aws --endpoint-url "{{workflow.parameters.dstRemoteURL}}" s3api head-object --bucket "$BUCKET" --key "$KEY" --query ETag --output text --no-cli-pager)
            if [ $? -eq 254 ]; then
                echo "unavailable"
                exit 0
            fi

            if [ $? -eq 0 ]; then
              if [[ $MD5 != {{workflow.parameters.specMd5}} ]]; then
                echo "md5 mismatch, aborting"
                exit 1
              else
                echo "available"
                exit 0
              fi
            fi
            
            echo "unavailable"
            exit 0
          else
            aws --endpoint-url "{{workflow.parameters.srcRemoteURL}}" s3 ls "{{workflow.parameters.specKey}}" >/dev/null 2>&1
            if [ $? -eq 0 ]; then
                echo "available"
            else
                echo "unavailable"
            fi
          fi
          exit 0

    - name: determine-size-s3
      script:
        image: amazon/aws-cli:latest
        command: [sh, -c]

        envFrom:
          - secretRef:
              name: s3-secret

        source: |
          set -euo pipefail

          BUCKET=$(echo "{{workflow.parameters.specKey}}" | cut -d/ -f1)
          KEY=$(echo "{{workflow.parameters.specKey}}" | cut -d/ -f2-)

          FILE_SIZE_BYTES=$(aws --endpoint-url "{{workflow.parameters.srcRemoteURL}}" s3api head-object --bucket "$BUCKET" --key "$KEY" --query 'ContentLength' --output text)

          if [ -z "$FILE_SIZE_BYTES" ]; then
            exit 1
          fi
          if [[ "$FILE_SIZE_BYTES" -gt "{{workflow.parameters.storageQuota}}" ]]; then
            echo "File size $FILE_SIZE_BYTES bigger than storage quota of {{workflow.parameters.storageQuota}} bytes."
            exit 1
          fi

          echo "$(expr ${FILE_SIZE_BYTES} / 1024 + 100)Mi"

    - name: determine-size-http
      script:
        image: quay.io/curl/curl:latest
        command: [sh, -c]

        source: |
          set -euo pipefail

          FILE_SIZE_BYTES=$(curl -sI "{{workflow.parameters.srcRemoteURL}}/{{workflow.parameters.specKey}}" | grep -i Content-Length | awk '{print $2}')

          if [ -z "$FILE_SIZE_BYTES" ]; then
            exit 1
          fi
          if [[ "$FILE_SIZE_BYTES" -gt "{{workflow.parameters.storageQuota}}" ]]; then
            echo "File size $FILE_SIZE_BYTES bigger than storage quota of {{workflow.parameters.storageQuota}} bytes."
            exit 1
          fi

          FILE_SIZE_BYTES=$(echo $FILE_SIZE_BYTES | tr '\r' ' ')
          echo "$(expr ${FILE_SIZE_BYTES} / 1024 + 100)Mi"

    - name: generate-volume
      inputs:
        parameters:
          - name: file-size
      resource:
        action: create
        setOwnerReference: true
        manifest: |
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: {{ workflow.name }}
          spec:
            accessModes: ['ReadWriteOnce']
            resources:
              requests:
                storage: "{{inputs.parameters.file-size}}"

    - name: pull-s3
      volumes: &volumes
        - name: work-volume
          persistentVolumeClaim:
            claimName: "{{ workflow.name }}"
      script:
        image: amazon/aws-cli:latest
        command: [sh, -c]
        volumeMounts: &volumeMounts
          - name: work-volume
            mountPath: /data
        envFrom:
          - secretRef:
              name: s3-secret
        source: |
          set -euo pipefail

          mkdir -p /data/storage

          echo "Downloading {{workflow.parameters.srcRemoteURL}}/{{workflow.parameters.specKey}}..."
          aws --endpoint-url "{{workflow.parameters.srcRemoteURL}}" s3 cp "s3://{{workflow.parameters.specKey}}" "/data/storage/file"

    - name: pull-http
      volumes: *volumes
      script:
        image: quay.io/curl/curl:latest
        command: [sh, -c]
        volumeMounts: *volumeMounts

        source: |
          set -euo pipefail

          mkdir -p /data/storage

          echo "Downloading {{workflow.parameters.srcRemoteURL}}/{{workflow.parameters.specKey}}..."
          curl --output "/data/storage/file" "{{workflow.parameters.srcRemoteURL}}/{{workflow.parameters.specKey}}"

    - name: scan-clamav
      volumes: *volumes
      script:
        image: clamav/clamav:stable
        command: ["/bin/bash", "-c"]
        volumeMounts: *volumeMounts
        source: |
          set -euo pipefail

          echo "Scanning blob with ClamAV..."

          /usr/bin/clamscan --no-summary "/data/storage/file"
          SCAN_RESULT=$?

          if [ $SCAN_RESULT -eq 0 ]; then
            echo "✅ Scan successful."
          else
            echo "❌ Scan failed (Exit Code: $SCAN_RESULT)."
            exit 1
          fi

    - name: push
      volumes: *volumes
      script:
        image: amazon/aws-cli:latest
        command: [sh, -c]
        volumeMounts: *volumeMounts
        envFrom:
          - secretRef:
              name: s3-secret
        source: |
          set -euo pipefail

          echo "Uploading {{workflow.parameters.dstRemoteURL}}/{{workflow.parameters.specOverride}}..."
          aws --endpoint-url "{{workflow.parameters.dstRemoteURL}}" s3 cp "/data/storage/file" "s3://{{workflow.parameters.specOverride}}"
