apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: blob-pipeline
spec:
  retryStrategy:
    retryPolicy: OnError
    limit: 1

  serviceAccountName: arc-workflow
  securityContext:
    fsGroup: 65532
    runAsUser: 65532

  # Mount certificate bundle
  volumes:
    - name: ca-certificates
      configMap:
        name: "root-bundle"
        defaultMode: 0644
        optional: false
        items:
          - key: trust-bundle.pem
            path: trust-bundle.pem

  # --- Input Parameters ---
  arguments:
    parameters:
      - name: srcType
      - name: srcRemoteURL
      - name: srcSecret
      - name: dstType
      - name: dstRemoteURL
      - name: dstSecret
      - name: specKey # The source file path (e.g., file.txt)
      - name: specOverride # The target file path (e.g., some/other.txt)
      - name: specMd5 # The md5 checksum of the source file (e.g., 5eb63bbbe01eeed093cb22bb8f5acdc3), optional
      - name: storageQuota # Additional parameter coming from ArtifactType

  entrypoint: oci-pipeline

  templates:
    # --- Main Pipeline Entrypoint ---
    - name: oci-pipeline
      steps:
        - - name: check-availability
            template: check-availability

        - - name: determine-size-s3
            template: determine-size-s3
            when: "{{ steps.check-availability.outputs.result }} == 'unavailable' && {{workflow.parameters.srcType}} == 's3'"

        - - name: determine-size-http
            template: determine-size-http
            when: "{{ steps.check-availability.outputs.result }} == 'unavailable' && {{workflow.parameters.srcType}} == 'http'"

        - - name: generate-volume-s3
            template: generate-volume
            when: "{{ steps.check-availability.outputs.result }} == 'unavailable' && {{workflow.parameters.srcType}} == 's3'"
            arguments:
              parameters:
                - name: file-size-bytes
                  value: "{{steps.determine-size-s3.outputs.parameters.file-size-bytes}}"

        - - name: generate-volume-http
            template: generate-volume
            when: "{{ steps.check-availability.outputs.result }} == 'unavailable' && {{workflow.parameters.srcType}} == 'http'"
            arguments:
              parameters:
                - name: file-size-bytes
                  value: "{{steps.determine-size-s3.outputs.parameters.file-size-bytes}}"

        - - name: pull-s3
            template: pull-s3
            when: "{{ steps.check-availability.outputs.result }} == 'unavailable' && {{workflow.parameters.srcType}} == 's3'"

        - - name: pull-http
            template: pull-http
            when: "{{ steps.check-availability.outputs.result }} == 'unavailable' && {{workflow.parameters.srcType}} == 'http'"

    # --- Check Availability in Destination (aws-cli) ---
    - name: check-availability
      retryStrategy:
        limit: "2"

      script:
        image: amazon/aws-cli:latest
        command: [sh, -c]

        # Mount the volumes
        volumeMounts:
          - name: dst-secret-vol
            readOnly: true
            mountPath: /secrets/dst
          - mountPath: /etc/ssl/certs/
            name: ca-certificates
            readOnly: true

        envFrom:
          - secretRef:
              name: s3-secret

        source: |
          if [[ ! -z ${{workflow.parameters.specMd5}} ]]; then
            bucket=$(echo {{workflow.parameters.specKey}} | cut -d/ -f1)
            key=$(echo {{workflow.parameters.specKey}} | cut -d/ -f2-)

            md5=$(aws --endpoint-url "{{workflow.parameters.srcRemoteURL}}" s3api head-object --bucket $bucket --key $key --query ETag --output text)
            if [ "$EXIT_CODE" -eq 0 ]; then
              if [[ $md5 != *${{workflow.parameters.specMd5}}* ]]; then
                echo "md5 mismatch, aborting"
                exit 1
              else 
                echo "available"
              fi
            else
                echo "unavailable"
            fi
          else
            aws --endpoint-url "{{workflow.parameters.srcRemoteURL}}" s3 ls "{{workflow.parameters.specKey}}" >/dev/null 2>&1
            if [ "$EXIT_CODE" -eq 0 ]; then
                echo "available"
            else
                echo "unavailable"
            fi
          fi
          exit 0

    - name: determine-size-s3
      outputs:
        parameters:
          - name: file-size-bytes
            valueFrom:
              path: /tmp/file-size-bytes.txt
      script:
        image: amazon/aws-cli:latest
        command: [sh, -c]

        source: |
          set -euo pipefail

          bucket=$(echo {{workflow.parameters.specKey}} | cut -d/ -f1)
          key=$(echo {{workflow.parameters.specKey}} | cut -d/ -f2-)

          FILE_SIZE_BYTES=$(aws --endpoint-url "{{workflow.parameters.srcRemoteURL}}" s3api head-object --bucket "$bucket" --key "$key" --query 'ContentLength' --output text)

          if [ -z "$FILE_SIZE_BYTES" ]; then
            exit 1
          fi

          echo "Filesize is $FILE_SIZE_BYTES bytes"

          if [[ "$FILE_SIZE_BYTES" -lt "102400" ]]; then
              echo "100M" > /tmp/file-size-bytes.txt
          fi

          fileSizeInMi=$(echo "$(expr ${FILE_SIZE_BYTES} / 1024)M")

          echo "$FILE_SIZE_BYTES" > /tmp/file-size-bytes.txt

    - name: determine-size-http
      outputs:
        parameters:
          - name: file-size-bytes
            valueFrom:
              path: /tmp/file-size-bytes.txt
      script:
        image: quay.io/curl/curl:latest
        command: [sh, -c]

        source: |
          set -euo pipefail

          FILE_SIZE_BYTES=$(curl -sI "{{workflow.parameters.srcRemoteURL}}/{{workflow.parameters.specKey}}" | grep -i Content-Length | awk '{print $2}')

          if [ -z "$FILE_SIZE_BYTES" ]; then
            exit 1
          fi

          echo "Filesize is $FILE_SIZE_BYTES bytes"

          if [[ "$FILE_SIZE_BYTES" -lt "102400" ]]; then
              echo "100M" > /tmp/file-size-bytes.txt
          fi

          fileSizeInMi=$(echo "$(expr ${FILE_SIZE_BYTES} / 1024)M")

    - name: generate-volume
      inputs:
        parameters:
          - name: file-size-bytes
      resource:
        action: create
        setOwnerReference: true
        manifest: |
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: {{ workflow.name }}
          spec:
            accessModes: ['ReadWriteOnce']
            resources:
              requests:
                storage: '{{inputs.parameters.file-size-bytes}}'

    - name: pull-s3
      volumes: &volumes
        - name: work-volume
          persistentVolumeClaim:
            claimName: "{{ workflow.name }}"
      script:
        image: amazon/aws-cli:latest
        command: [sh, -c]
        volumeMounts: &volumeMounts
          - name: work-volume
            mountPath: /data

        source: |
          set -euo pipefail

          mkdir -p /data/storage

          echo "Downloading {{workflow.parameters.srcRemoteURL}}/{{workflow.parameters.specKey}}..."
          aws --endpoint-url "{{workflow.parameters.srcRemoteURL}}" s3 cp "s3://{{workflow.parameters.specKey}}" "/data/storage/file"

    - name: pull-http
      volumes: *volumes
      script:
        image: quay.io/curl/curl:latest
        command: [sh, -c]
        volumeMounts: *volumeMounts

        source: |
          set -euo pipefail

          mkdir -p /data/storage

          echo "Downloading {{workflow.parameters.srcRemoteURL}}/{{workflow.parameters.specKey}}..."
          curl --output "/data/storage/file" "{{workflow.parameters.srcRemoteURL}}/{{workflow.parameters.specKey}}"
