apiVersion: arc.bwi.de/v1alpha1
kind: Endpoint
metadata:
  name: src-s3
spec:
  type: s3 # Endpoint Type!
  remoteURL: s3://src.minio
  usage: PullOnly
  secretRef:
    name: s3-secret
---
apiVersion: arc.bwi.de/v1alpha1
kind: Endpoint
metadata:
  name: src-http
spec:
  type: http # Endpoint Type!
  remoteURL: https://raw.githubusercontent.com
  usage: PullOnly
---
apiVersion: arc.bwi.de/v1alpha1
kind: Endpoint
metadata:
  name: internal-s3
spec:
  type: s3 # Endpoint Type!
  remoteURL: s3://dst.minio
  secretRef:
    name: s3-secret
  usage: PushOnly
---
apiVersion: arc.bwi.de/v1alpha1
kind: Order
metadata:
  name: example-blob-order
spec:
  defaults:
    srcRef:
      name: src-s3
    dstRef:
      name: internal-s3
  artifacts:
    - type: blob # Artifact Type!
      spec:
        key: "opendefensecloud/artifact-conduit/refs/heads/feature/101-example-for-blob-file-transfer-s3/examples/blob/file.txt"
        md5: "5eb63bbbe01eeed093cb22bb8f5acdc3" # optional
        override: "test/result.txt" # optional, defaults to key
    - type: blob # Artifact Type!
      srcRef:
        name: src-http
      spec:
        key: "test/file.txt"
        md5: "5eb63bbbe01eeed093cb22bb8f5acdc3" # optional
        override: "test/result.txt" # optional, defaults to key
