// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ArtifactTypeRulesApplyConfiguration represents a declarative configuration of the ArtifactTypeRules type for use
// with apply.
type ArtifactTypeRulesApplyConfiguration struct {
	SrcTypes []string `json:"srcTypes,omitempty"`
	DstTypes []string `json:"dstTypes,omitempty"`
}

// ArtifactTypeRulesApplyConfiguration constructs a declarative configuration of the ArtifactTypeRules type for use with
// apply.
func ArtifactTypeRules() *ArtifactTypeRulesApplyConfiguration {
	return &ArtifactTypeRulesApplyConfiguration{}
}

// WithSrcTypes adds the given value to the SrcTypes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SrcTypes field.
func (b *ArtifactTypeRulesApplyConfiguration) WithSrcTypes(values ...string) *ArtifactTypeRulesApplyConfiguration {
	for i := range values {
		b.SrcTypes = append(b.SrcTypes, values[i])
	}
	return b
}

// WithDstTypes adds the given value to the DstTypes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DstTypes field.
func (b *ArtifactTypeRulesApplyConfiguration) WithDstTypes(values ...string) *ArtifactTypeRulesApplyConfiguration {
	for i := range values {
		b.DstTypes = append(b.DstTypes, values[i])
	}
	return b
}
