// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ArtifactWorkflowTTLSettingsApplyConfiguration represents a declarative configuration of the ArtifactWorkflowTTLSettings type for use
// with apply.
type ArtifactWorkflowTTLSettingsApplyConfiguration struct {
	// TTLSecondsAfterFinished specifies the time to live for the created ArtifactWorkflow(s) after successful completion.
	// After this time, the ArtifactWorkflow(s) are automatically deleted.
	// If unset finished ArtifactWorkflow(s) are automatically deleted immediately after completion.
	TTLSecondsAfterFinished *int64 `json:"ttlSecondsAfterFinished,omitempty"`
	// TTLSecondsAfterFailed specifies the time to live for the created ArtifactWorkflow(s) after failure.
	// After this time, the ArtifactWorkflow(s) are automatically deleted.
	// If unset finished ArtifactWorkflow(s) are retained indefinitely.
	TTLSecondsAfterFailed *int64 `json:"ttlSecondsAfterFailed,omitempty"`
}

// ArtifactWorkflowTTLSettingsApplyConfiguration constructs a declarative configuration of the ArtifactWorkflowTTLSettings type for use with
// apply.
func ArtifactWorkflowTTLSettings() *ArtifactWorkflowTTLSettingsApplyConfiguration {
	return &ArtifactWorkflowTTLSettingsApplyConfiguration{}
}

// WithTTLSecondsAfterFinished sets the TTLSecondsAfterFinished field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TTLSecondsAfterFinished field is set to the value of the last call.
func (b *ArtifactWorkflowTTLSettingsApplyConfiguration) WithTTLSecondsAfterFinished(value int64) *ArtifactWorkflowTTLSettingsApplyConfiguration {
	b.TTLSecondsAfterFinished = &value
	return b
}

// WithTTLSecondsAfterFailed sets the TTLSecondsAfterFailed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TTLSecondsAfterFailed field is set to the value of the last call.
func (b *ArtifactWorkflowTTLSettingsApplyConfiguration) WithTTLSecondsAfterFailed(value int64) *ArtifactWorkflowTTLSettingsApplyConfiguration {
	b.TTLSecondsAfterFailed = &value
	return b
}
