// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ArtifactWorkflowTTLSettingsApplyConfiguration represents a declarative configuration of the ArtifactWorkflowTTLSettings type for use
// with apply.
type ArtifactWorkflowTTLSettingsApplyConfiguration struct {
	// TTLAfterFinished specifies the time to live for the created ArtifactWorkflow(s) after successful completion.
	// After this time, the ArtifactWorkflow(s) are automatically deleted.
	// If unset ArtifactWorkflow(s) are automatically deleted immediately after completion.
	TTLAfterFinished *v1.Duration `json:"ttlAfterFinished,omitempty"`
	// TTLAfterFailed specifies the time to live for the created ArtifactWorkflow(s) after failure.
	// After this time, the ArtifactWorkflow(s) are automatically deleted.
	// If unset ArtifactWorkflow(s) are retained indefinitely.
	TTLAfterFailed *v1.Duration `json:"ttlAfterFailed,omitempty"`
}

// ArtifactWorkflowTTLSettingsApplyConfiguration constructs a declarative configuration of the ArtifactWorkflowTTLSettings type for use with
// apply.
func ArtifactWorkflowTTLSettings() *ArtifactWorkflowTTLSettingsApplyConfiguration {
	return &ArtifactWorkflowTTLSettingsApplyConfiguration{}
}

// WithTTLAfterFinished sets the TTLAfterFinished field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TTLAfterFinished field is set to the value of the last call.
func (b *ArtifactWorkflowTTLSettingsApplyConfiguration) WithTTLAfterFinished(value v1.Duration) *ArtifactWorkflowTTLSettingsApplyConfiguration {
	b.TTLAfterFinished = &value
	return b
}

// WithTTLAfterFailed sets the TTLAfterFailed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TTLAfterFailed field is set to the value of the last call.
func (b *ArtifactWorkflowTTLSettingsApplyConfiguration) WithTTLAfterFailed(value v1.Duration) *ArtifactWorkflowTTLSettingsApplyConfiguration {
	b.TTLAfterFailed = &value
	return b
}
