// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	arcv1alpha1 "go.opendefense.cloud/arc/api/arc/v1alpha1"
)

// ArtifactWorkflowStatusApplyConfiguration represents a declarative configuration of the ArtifactWorkflowStatus type for use
// with apply.
type ArtifactWorkflowStatusApplyConfiguration struct {
	Phase   *arcv1alpha1.WorkflowPhase `json:"phase,omitempty"`
	Message *string                    `json:"message,omitempty"`
}

// ArtifactWorkflowStatusApplyConfiguration constructs a declarative configuration of the ArtifactWorkflowStatus type for use with
// apply.
func ArtifactWorkflowStatus() *ArtifactWorkflowStatusApplyConfiguration {
	return &ArtifactWorkflowStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *ArtifactWorkflowStatusApplyConfiguration) WithPhase(value arcv1alpha1.WorkflowPhase) *ArtifactWorkflowStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *ArtifactWorkflowStatusApplyConfiguration) WithMessage(value string) *ArtifactWorkflowStatusApplyConfiguration {
	b.Message = &value
	return b
}
