// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// ArtifactWorkflowSpecApplyConfiguration represents a declarative configuration of the ArtifactWorkflowSpec type for use
// with apply.
type ArtifactWorkflowSpecApplyConfiguration struct {
	Type         *string                                       `json:"type,omitempty"`
	Parameters   []ArtifactWorkflowParameterApplyConfiguration `json:"parameters,omitempty"`
	SrcSecretRef *v1.LocalObjectReference                      `json:"srcSecretRef,omitempty"`
	DstSecretRef *v1.LocalObjectReference                      `json:"dstSecretRef,omitempty"`
}

// ArtifactWorkflowSpecApplyConfiguration constructs a declarative configuration of the ArtifactWorkflowSpec type for use with
// apply.
func ArtifactWorkflowSpec() *ArtifactWorkflowSpecApplyConfiguration {
	return &ArtifactWorkflowSpecApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *ArtifactWorkflowSpecApplyConfiguration) WithType(value string) *ArtifactWorkflowSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithParameters adds the given value to the Parameters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Parameters field.
func (b *ArtifactWorkflowSpecApplyConfiguration) WithParameters(values ...*ArtifactWorkflowParameterApplyConfiguration) *ArtifactWorkflowSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithParameters")
		}
		b.Parameters = append(b.Parameters, *values[i])
	}
	return b
}

// WithSrcSecretRef sets the SrcSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SrcSecretRef field is set to the value of the last call.
func (b *ArtifactWorkflowSpecApplyConfiguration) WithSrcSecretRef(value v1.LocalObjectReference) *ArtifactWorkflowSpecApplyConfiguration {
	b.SrcSecretRef = &value
	return b
}

// WithDstSecretRef sets the DstSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DstSecretRef field is set to the value of the last call.
func (b *ArtifactWorkflowSpecApplyConfiguration) WithDstSecretRef(value v1.LocalObjectReference) *ArtifactWorkflowSpecApplyConfiguration {
	b.DstSecretRef = &value
	return b
}
