// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ArtifactWorkflowTTLSettingsApplyConfiguration represents a declarative configuration of the ArtifactWorkflowTTLSettings type for use
// with apply.
type ArtifactWorkflowTTLSettingsApplyConfiguration struct {
	// TTLDurationAfterFinished specifies the time to live for the created ArtifactWorkflow(s) after successful completion.
	// After this time, the ArtifactWorkflow(s) are automatically deleted.
	// If unset finished ArtifactWorkflow(s) are automatically deleted immediately after completion.
	TTLDurationAfterFinished *v1.Duration `json:"ttlDurationAfterFinished,omitempty"`
	// TTLDurationAfterFailed specifies the time to live for the created ArtifactWorkflow(s) after failure.
	// After this time, the ArtifactWorkflow(s) are automatically deleted.
	// If unset finished ArtifactWorkflow(s) are retained indefinitely.
	TTLDurationAfterFailed *v1.Duration `json:"ttlDurationAfterFailed,omitempty"`
}

// ArtifactWorkflowTTLSettingsApplyConfiguration constructs a declarative configuration of the ArtifactWorkflowTTLSettings type for use with
// apply.
func ArtifactWorkflowTTLSettings() *ArtifactWorkflowTTLSettingsApplyConfiguration {
	return &ArtifactWorkflowTTLSettingsApplyConfiguration{}
}

// WithTTLDurationAfterFinished sets the TTLDurationAfterFinished field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TTLDurationAfterFinished field is set to the value of the last call.
func (b *ArtifactWorkflowTTLSettingsApplyConfiguration) WithTTLDurationAfterFinished(value v1.Duration) *ArtifactWorkflowTTLSettingsApplyConfiguration {
	b.TTLDurationAfterFinished = &value
	return b
}

// WithTTLDurationAfterFailed sets the TTLDurationAfterFailed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TTLDurationAfterFailed field is set to the value of the last call.
func (b *ArtifactWorkflowTTLSettingsApplyConfiguration) WithTTLDurationAfterFailed(value v1.Duration) *ArtifactWorkflowTTLSettingsApplyConfiguration {
	b.TTLDurationAfterFailed = &value
	return b
}
