// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// ArtifactWorkflowSpecApplyConfiguration represents a declarative configuration of the ArtifactWorkflowSpec type for use
// with apply.
type ArtifactWorkflowSpecApplyConfiguration struct {
	Type      *string                  `json:"type,omitempty"`
	SecretRef *v1.LocalObjectReference `json:"secretRef,omitempty"`
}

// ArtifactWorkflowSpecApplyConfiguration constructs a declarative configuration of the ArtifactWorkflowSpec type for use with
// apply.
func ArtifactWorkflowSpec() *ArtifactWorkflowSpecApplyConfiguration {
	return &ArtifactWorkflowSpecApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *ArtifactWorkflowSpecApplyConfiguration) WithType(value string) *ArtifactWorkflowSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *ArtifactWorkflowSpecApplyConfiguration) WithSecretRef(value v1.LocalObjectReference) *ArtifactWorkflowSpecApplyConfiguration {
	b.SecretRef = &value
	return b
}
