// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ArtifactTypeSpecApplyConfiguration represents a declarative configuration of the ArtifactTypeSpec type for use
// with apply.
//
// ArtifactTypeSpec specifies a type of artifact and describes the corresponding workflow.
type ArtifactTypeSpecApplyConfiguration struct {
	ArtifactWorkflowTTLSettingsApplyConfiguration `json:",inline"`
	// Rules defines a set of rules for this type.
	Rules *ArtifactTypeRulesApplyConfiguration `json:"rules,omitempty"`
	// Parameters defines extra parameters for the Workflow to use.
	// These parameters will override parameters coming from ArtifactWorkflows.
	Parameters []ArtifactWorkflowParameterApplyConfiguration `json:"parameters,omitempty"`
	// WorkflowTemplateRef specifies the corresponding Workflow for this type of artifact.
	WorkflowTemplateRef *ArtifactTypeTemplateRefApplyConfiguration `json:"workflowTemplateRef,omitempty"`
}

// ArtifactTypeSpecApplyConfiguration constructs a declarative configuration of the ArtifactTypeSpec type for use with
// apply.
func ArtifactTypeSpec() *ArtifactTypeSpecApplyConfiguration {
	return &ArtifactTypeSpecApplyConfiguration{}
}

// WithTTLSecondsAfterFinished sets the TTLSecondsAfterFinished field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TTLSecondsAfterFinished field is set to the value of the last call.
func (b *ArtifactTypeSpecApplyConfiguration) WithTTLSecondsAfterFinished(value int64) *ArtifactTypeSpecApplyConfiguration {
	b.ArtifactWorkflowTTLSettingsApplyConfiguration.TTLSecondsAfterFinished = &value
	return b
}

// WithTTLSecondsAfterFailed sets the TTLSecondsAfterFailed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TTLSecondsAfterFailed field is set to the value of the last call.
func (b *ArtifactTypeSpecApplyConfiguration) WithTTLSecondsAfterFailed(value int64) *ArtifactTypeSpecApplyConfiguration {
	b.ArtifactWorkflowTTLSettingsApplyConfiguration.TTLSecondsAfterFailed = &value
	return b
}

// WithRules sets the Rules field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Rules field is set to the value of the last call.
func (b *ArtifactTypeSpecApplyConfiguration) WithRules(value *ArtifactTypeRulesApplyConfiguration) *ArtifactTypeSpecApplyConfiguration {
	b.Rules = value
	return b
}

// WithParameters adds the given value to the Parameters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Parameters field.
func (b *ArtifactTypeSpecApplyConfiguration) WithParameters(values ...*ArtifactWorkflowParameterApplyConfiguration) *ArtifactTypeSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithParameters")
		}
		b.Parameters = append(b.Parameters, *values[i])
	}
	return b
}

// WithWorkflowTemplateRef sets the WorkflowTemplateRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkflowTemplateRef field is set to the value of the last call.
func (b *ArtifactTypeSpecApplyConfiguration) WithWorkflowTemplateRef(value *ArtifactTypeTemplateRefApplyConfiguration) *ArtifactTypeSpecApplyConfiguration {
	b.WorkflowTemplateRef = value
	return b
}
