// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ArtifactWorkflowSpecApplyConfiguration represents a declarative configuration of the ArtifactWorkflowSpec type for use
// with apply.
//
// ArtifactWorkflowSpec specifies a single artifact which is translated into a corresponding Workflow based on its type.
type ArtifactWorkflowSpecApplyConfiguration struct {
	ArtifactWorkflowTTLSettingsApplyConfiguration `json:",inline"`
	// WorkflowTemplateRef specifies the corresponding Workflow for this ArtifactWorkflow as derived from ArtifactType
	WorkflowTemplateRef *ArtifactTypeTemplateRefApplyConfiguration `json:"workflowTemplateRef,omitempty"`
	// Parameters defines the key-value pairs, that are passed to the underlying Workflow.
	Parameters []ArtifactWorkflowParameterApplyConfiguration `json:"parameters,omitempty"`
	// SrcSecretRef references the secret containing credentials for the source.
	SrcSecretRef *v1.LocalObjectReference `json:"srcSecretRef,omitempty"`
	// DstSecretRef references the secret containing credentials for the destination.
	DstSecretRef *v1.LocalObjectReference `json:"dstSecretRef,omitempty"`
	// Cron specifies options which determine when the order should be scheduled.
	Cron *CronApplyConfiguration `json:"cron,omitempty"`
}

// ArtifactWorkflowSpecApplyConfiguration constructs a declarative configuration of the ArtifactWorkflowSpec type for use with
// apply.
func ArtifactWorkflowSpec() *ArtifactWorkflowSpecApplyConfiguration {
	return &ArtifactWorkflowSpecApplyConfiguration{}
}

// WithTTLDurationAfterFinished sets the TTLDurationAfterFinished field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TTLDurationAfterFinished field is set to the value of the last call.
func (b *ArtifactWorkflowSpecApplyConfiguration) WithTTLDurationAfterFinished(value metav1.Duration) *ArtifactWorkflowSpecApplyConfiguration {
	b.ArtifactWorkflowTTLSettingsApplyConfiguration.TTLDurationAfterFinished = &value
	return b
}

// WithTTLDurationAfterFailed sets the TTLDurationAfterFailed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TTLDurationAfterFailed field is set to the value of the last call.
func (b *ArtifactWorkflowSpecApplyConfiguration) WithTTLDurationAfterFailed(value metav1.Duration) *ArtifactWorkflowSpecApplyConfiguration {
	b.ArtifactWorkflowTTLSettingsApplyConfiguration.TTLDurationAfterFailed = &value
	return b
}

// WithWorkflowTemplateRef sets the WorkflowTemplateRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkflowTemplateRef field is set to the value of the last call.
func (b *ArtifactWorkflowSpecApplyConfiguration) WithWorkflowTemplateRef(value *ArtifactTypeTemplateRefApplyConfiguration) *ArtifactWorkflowSpecApplyConfiguration {
	b.WorkflowTemplateRef = value
	return b
}

// WithParameters adds the given value to the Parameters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Parameters field.
func (b *ArtifactWorkflowSpecApplyConfiguration) WithParameters(values ...*ArtifactWorkflowParameterApplyConfiguration) *ArtifactWorkflowSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithParameters")
		}
		b.Parameters = append(b.Parameters, *values[i])
	}
	return b
}

// WithSrcSecretRef sets the SrcSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SrcSecretRef field is set to the value of the last call.
func (b *ArtifactWorkflowSpecApplyConfiguration) WithSrcSecretRef(value v1.LocalObjectReference) *ArtifactWorkflowSpecApplyConfiguration {
	b.SrcSecretRef = &value
	return b
}

// WithDstSecretRef sets the DstSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DstSecretRef field is set to the value of the last call.
func (b *ArtifactWorkflowSpecApplyConfiguration) WithDstSecretRef(value v1.LocalObjectReference) *ArtifactWorkflowSpecApplyConfiguration {
	b.DstSecretRef = &value
	return b
}

// WithCron sets the Cron field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cron field is set to the value of the last call.
func (b *ArtifactWorkflowSpecApplyConfiguration) WithCron(value *CronApplyConfiguration) *ArtifactWorkflowSpecApplyConfiguration {
	b.Cron = value
	return b
}
