// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	arcv1alpha1 "go.opendefense.cloud/arc/api/arc/v1alpha1"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ArtifactWorkflowStatusApplyConfiguration represents a declarative configuration of the ArtifactWorkflowStatus type for use
// with apply.
//
// ArtifactWorkflowStatus defines the observed state of ArtifactWorkflow
type ArtifactWorkflowStatusApplyConfiguration struct {
	WorkflowStatusApplyConfiguration `json:",inline"`
	// LastReconcileAt is the last time the Order was reconciled
	LastReconcileAt *v1.Time `json:"lastReconcileAt,omitempty"`
	// LastForceAt is the last time a force reconciliation was requested
	LastForceAt *v1.Time `json:"lastForceAt,omitempty"`
	// ActiveWorkflowRef tracks the currently spawned workflow, if cron is used.
	// It resets after a successful or failed run.
	ActiveWorkflowRef *corev1.LocalObjectReference `json:"activeWorkflowRef,omitempty"`
}

// ArtifactWorkflowStatusApplyConfiguration constructs a declarative configuration of the ArtifactWorkflowStatus type for use with
// apply.
func ArtifactWorkflowStatus() *ArtifactWorkflowStatusApplyConfiguration {
	return &ArtifactWorkflowStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *ArtifactWorkflowStatusApplyConfiguration) WithPhase(value arcv1alpha1.WorkflowPhase) *ArtifactWorkflowStatusApplyConfiguration {
	b.WorkflowStatusApplyConfiguration.Phase = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *ArtifactWorkflowStatusApplyConfiguration) WithMessage(value string) *ArtifactWorkflowStatusApplyConfiguration {
	b.WorkflowStatusApplyConfiguration.Message = &value
	return b
}

// WithCompletionTime sets the CompletionTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompletionTime field is set to the value of the last call.
func (b *ArtifactWorkflowStatusApplyConfiguration) WithCompletionTime(value v1.Time) *ArtifactWorkflowStatusApplyConfiguration {
	b.WorkflowStatusApplyConfiguration.CompletionTime = &value
	return b
}

// WithFailureTime sets the FailureTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailureTime field is set to the value of the last call.
func (b *ArtifactWorkflowStatusApplyConfiguration) WithFailureTime(value v1.Time) *ArtifactWorkflowStatusApplyConfiguration {
	b.WorkflowStatusApplyConfiguration.FailureTime = &value
	return b
}

// WithLastScheduled sets the LastScheduled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastScheduled field is set to the value of the last call.
func (b *ArtifactWorkflowStatusApplyConfiguration) WithLastScheduled(value v1.Time) *ArtifactWorkflowStatusApplyConfiguration {
	b.WorkflowStatusApplyConfiguration.LastScheduled = &value
	return b
}

// WithSucceeded sets the Succeeded field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Succeeded field is set to the value of the last call.
func (b *ArtifactWorkflowStatusApplyConfiguration) WithSucceeded(value int64) *ArtifactWorkflowStatusApplyConfiguration {
	b.WorkflowStatusApplyConfiguration.Succeeded = &value
	return b
}

// WithFailed sets the Failed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Failed field is set to the value of the last call.
func (b *ArtifactWorkflowStatusApplyConfiguration) WithFailed(value int64) *ArtifactWorkflowStatusApplyConfiguration {
	b.WorkflowStatusApplyConfiguration.Failed = &value
	return b
}

// WithLastReconcileAt sets the LastReconcileAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastReconcileAt field is set to the value of the last call.
func (b *ArtifactWorkflowStatusApplyConfiguration) WithLastReconcileAt(value v1.Time) *ArtifactWorkflowStatusApplyConfiguration {
	b.LastReconcileAt = &value
	return b
}

// WithLastForceAt sets the LastForceAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastForceAt field is set to the value of the last call.
func (b *ArtifactWorkflowStatusApplyConfiguration) WithLastForceAt(value v1.Time) *ArtifactWorkflowStatusApplyConfiguration {
	b.LastForceAt = &value
	return b
}

// WithActiveWorkflowRef sets the ActiveWorkflowRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActiveWorkflowRef field is set to the value of the last call.
func (b *ArtifactWorkflowStatusApplyConfiguration) WithActiveWorkflowRef(value corev1.LocalObjectReference) *ArtifactWorkflowStatusApplyConfiguration {
	b.ActiveWorkflowRef = &value
	return b
}
