// Copyright 2025 BWI GmbH and Artefact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ArtifactTypeDefinitionRulesApplyConfiguration represents a declarative configuration of the ArtifactTypeDefinitionRules type for use
// with apply.
type ArtifactTypeDefinitionRulesApplyConfiguration struct {
	SrcTypes []string `json:"srcTypes,omitempty"`
	DstTypes []string `json:"dstType,omitempty"`
}

// ArtifactTypeDefinitionRulesApplyConfiguration constructs a declarative configuration of the ArtifactTypeDefinitionRules type for use with
// apply.
func ArtifactTypeDefinitionRules() *ArtifactTypeDefinitionRulesApplyConfiguration {
	return &ArtifactTypeDefinitionRulesApplyConfiguration{}
}

// WithSrcTypes adds the given value to the SrcTypes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SrcTypes field.
func (b *ArtifactTypeDefinitionRulesApplyConfiguration) WithSrcTypes(values ...string) *ArtifactTypeDefinitionRulesApplyConfiguration {
	for i := range values {
		b.SrcTypes = append(b.SrcTypes, values[i])
	}
	return b
}

// WithDstTypes adds the given value to the DstTypes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DstTypes field.
func (b *ArtifactTypeDefinitionRulesApplyConfiguration) WithDstTypes(values ...string) *ArtifactTypeDefinitionRulesApplyConfiguration {
	for i := range values {
		b.DstTypes = append(b.DstTypes, values[i])
	}
	return b
}
