// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ArtifactTypeTemplateRefApplyConfiguration represents a declarative configuration of the ArtifactTypeTemplateRef type for use
// with apply.
type ArtifactTypeTemplateRefApplyConfiguration struct {
	Name         *string `json:"name,omitempty"`
	ClusterScope *bool   `json:"clusterScope,omitempty"`
}

// ArtifactTypeTemplateRefApplyConfiguration constructs a declarative configuration of the ArtifactTypeTemplateRef type for use with
// apply.
func ArtifactTypeTemplateRef() *ArtifactTypeTemplateRefApplyConfiguration {
	return &ArtifactTypeTemplateRefApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ArtifactTypeTemplateRefApplyConfiguration) WithName(value string) *ArtifactTypeTemplateRefApplyConfiguration {
	b.Name = &value
	return b
}

// WithClusterScope sets the ClusterScope field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterScope field is set to the value of the last call.
func (b *ArtifactTypeTemplateRefApplyConfiguration) WithClusterScope(value bool) *ArtifactTypeTemplateRefApplyConfiguration {
	b.ClusterScope = &value
	return b
}
