// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ArtifactWorkflowParameterApplyConfiguration represents a declarative configuration of the ArtifactWorkflowParameter type for use
// with apply.
type ArtifactWorkflowParameterApplyConfiguration struct {
	Name  *string `json:"name,omitempty"`
	Value *string `json:"value,omitempty"`
}

// ArtifactWorkflowParameterApplyConfiguration constructs a declarative configuration of the ArtifactWorkflowParameter type for use with
// apply.
func ArtifactWorkflowParameter() *ArtifactWorkflowParameterApplyConfiguration {
	return &ArtifactWorkflowParameterApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ArtifactWorkflowParameterApplyConfiguration) WithName(value string) *ArtifactWorkflowParameterApplyConfiguration {
	b.Name = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *ArtifactWorkflowParameterApplyConfiguration) WithValue(value string) *ArtifactWorkflowParameterApplyConfiguration {
	b.Value = &value
	return b
}
