// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// ArtifactTypeDefinitionSpecApplyConfiguration represents a declarative configuration of the ArtifactTypeDefinitionSpec type for use
// with apply.
type ArtifactTypeDefinitionSpecApplyConfiguration struct {
	Rules               *ArtifactTypeDefinitionRulesApplyConfiguration `json:"rules,omitempty"`
	Defaults            *OrderDefaultsApplyConfiguration               `json:"defaults,omitempty"`
	WorkflowTemplateRef *v1.LocalObjectReference                       `json:"workflowTemplateRef,omitempty"`
}

// ArtifactTypeDefinitionSpecApplyConfiguration constructs a declarative configuration of the ArtifactTypeDefinitionSpec type for use with
// apply.
func ArtifactTypeDefinitionSpec() *ArtifactTypeDefinitionSpecApplyConfiguration {
	return &ArtifactTypeDefinitionSpecApplyConfiguration{}
}

// WithRules sets the Rules field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Rules field is set to the value of the last call.
func (b *ArtifactTypeDefinitionSpecApplyConfiguration) WithRules(value *ArtifactTypeDefinitionRulesApplyConfiguration) *ArtifactTypeDefinitionSpecApplyConfiguration {
	b.Rules = value
	return b
}

// WithDefaults sets the Defaults field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Defaults field is set to the value of the last call.
func (b *ArtifactTypeDefinitionSpecApplyConfiguration) WithDefaults(value *OrderDefaultsApplyConfiguration) *ArtifactTypeDefinitionSpecApplyConfiguration {
	b.Defaults = value
	return b
}

// WithWorkflowTemplateRef sets the WorkflowTemplateRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkflowTemplateRef field is set to the value of the last call.
func (b *ArtifactTypeDefinitionSpecApplyConfiguration) WithWorkflowTemplateRef(value v1.LocalObjectReference) *ArtifactTypeDefinitionSpecApplyConfiguration {
	b.WorkflowTemplateRef = &value
	return b
}
