// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	arcv1alpha1 "go.opendefense.cloud/arc/api/arc/v1alpha1"
)

// CronApplyConfiguration represents a declarative configuration of the Cron type for use
// with apply.
type CronApplyConfiguration struct {
	Timezone                *string                        `json:"timezone,omitempty"`
	ConcurrencyPolicy       *arcv1alpha1.ConcurrencyPolicy `json:"concurrencyPolicy,omitempty"`
	StartingDeadlineSeconds *int64                         `json:"startingDeadlineSeconds,omitempty"`
	Schedules               []string                       `json:"schedules,omitempty"`
	When                    *string                        `json:"when,omitempty"`
}

// CronApplyConfiguration constructs a declarative configuration of the Cron type for use with
// apply.
func Cron() *CronApplyConfiguration {
	return &CronApplyConfiguration{}
}

// WithTimezone sets the Timezone field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timezone field is set to the value of the last call.
func (b *CronApplyConfiguration) WithTimezone(value string) *CronApplyConfiguration {
	b.Timezone = &value
	return b
}

// WithConcurrencyPolicy sets the ConcurrencyPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConcurrencyPolicy field is set to the value of the last call.
func (b *CronApplyConfiguration) WithConcurrencyPolicy(value arcv1alpha1.ConcurrencyPolicy) *CronApplyConfiguration {
	b.ConcurrencyPolicy = &value
	return b
}

// WithStartingDeadlineSeconds sets the StartingDeadlineSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartingDeadlineSeconds field is set to the value of the last call.
func (b *CronApplyConfiguration) WithStartingDeadlineSeconds(value int64) *CronApplyConfiguration {
	b.StartingDeadlineSeconds = &value
	return b
}

// WithSchedules adds the given value to the Schedules field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Schedules field.
func (b *CronApplyConfiguration) WithSchedules(values ...string) *CronApplyConfiguration {
	for i := range values {
		b.Schedules = append(b.Schedules, values[i])
	}
	return b
}

// WithWhen sets the When field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the When field is set to the value of the last call.
func (b *CronApplyConfiguration) WithWhen(value string) *CronApplyConfiguration {
	b.When = &value
	return b
}
