// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// EndpointSpecApplyConfiguration represents a declarative configuration of the EndpointSpec type for use
// with apply.
type EndpointSpecApplyConfiguration struct {
	Type      *string                  `json:"type,omitempty"`
	RemoteURL *string                  `json:"remoteURL,omitempty"`
	SecretRef *v1.LocalObjectReference `json:"credentialRef,omitempty"`
}

// EndpointSpecApplyConfiguration constructs a declarative configuration of the EndpointSpec type for use with
// apply.
func EndpointSpec() *EndpointSpecApplyConfiguration {
	return &EndpointSpecApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *EndpointSpecApplyConfiguration) WithType(value string) *EndpointSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithRemoteURL sets the RemoteURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemoteURL field is set to the value of the last call.
func (b *EndpointSpecApplyConfiguration) WithRemoteURL(value string) *EndpointSpecApplyConfiguration {
	b.RemoteURL = &value
	return b
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *EndpointSpecApplyConfiguration) WithSecretRef(value v1.LocalObjectReference) *EndpointSpecApplyConfiguration {
	b.SecretRef = &value
	return b
}
