// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// EndpointStatusApplyConfiguration represents a declarative configuration of the EndpointStatus type for use
// with apply.
//
// EndpointStatus defines the observed state of Endpoint
type EndpointStatusApplyConfiguration struct {
	// Conditions represent the latest available observations of the Endpoint's state.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// ObservedGeneration is the .metadata.generation the conditions were computed from.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// LastProbeTime is when the connection to spec.remoteURL was last attempted.
	LastProbeTime *metav1.Time `json:"lastProbeTime,omitempty"`
}

// EndpointStatusApplyConfiguration constructs a declarative configuration of the EndpointStatus type for use with
// apply.
func EndpointStatus() *EndpointStatusApplyConfiguration {
	return &EndpointStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *EndpointStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *EndpointStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *EndpointStatusApplyConfiguration) WithObservedGeneration(value int64) *EndpointStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithLastProbeTime sets the LastProbeTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastProbeTime field is set to the value of the last call.
func (b *EndpointStatusApplyConfiguration) WithLastProbeTime(value metav1.Time) *EndpointStatusApplyConfiguration {
	b.LastProbeTime = &value
	return b
}
