// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	workflowv1alpha1 "github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1"
	v1 "k8s.io/api/core/v1"
)

// FragmentSpecApplyConfiguration represents a declarative configuration of the FragmentSpec type for use
// with apply.
type FragmentSpecApplyConfiguration struct {
	Type       *string                      `json:"type,omitempty"`
	Parameters []workflowv1alpha1.Parameter `json:"parameters,omitempty"`
	SecretRef  *v1.LocalObjectReference     `json:"secretRef,omitempty"`
}

// FragmentSpecApplyConfiguration constructs a declarative configuration of the FragmentSpec type for use with
// apply.
func FragmentSpec() *FragmentSpecApplyConfiguration {
	return &FragmentSpecApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *FragmentSpecApplyConfiguration) WithType(value string) *FragmentSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithParameters adds the given value to the Parameters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Parameters field.
func (b *FragmentSpecApplyConfiguration) WithParameters(values ...workflowv1alpha1.Parameter) *FragmentSpecApplyConfiguration {
	for i := range values {
		b.Parameters = append(b.Parameters, values[i])
	}
	return b
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *FragmentSpecApplyConfiguration) WithSecretRef(value v1.LocalObjectReference) *FragmentSpecApplyConfiguration {
	b.SecretRef = &value
	return b
}
