// Copyright 2025 BWI GmbH and Artefact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// FragmentSpecApplyConfiguration represents a declarative configuration of the FragmentSpec type for use
// with apply.
type FragmentSpecApplyConfiguration struct {
	Type   *string                  `json:"type,omitempty"`
	SrcRef *v1.LocalObjectReference `json:"srcRef,omitempty"`
	DstRef *v1.LocalObjectReference `json:"dstRef,omitempty"`
	Spec   *runtime.RawExtension    `json:"spec,omitempty"`
}

// FragmentSpecApplyConfiguration constructs a declarative configuration of the FragmentSpec type for use with
// apply.
func FragmentSpec() *FragmentSpecApplyConfiguration {
	return &FragmentSpecApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *FragmentSpecApplyConfiguration) WithType(value string) *FragmentSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithSrcRef sets the SrcRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SrcRef field is set to the value of the last call.
func (b *FragmentSpecApplyConfiguration) WithSrcRef(value v1.LocalObjectReference) *FragmentSpecApplyConfiguration {
	b.SrcRef = &value
	return b
}

// WithDstRef sets the DstRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DstRef field is set to the value of the last call.
func (b *FragmentSpecApplyConfiguration) WithDstRef(value v1.LocalObjectReference) *FragmentSpecApplyConfiguration {
	b.DstRef = &value
	return b
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *FragmentSpecApplyConfiguration) WithSpec(value runtime.RawExtension) *FragmentSpecApplyConfiguration {
	b.Spec = &value
	return b
}
