// Copyright 2025 BWI GmbH and Artefact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// OrderStatusApplyConfiguration represents a declarative configuration of the OrderStatus type for use
// with apply.
type OrderStatusApplyConfiguration struct {
	Fragments map[string]v1.ObjectReference `json:"fragments,omitempty"`
}

// OrderStatusApplyConfiguration constructs a declarative configuration of the OrderStatus type for use with
// apply.
func OrderStatus() *OrderStatusApplyConfiguration {
	return &OrderStatusApplyConfiguration{}
}

// WithFragments puts the entries into the Fragments field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Fragments field,
// overwriting an existing map entries in Fragments field with the same key.
func (b *OrderStatusApplyConfiguration) WithFragments(entries map[string]v1.ObjectReference) *OrderStatusApplyConfiguration {
	if b.Fragments == nil && len(entries) > 0 {
		b.Fragments = make(map[string]v1.ObjectReference, len(entries))
	}
	for k, v := range entries {
		b.Fragments[k] = v
	}
	return b
}
