// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	arcv1alpha1 "go.opendefense.cloud/arc/api/arc/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// OrderArtifactWorkflowStatusApplyConfiguration represents a declarative configuration of the OrderArtifactWorkflowStatus type for use
// with apply.
type OrderArtifactWorkflowStatusApplyConfiguration struct {
	WorkflowStatusApplyConfiguration `json:",inline"`
	// ArtifactIndex references back the index the corresponding artifact has in the .Spec
	ArtifactIndex *int `json:"artifactIndex,omitempty"`
	// TTLSecondsAfterCompletion specifies the time to live for the created ArtifactWorkflow(s) after completion.
	// After this time, the ArtifactWorkflow(s) are automatically deleted.
	// If unset, the ArtifactWorkflow(s) are automatically deleted immediately after completion.
	TTLSecondsAfterCompletion *int64 `json:"TTLSecondsAfterCompletion,omitempty"`
}

// OrderArtifactWorkflowStatusApplyConfiguration constructs a declarative configuration of the OrderArtifactWorkflowStatus type for use with
// apply.
func OrderArtifactWorkflowStatus() *OrderArtifactWorkflowStatusApplyConfiguration {
	return &OrderArtifactWorkflowStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *OrderArtifactWorkflowStatusApplyConfiguration) WithPhase(value arcv1alpha1.WorkflowPhase) *OrderArtifactWorkflowStatusApplyConfiguration {
	b.WorkflowStatusApplyConfiguration.Phase = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *OrderArtifactWorkflowStatusApplyConfiguration) WithMessage(value string) *OrderArtifactWorkflowStatusApplyConfiguration {
	b.WorkflowStatusApplyConfiguration.Message = &value
	return b
}

// WithCompletionTime sets the CompletionTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompletionTime field is set to the value of the last call.
func (b *OrderArtifactWorkflowStatusApplyConfiguration) WithCompletionTime(value v1.Time) *OrderArtifactWorkflowStatusApplyConfiguration {
	b.WorkflowStatusApplyConfiguration.CompletionTime = &value
	return b
}

// WithLastScheduled sets the LastScheduled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastScheduled field is set to the value of the last call.
func (b *OrderArtifactWorkflowStatusApplyConfiguration) WithLastScheduled(value v1.Time) *OrderArtifactWorkflowStatusApplyConfiguration {
	b.WorkflowStatusApplyConfiguration.LastScheduled = &value
	return b
}

// WithSucceeded sets the Succeeded field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Succeeded field is set to the value of the last call.
func (b *OrderArtifactWorkflowStatusApplyConfiguration) WithSucceeded(value int64) *OrderArtifactWorkflowStatusApplyConfiguration {
	b.WorkflowStatusApplyConfiguration.Succeeded = &value
	return b
}

// WithFailed sets the Failed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Failed field is set to the value of the last call.
func (b *OrderArtifactWorkflowStatusApplyConfiguration) WithFailed(value int64) *OrderArtifactWorkflowStatusApplyConfiguration {
	b.WorkflowStatusApplyConfiguration.Failed = &value
	return b
}

// WithArtifactIndex sets the ArtifactIndex field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ArtifactIndex field is set to the value of the last call.
func (b *OrderArtifactWorkflowStatusApplyConfiguration) WithArtifactIndex(value int) *OrderArtifactWorkflowStatusApplyConfiguration {
	b.ArtifactIndex = &value
	return b
}

// WithTTLSecondsAfterCompletion sets the TTLSecondsAfterCompletion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TTLSecondsAfterCompletion field is set to the value of the last call.
func (b *OrderArtifactWorkflowStatusApplyConfiguration) WithTTLSecondsAfterCompletion(value int64) *OrderArtifactWorkflowStatusApplyConfiguration {
	b.TTLSecondsAfterCompletion = &value
	return b
}
