// Copyright 2025 BWI GmbH and Artefact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// OrderSpecApplyConfiguration represents a declarative configuration of the OrderSpec type for use
// with apply.
type OrderSpecApplyConfiguration struct {
	Defaults  *OrderDefaultsApplyConfiguration  `json:"defaults,omitempty"`
	Artifacts []OrderArtifactApplyConfiguration `json:"artifacts,omitempty"`
}

// OrderSpecApplyConfiguration constructs a declarative configuration of the OrderSpec type for use with
// apply.
func OrderSpec() *OrderSpecApplyConfiguration {
	return &OrderSpecApplyConfiguration{}
}

// WithDefaults sets the Defaults field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Defaults field is set to the value of the last call.
func (b *OrderSpecApplyConfiguration) WithDefaults(value *OrderDefaultsApplyConfiguration) *OrderSpecApplyConfiguration {
	b.Defaults = value
	return b
}

// WithArtifacts adds the given value to the Artifacts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Artifacts field.
func (b *OrderSpecApplyConfiguration) WithArtifacts(values ...*OrderArtifactApplyConfiguration) *OrderSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithArtifacts")
		}
		b.Artifacts = append(b.Artifacts, *values[i])
	}
	return b
}
