// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// OrderStatusApplyConfiguration represents a declarative configuration of the OrderStatus type for use
// with apply.
type OrderStatusApplyConfiguration struct {
	ArtifactWorkflows map[string]v1.LocalObjectReference `json:"fragments,omitempty"`
}

// OrderStatusApplyConfiguration constructs a declarative configuration of the OrderStatus type for use with
// apply.
func OrderStatus() *OrderStatusApplyConfiguration {
	return &OrderStatusApplyConfiguration{}
}

// WithArtifactWorkflows puts the entries into the ArtifactWorkflows field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ArtifactWorkflows field,
// overwriting an existing map entries in ArtifactWorkflows field with the same key.
func (b *OrderStatusApplyConfiguration) WithArtifactWorkflows(entries map[string]v1.LocalObjectReference) *OrderStatusApplyConfiguration {
	if b.ArtifactWorkflows == nil && len(entries) > 0 {
		b.ArtifactWorkflows = make(map[string]v1.LocalObjectReference, len(entries))
	}
	for k, v := range entries {
		b.ArtifactWorkflows[k] = v
	}
	return b
}
