// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// OrderSpecApplyConfiguration represents a declarative configuration of the OrderSpec type for use
// with apply.
//
// OrderSpec defines the desired state of Order
type OrderSpecApplyConfiguration struct {
	// Defaults sets up defaults for all artifacts.
	Defaults *OrderDefaultsApplyConfiguration `json:"defaults,omitempty"`
	// Artifacts lists all artifacts, that will be processed by this Order.
	Artifacts []OrderArtifactApplyConfiguration `json:"artifacts,omitempty"`
	// TTL specifies how long the Order is retained after its creation. Once the
	// duration has elapsed since the Order's creationTimestamp, the Order is
	// automatically deleted (garbage collected) together with the artifact
	// workflows it created. The TTL is measured from creation regardless of
	// workflow progress: if it elapses while an artifact workflow is still
	// pending or running, that workflow is deleted mid-execution, interrupting
	// the in-flight transfer. If unset or zero, the Order is retained
	// indefinitely.
	TTL *v1.Duration `json:"ttl,omitempty"`
}

// OrderSpecApplyConfiguration constructs a declarative configuration of the OrderSpec type for use with
// apply.
func OrderSpec() *OrderSpecApplyConfiguration {
	return &OrderSpecApplyConfiguration{}
}

// WithDefaults sets the Defaults field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Defaults field is set to the value of the last call.
func (b *OrderSpecApplyConfiguration) WithDefaults(value *OrderDefaultsApplyConfiguration) *OrderSpecApplyConfiguration {
	b.Defaults = value
	return b
}

// WithArtifacts adds the given value to the Artifacts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Artifacts field.
func (b *OrderSpecApplyConfiguration) WithArtifacts(values ...*OrderArtifactApplyConfiguration) *OrderSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithArtifacts")
		}
		b.Artifacts = append(b.Artifacts, *values[i])
	}
	return b
}

// WithTTL sets the TTL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TTL field is set to the value of the last call.
func (b *OrderSpecApplyConfiguration) WithTTL(value v1.Duration) *OrderSpecApplyConfiguration {
	b.TTL = &value
	return b
}
