// Copyright 2025 BWI GmbH and Artefact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// OrderDefaultsApplyConfiguration represents a declarative configuration of the OrderDefaults type for use
// with apply.
type OrderDefaultsApplyConfiguration struct {
	SrcRef *v1.LocalObjectReference `json:"srcRef,omitempty"`
	DstRef *v1.LocalObjectReference `json:"dstRef,omitempty"`
}

// OrderDefaultsApplyConfiguration constructs a declarative configuration of the OrderDefaults type for use with
// apply.
func OrderDefaults() *OrderDefaultsApplyConfiguration {
	return &OrderDefaultsApplyConfiguration{}
}

// WithSrcRef sets the SrcRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SrcRef field is set to the value of the last call.
func (b *OrderDefaultsApplyConfiguration) WithSrcRef(value v1.LocalObjectReference) *OrderDefaultsApplyConfiguration {
	b.SrcRef = &value
	return b
}

// WithDstRef sets the DstRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DstRef field is set to the value of the last call.
func (b *OrderDefaultsApplyConfiguration) WithDstRef(value v1.LocalObjectReference) *OrderDefaultsApplyConfiguration {
	b.DstRef = &value
	return b
}
