// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	arcv1alpha1 "go.opendefense.cloud/arc/api/arc/v1alpha1"
)

// OrderArtifactWorkflowStatusApplyConfiguration represents a declarative configuration of the OrderArtifactWorkflowStatus type for use
// with apply.
type OrderArtifactWorkflowStatusApplyConfiguration struct {
	ArtifactIndex *int                       `json:"artifactIndex,omitempty"`
	Phase         *arcv1alpha1.WorkflowPhase `json:"phase,omitempty"`
	Message       *string                    `json:"message,omitempty"`
}

// OrderArtifactWorkflowStatusApplyConfiguration constructs a declarative configuration of the OrderArtifactWorkflowStatus type for use with
// apply.
func OrderArtifactWorkflowStatus() *OrderArtifactWorkflowStatusApplyConfiguration {
	return &OrderArtifactWorkflowStatusApplyConfiguration{}
}

// WithArtifactIndex sets the ArtifactIndex field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ArtifactIndex field is set to the value of the last call.
func (b *OrderArtifactWorkflowStatusApplyConfiguration) WithArtifactIndex(value int) *OrderArtifactWorkflowStatusApplyConfiguration {
	b.ArtifactIndex = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *OrderArtifactWorkflowStatusApplyConfiguration) WithPhase(value arcv1alpha1.WorkflowPhase) *OrderArtifactWorkflowStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *OrderArtifactWorkflowStatusApplyConfiguration) WithMessage(value string) *OrderArtifactWorkflowStatusApplyConfiguration {
	b.Message = &value
	return b
}
