// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	arcv1alpha1 "go.opendefense.cloud/arc/api/arc/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// WorkflowStatusApplyConfiguration represents a declarative configuration of the WorkflowStatus type for use
// with apply.
type WorkflowStatusApplyConfiguration struct {
	Phase          *arcv1alpha1.WorkflowPhase `json:"phase,omitempty"`
	Message        *string                    `json:"message,omitempty"`
	CompletionTime *v1.Time                   `json:"completionTime,omitempty"`
	LastScheduled  *v1.Time                   `json:"lastScheduled,omitempty"`
	Succeeded      *int64                     `json:"succeeded,omitempty"`
	Failed         *int64                     `json:"failed,omitempty"`
}

// WorkflowStatusApplyConfiguration constructs a declarative configuration of the WorkflowStatus type for use with
// apply.
func WorkflowStatus() *WorkflowStatusApplyConfiguration {
	return &WorkflowStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *WorkflowStatusApplyConfiguration) WithPhase(value arcv1alpha1.WorkflowPhase) *WorkflowStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *WorkflowStatusApplyConfiguration) WithMessage(value string) *WorkflowStatusApplyConfiguration {
	b.Message = &value
	return b
}

// WithCompletionTime sets the CompletionTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompletionTime field is set to the value of the last call.
func (b *WorkflowStatusApplyConfiguration) WithCompletionTime(value v1.Time) *WorkflowStatusApplyConfiguration {
	b.CompletionTime = &value
	return b
}

// WithLastScheduled sets the LastScheduled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastScheduled field is set to the value of the last call.
func (b *WorkflowStatusApplyConfiguration) WithLastScheduled(value v1.Time) *WorkflowStatusApplyConfiguration {
	b.LastScheduled = &value
	return b
}

// WithSucceeded sets the Succeeded field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Succeeded field is set to the value of the last call.
func (b *WorkflowStatusApplyConfiguration) WithSucceeded(value int64) *WorkflowStatusApplyConfiguration {
	b.Succeeded = &value
	return b
}

// WithFailed sets the Failed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Failed field is set to the value of the last call.
func (b *WorkflowStatusApplyConfiguration) WithFailed(value int64) *WorkflowStatusApplyConfiguration {
	b.Failed = &value
	return b
}
