// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	arcv1alpha1 "go.opendefense.cloud/arc/api/arc/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ArtifactTypeLister helps list ArtifactTypes.
// All objects returned here must be treated as read-only.
type ArtifactTypeLister interface {
	// List lists all ArtifactTypes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*arcv1alpha1.ArtifactType, err error)
	// ArtifactTypes returns an object that can list and get ArtifactTypes.
	ArtifactTypes(namespace string) ArtifactTypeNamespaceLister
	ArtifactTypeListerExpansion
}

// artifactTypeDefinitionLister implements the ArtifactTypeLister interface.
type artifactTypeDefinitionLister struct {
	listers.ResourceIndexer[*arcv1alpha1.ArtifactType]
}

// NewArtifactTypeLister returns a new ArtifactTypeLister.
func NewArtifactTypeLister(indexer cache.Indexer) ArtifactTypeLister {
	return &artifactTypeDefinitionLister{listers.New[*arcv1alpha1.ArtifactType](indexer, arcv1alpha1.Resource("artifacttypedefinition"))}
}

// ArtifactTypes returns an object that can list and get ArtifactTypes.
func (s *artifactTypeDefinitionLister) ArtifactTypes(namespace string) ArtifactTypeNamespaceLister {
	return artifactTypeDefinitionNamespaceLister{listers.NewNamespaced[*arcv1alpha1.ArtifactType](s.ResourceIndexer, namespace)}
}

// ArtifactTypeNamespaceLister helps list and get ArtifactTypes.
// All objects returned here must be treated as read-only.
type ArtifactTypeNamespaceLister interface {
	// List lists all ArtifactTypes in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*arcv1alpha1.ArtifactType, err error)
	// Get retrieves the ArtifactType from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*arcv1alpha1.ArtifactType, error)
	ArtifactTypeNamespaceListerExpansion
}

// artifactTypeDefinitionNamespaceLister implements the ArtifactTypeNamespaceLister
// interface.
type artifactTypeDefinitionNamespaceLister struct {
	listers.ResourceIndexer[*arcv1alpha1.ArtifactType]
}
