// Copyright 2025 BWI GmbH and Artefact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	arcv1alpha1 "gitlab.opencode.de/bwi/ace/artifact-conduit/api/arc/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ArtifactTypeDefinitionLister helps list ArtifactTypeDefinitions.
// All objects returned here must be treated as read-only.
type ArtifactTypeDefinitionLister interface {
	// List lists all ArtifactTypeDefinitions in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*arcv1alpha1.ArtifactTypeDefinition, err error)
	// ArtifactTypeDefinitions returns an object that can list and get ArtifactTypeDefinitions.
	ArtifactTypeDefinitions(namespace string) ArtifactTypeDefinitionNamespaceLister
	ArtifactTypeDefinitionListerExpansion
}

// artifactTypeDefinitionLister implements the ArtifactTypeDefinitionLister interface.
type artifactTypeDefinitionLister struct {
	listers.ResourceIndexer[*arcv1alpha1.ArtifactTypeDefinition]
}

// NewArtifactTypeDefinitionLister returns a new ArtifactTypeDefinitionLister.
func NewArtifactTypeDefinitionLister(indexer cache.Indexer) ArtifactTypeDefinitionLister {
	return &artifactTypeDefinitionLister{listers.New[*arcv1alpha1.ArtifactTypeDefinition](indexer, arcv1alpha1.Resource("artifacttypedefinition"))}
}

// ArtifactTypeDefinitions returns an object that can list and get ArtifactTypeDefinitions.
func (s *artifactTypeDefinitionLister) ArtifactTypeDefinitions(namespace string) ArtifactTypeDefinitionNamespaceLister {
	return artifactTypeDefinitionNamespaceLister{listers.NewNamespaced[*arcv1alpha1.ArtifactTypeDefinition](s.ResourceIndexer, namespace)}
}

// ArtifactTypeDefinitionNamespaceLister helps list and get ArtifactTypeDefinitions.
// All objects returned here must be treated as read-only.
type ArtifactTypeDefinitionNamespaceLister interface {
	// List lists all ArtifactTypeDefinitions in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*arcv1alpha1.ArtifactTypeDefinition, err error)
	// Get retrieves the ArtifactTypeDefinition from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*arcv1alpha1.ArtifactTypeDefinition, error)
	ArtifactTypeDefinitionNamespaceListerExpansion
}

// artifactTypeDefinitionNamespaceLister implements the ArtifactTypeDefinitionNamespaceLister
// interface.
type artifactTypeDefinitionNamespaceLister struct {
	listers.ResourceIndexer[*arcv1alpha1.ArtifactTypeDefinition]
}
