// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	arcv1alpha1 "go.opendefense.cloud/arc/api/arc/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ArtifactTypeLister helps list ArtifactTypes.
// All objects returned here must be treated as read-only.
type ArtifactTypeLister interface {
	// List lists all ArtifactTypes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*arcv1alpha1.ArtifactType, err error)
	// Get retrieves the ArtifactType from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*arcv1alpha1.ArtifactType, error)
	ArtifactTypeListerExpansion
}

// artifactTypeLister implements the ArtifactTypeLister interface.
type artifactTypeLister struct {
	listers.ResourceIndexer[*arcv1alpha1.ArtifactType]
}

// NewArtifactTypeLister returns a new ArtifactTypeLister.
func NewArtifactTypeLister(indexer cache.Indexer) ArtifactTypeLister {
	return &artifactTypeLister{listers.New[*arcv1alpha1.ArtifactType](indexer, arcv1alpha1.Resource("artifacttype"))}
}
