// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	arcv1alpha1 "go.opendefense.cloud/arc/api/arc/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterArtifactTypeLister helps list ClusterArtifactTypes.
// All objects returned here must be treated as read-only.
type ClusterArtifactTypeLister interface {
	// List lists all ClusterArtifactTypes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*arcv1alpha1.ClusterArtifactType, err error)
	// Get retrieves the ClusterArtifactType from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*arcv1alpha1.ClusterArtifactType, error)
	ClusterArtifactTypeListerExpansion
}

// clusterArtifactTypeLister implements the ClusterArtifactTypeLister interface.
type clusterArtifactTypeLister struct {
	listers.ResourceIndexer[*arcv1alpha1.ClusterArtifactType]
}

// NewClusterArtifactTypeLister returns a new ClusterArtifactTypeLister.
func NewClusterArtifactTypeLister(indexer cache.Indexer) ClusterArtifactTypeLister {
	return &clusterArtifactTypeLister{listers.New[*arcv1alpha1.ClusterArtifactType](indexer, arcv1alpha1.Resource("clusterartifacttype"))}
}
