// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ArtifactTypeListerExpansion allows custom methods to be added to
// ArtifactTypeLister.
type ArtifactTypeListerExpansion interface{}

// ArtifactTypeNamespaceListerExpansion allows custom methods to be added to
// ArtifactTypeNamespaceLister.
type ArtifactTypeNamespaceListerExpansion interface{}

// ArtifactWorkflowListerExpansion allows custom methods to be added to
// ArtifactWorkflowLister.
type ArtifactWorkflowListerExpansion interface{}

// ArtifactWorkflowNamespaceListerExpansion allows custom methods to be added to
// ArtifactWorkflowNamespaceLister.
type ArtifactWorkflowNamespaceListerExpansion interface{}

// EndpointListerExpansion allows custom methods to be added to
// EndpointLister.
type EndpointListerExpansion interface{}

// EndpointNamespaceListerExpansion allows custom methods to be added to
// EndpointNamespaceLister.
type EndpointNamespaceListerExpansion interface{}

// OrderListerExpansion allows custom methods to be added to
// OrderLister.
type OrderListerExpansion interface{}

// OrderNamespaceListerExpansion allows custom methods to be added to
// OrderNamespaceLister.
type OrderNamespaceListerExpansion interface{}
