// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ArtifactTypeDefinitionListerExpansion allows custom methods to be added to
// ArtifactTypeDefinitionLister.
type ArtifactTypeDefinitionListerExpansion interface{}

// ArtifactTypeDefinitionNamespaceListerExpansion allows custom methods to be added to
// ArtifactTypeDefinitionNamespaceLister.
type ArtifactTypeDefinitionNamespaceListerExpansion interface{}

// EndpointListerExpansion allows custom methods to be added to
// EndpointLister.
type EndpointListerExpansion interface{}

// EndpointNamespaceListerExpansion allows custom methods to be added to
// EndpointNamespaceLister.
type EndpointNamespaceListerExpansion interface{}

// FragmentListerExpansion allows custom methods to be added to
// FragmentLister.
type FragmentListerExpansion interface{}

// FragmentNamespaceListerExpansion allows custom methods to be added to
// FragmentNamespaceLister.
type FragmentNamespaceListerExpansion interface{}

// OrderListerExpansion allows custom methods to be added to
// OrderLister.
type OrderListerExpansion interface{}

// OrderNamespaceListerExpansion allows custom methods to be added to
// OrderNamespaceLister.
type OrderNamespaceListerExpansion interface{}
