// Copyright 2025 BWI GmbH and Artefact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	arcv1alpha1 "go.opendefense.cloud/arc/api/arc/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// FragmentLister helps list Fragments.
// All objects returned here must be treated as read-only.
type FragmentLister interface {
	// List lists all Fragments in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*arcv1alpha1.Fragment, err error)
	// Fragments returns an object that can list and get Fragments.
	Fragments(namespace string) FragmentNamespaceLister
	FragmentListerExpansion
}

// fragmentLister implements the FragmentLister interface.
type fragmentLister struct {
	listers.ResourceIndexer[*arcv1alpha1.Fragment]
}

// NewFragmentLister returns a new FragmentLister.
func NewFragmentLister(indexer cache.Indexer) FragmentLister {
	return &fragmentLister{listers.New[*arcv1alpha1.Fragment](indexer, arcv1alpha1.Resource("fragment"))}
}

// Fragments returns an object that can list and get Fragments.
func (s *fragmentLister) Fragments(namespace string) FragmentNamespaceLister {
	return fragmentNamespaceLister{listers.NewNamespaced[*arcv1alpha1.Fragment](s.ResourceIndexer, namespace)}
}

// FragmentNamespaceLister helps list and get Fragments.
// All objects returned here must be treated as read-only.
type FragmentNamespaceLister interface {
	// List lists all Fragments in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*arcv1alpha1.Fragment, err error)
	// Get retrieves the Fragment from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*arcv1alpha1.Fragment, error)
	FragmentNamespaceListerExpansion
}

// fragmentNamespaceLister implements the FragmentNamespaceLister
// interface.
type fragmentNamespaceLister struct {
	listers.ResourceIndexer[*arcv1alpha1.Fragment]
}
