apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: oci-image-pipeline
spec:
  retryStrategy:
    retryPolicy: OnError
    limit: 1

  serviceAccountName: arc-workflow
  securityContext:
    fsGroup: 65532
    runAsUser: 65532

  # Define the PVC template for inter-step data sharing
  volumeClaimTemplates:
    - metadata:
        name: work-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi

  # Mount certificate bundle
  volumes:
    - name: ca-certificates
      configMap:
        name: "root-bundle"
        defaultMode: 0644
        optional: false
        items:
          - key: trust-bundle.pem
            path: trust-bundle.pem

  # --- Input Parameters ---
  arguments:
    parameters:
      - name: srcType
      - name: srcRemoteURL
      - name: srcSecret
      - name: dstType
      - name: dstRemoteURL
      - name: dstSecret
      - name: specRepository # The source image repository (e.g. library/alpine)
      - name: specTag # The source image tag or semver pattern, e.g. 3.18 or >3.18.0 < 3.19.0
      - name: specOverride # Defines how destination repository:tag is overriden, supports go templates
        value: ""
      - name: scanSeverity # Additional parameter coming from ArtifactType

  entrypoint: oci-pipeline

  templates:
    # --- Main Pipeline Entrypoint ---
    - name: oci-pipeline
      steps:
        - - name: authenticate-registries
            template: authenticate-registries

        - - name: check-src-availability
            template: check-src-availability

        # If source is unavailable we assume it is a constraint, so let's find the latest semver
        - - name: retrieve-tags
            template: retrieve-tags
            when: "{{ steps.check-src-availability.outputs.result }} == 'unavailable'"

        - - name: filter-tags
            template: filter-tags
            when: "{{ steps.check-src-availability.outputs.result }} == 'unavailable'"

        - - name: compute-images
            template: compute-images

        - - name: check-dst-availability
            template: check-dst-availability

        - - name: pull-image
            template: pull-image
            when: "{{ steps.check-dst-availability.outputs.result }} == 'unavailable'"

        - - name: scan-image
            template: scan-image
            when: "{{ steps.check-dst-availability.outputs.result }} == 'unavailable'"

        - - name: push-image
            template: push-image
            when: "{{ steps.check-dst-availability.outputs.result }} == 'unavailable'"

        - - name: attest-scan
            template: attest-scan-results
            when: "{{ steps.check-dst-availability.outputs.result }} == 'unavailable'"
            arguments:
              parameters:
              - name: dst
                value: "{{steps.compute-images.outputs.parameters.dst}}"

        - - name: sign-image
            template: sign-image
            when: "{{ steps.check-dst-availability.outputs.result }} == 'unavailable'"
            arguments:
              parameters:
              - name: dst
                value: "{{steps.compute-images.outputs.parameters.dst}}"

    # --- Authenticate (Skopeo) ---
    - name: authenticate-registries

      script:
        image: quay.io/skopeo/stable:v1.22.2
        command: [sh, -c]

        # Mount the volumes
        volumeMounts: &volumeMounts
          - name: src-secret-vol
            readOnly: true
            mountPath: /secrets/src
          - name: dst-secret-vol
            readOnly: true
            mountPath: /secrets/dst
          - name: work-volume
            mountPath: /data
          - mountPath: /etc/ssl/certs/
            name: ca-certificates
            readOnly: true

        env: &env
          - name: DOCKER_CONFIG
            value: /data/.docker
          - name: REGISTRY_AUTH_FILE
            value: /data/.docker/config.json
          # Argo Workflows is considering disallowing accessing parameters in the body of the script,
          # so let's explicitly pass them in as variables:
          - name: SRC_TYPE
            value: "{{workflow.parameters.srcType}}"
          - name: SRC_REMOTE_URL
            value: "{{workflow.parameters.srcRemoteURL}}"
          - name: SRC_SECRET
            value: "{{workflow.parameters.srcSecret}}"
          - name: DST_TYPE
            value: "{{workflow.parameters.dstType}}"
          - name: DST_REMOTE_URL
            value: "{{workflow.parameters.dstRemoteURL}}"
          - name: DST_SECRET
            value: "{{workflow.parameters.dstSecret}}"
          - name: SPEC_REPOSITORY
            value: "{{workflow.parameters.specRepository}}"
          - name: SPEC_TAG
            value: "{{workflow.parameters.specTag}}"
          - name: SPEC_OVERRIDE
            value: "{{workflow.parameters.specOverride}}"
          - name: SCAN_SEVERITY
            value: "{{workflow.parameters.scanSeverity}}"

        source: |
          set -euo pipefail

          # Conditionally login to source registry
          if [ "{{workflow.parameters.srcSecret}}" = "true" ]; then
              echo "Authenticating to source registry {{workflow.parameters.srcRemoteURL}}..."
              cat /secrets/src/password | skopeo login -u "$(cat /secrets/src/username)" --password-stdin {{workflow.parameters.srcRemoteURL}} --compat-auth-file "${DOCKER_CONFIG}/config.json"
          fi

          # Conditionally login to destination registry
          if [ "{{workflow.parameters.dstSecret}}" = "true" ]; then
              echo "Authenticating to destination registry {{workflow.parameters.dstRemoteURL}}..."
              cat /secrets/dst/password | skopeo login -u "$(cat /secrets/dst/username)" --password-stdin {{workflow.parameters.dstRemoteURL}} --compat-auth-file "${DOCKER_CONFIG}/config.json"
          fi

    # --- Check Source Availability (Skopeo) ---
    - name: check-src-availability
      retryStrategy:
        limit: "2"
      script:
        image: quay.io/skopeo/stable:v1.22.2
        command: [sh, -c]
        volumeMounts: *volumeMounts
        env: *env

        source: |
          skopeo inspect "docker://$SRC_REMOTE_URL/$SPEC_REPOSITORY:$SPEC_TAG" >/dev/null 2>&1

          EXIT_CODE=$?

          if [ "$EXIT_CODE" -eq 0 ]; then
              echo "$SPEC_TAG" > /data/tag.txt
              echo "available"
          else
              # Image does not exist
              echo "unavailable"
          fi
          exit 0

    # --- Retrieve Tags (Skopeo) ---
    - name: retrieve-tags
      retryStrategy:
        limit: "2"
      script:
        image: quay.io/skopeo/stable:v1.22.2
        command: [sh, -c]
        volumeMounts: *volumeMounts
        env: *env

        source: |
          set -euo pipefail

          skopeo list-tags "docker://$SRC_REMOTE_URL/$SPEC_REPOSITORY" > /data/list-tags.json

    # --- Filter Tags (semver) ---
    - name: filter-tags
      retryStrategy:
        limit: "2"
      script:
        image: ghcr.io/trevex/semver:v0.1.1
        command: [bash, -c]
        volumeMounts: *volumeMounts
        env: *env

        source: |
          set -euo pipefail

          cat /data/list-tags.json | jq -r '.Tags[]' | semver filter "$SPEC_TAG" -i | semver latest > /data/tag.txt

    # --- Compute Images
    - name: compute-images
      retryStrategy:
        limit: "2"
      outputs:
        parameters:
        - name: src
          valueFrom:
            path: /tmp/src.txt
        - name: dst
          valueFrom:
            path: /tmp/dst.txt
      script:
        image: hairyhenderson/gomplate:v5.2.0-alpine
        command: [sh, -c]
        volumeMounts: *volumeMounts
        env: *env
        source: |
          set -euo pipefail

          # escaping go templates sucks, so let's just not...
          cat > /tmp/images.tpl <<EOF
          <<- \$srcRemoteURL := "$SRC_REMOTE_URL" >>
          <<- \$dstRemoteURL := "$DST_REMOTE_URL" >>
          <<- \$repository := "$SPEC_REPOSITORY" >>
          <<- \$override := "$SPEC_OVERRIDE" >>
          <<- \$tag := "$(cat /data/tag.txt)" >>
          <<- \$values := dict "tag" \$tag "repository" \$repository >>
          << \$srcRemoteURL >>/<< \$repository >>:<< \$tag >>
          <<- if \$override >>
          <<- \$repoTag := tmpl.Inline \$override \$values >>
          << \$dstRemoteURL >>/<< \$repoTag >>
          <<- else >>
          << \$dstRemoteURL >>/<< \$repository >>:<< \$tag >>
          <<- end >>
          EOF

          sed -i 's/<</{{/g' /tmp/images.tpl
          sed -i 's/>>/}}/g' /tmp/images.tpl
          cat /tmp/images.tpl

          cat /tmp/images.tpl | gomplate --out - > /data/gomplate.txt

          sed -i '/^[[:space:]]*$/d' /data/gomplate.txt
          cat /data/gomplate.txt

          head -1 /data/gomplate.txt > /data/src.txt
          cp /data/src.txt /tmp/src.txt
          head -2 /data/gomplate.txt | tail -1 > /data/dst.txt
          cp /data/dst.txt /tmp/dst.txt

    # --- Check Destination Availability (Skopeo) ---
    - name: check-dst-availability
      retryStrategy:
        limit: "2"

      script:
        image: quay.io/skopeo/stable:v1.22.2
        command: [sh, -c]
        volumeMounts: *volumeMounts
        env: *env

        source: |
          skopeo inspect "docker://$(cat /data/dst.txt)" >/dev/null 2>&1

          EXIT_CODE=$?

          if [ "$EXIT_CODE" -eq 0 ]; then
              echo "available"
          else
              # Image does not exist
              echo "unavailable"
          fi
          exit 0

    # --- Pull Image (Skopeo) ---
    - name: pull-image
      retryStrategy:
        limit: "2"

      script:
        image: quay.io/skopeo/stable:v1.22.2
        command: [sh, -c]
        volumeMounts: *volumeMounts
        env: *env

        source: |
          set -euo pipefail

          echo "Pulling image from $(cat /data/src.txt)"
          mkdir -p /data/image-storage

          skopeo copy --preserve-digests --multi-arch all "docker://$(cat /data/src.txt)" "oci:/data/image-storage/scanned-image"

    - name: scan-image
      script:
        image: aquasec/trivy:0.73.0
        command: [sh, -c]
        volumeMounts: *volumeMounts

        source: |
          echo "Scanning image for severities: $SCAN_SEVERITY"

          # Trivy scan in a directory mode
          trivy image \
            --cache-dir /data/.trivy/cache \
            --exit-code 1 \
            --severity "$SCAN_SEVERITY" \
            --format json \
            --output /data/scan-results.json \
            --input /data/image-storage/scanned-image

          if [ $? -eq 0 ]; then
              echo "✅ Scan successful and no vulnerabilities found above severity: $SCAN_SEVERITY"
          else
              echo "❌ Scan failed!"
              cat /data/scan-results.json
              exit 1
          fi
        env: *env

    # --- Push Image (Skopeo) ---
    - name: push-image
      retryStrategy:
        limit: "2"

      script:
        image: quay.io/skopeo/stable:v1.22.2
        command: [sh, -c]

        # Mount the secret volume to a temporary directory
        volumeMounts: *volumeMounts

        source: |
          set -euo pipefail

          echo "Pushing image to $(cat /data/dst.txt)"
          skopeo copy --dest-precompute-digests --preserve-digests "oci:/data/image-storage/scanned-image" "docker://$(cat /data/dst.txt)"
        env: *env

    # --- Attest Scan Results (Cosign) ---
    - name: attest-scan-results
      inputs:
        parameters:
        - name: dst
      container:
        image: cgr.dev/chainguard/cosign:latest
        command: [cosign, attest]
        args:
          [
            "--allow-http-registry=true",
            "--key",
            "k8s://{{workflow.namespace}}/cosign-key",
            "--predicate",
            "/data/scan-results.json",
            "--type",
            "vuln",
            "{{inputs.parameters.dst}}",
          ]
        env: *env
        volumeMounts: *volumeMounts

    # --- Sign the image (Cosign) ---
    - name: sign-image
      inputs:
        parameters:
        - name: dst
      container:
        image: cgr.dev/chainguard/cosign:latest
        command: [cosign, sign]
        args:
          [
            "--yes",
            "--allow-http-registry=true",
            "--key",
            "k8s://{{workflow.namespace}}/cosign-key",
            "{{inputs.parameters.dst}}",
          ]
        env: *env
        volumeMounts: *volumeMounts
