apiVersion: v1
data:
  cosign.key: LS0tLS1CRUdJTiBFTkNSWVBURUQgU0lHU1RPUkUgUFJJVkFURSBLRVktLS0tLQpleUpyWkdZaU9uc2libUZ0WlNJNkluTmpjbmx3ZENJc0luQmhjbUZ0Y3lJNmV5Sk9Jam8yTlRVek5pd2ljaUk2Ck9Dd2ljQ0k2TVgwc0luTmhiSFFpT2lJMVZ6RTJXbVJuUmxjMlVqRnVlRk5rZVRKelJqZG9VVEZUTmtWWFVGZFoKZVRCR1YwTjZOWEE1ZVRRd1BTSjlMQ0pqYVhCb1pYSWlPbnNpYm1GdFpTSTZJbTVoWTJ3dmMyVmpjbVYwWW05NApJaXdpYm05dVkyVWlPaUpVYm5adU5rcHRWa2hYU1drdlozTkZTV2gxYVVOdFowbzJUMk5GUVc1dWJpSjlMQ0pqCmFYQm9aWEowWlhoMElqb2llV05oVnpSU1EwcHVNbWhCTW5nMWRFUjBSa2hHVFdSclJuaDBUbnBXUldoM01GQXgKT0hsNlFVZE1ibGhwVWl0Q1ZrVkpVMGhRYW1aRVNWVmtlRzFFVDJwWlRUWjZWRzh2TUZrMlVUWnBTblpLVFV0UwpMMWhLUjNCcU0yNVNObVJ2WnpSTVN6aElkMFZCWVZZeVZqVk5VV0pwYms0dldFMTZUV0pQVTBkTU1tNVZiVGN6CkwySXlUR1JZVkhrMk1rYzJXQ3M0WTNBMVNUSnNUa2MyWXpFMlRVeFdOWFF6Ylc1S05VdHVlRTExZUcxc1FraHIKVFVkc01FTmpURGR3YmxnMWNYUXpVVmx4UjBweFkwaElhVkU5UFNKOQotLS0tLUVORCBFTkNSWVBURUQgU0lHU1RPUkUgUFJJVkFURSBLRVktLS0tLQo=
  cosign.password: cGFzc3dvcmQ=
  cosign.pub: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFUWd3OUdWYzV4RWtEYnEvbjJtcVdMMmxUSHprdAp6OHBKYytjYWJEYVorRXBPZWxPdTRnTHNlWG85MkVtYk4wSmlLbVZ5bTRhY0ZoNkJQeEZMTENZSmR3PT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
immutable: true
kind: Secret
metadata:
  name: cosign-key
type: Opaque
