apiVersion: arc.bwi.de/v1alpha1
kind: Endpoint
metadata:
  name: gcrio
spec:
  type: oci # Endpoint Type!
  remoteURL: gcr.io
  usage: PullOnly
---
apiVersion: arc.bwi.de/v1alpha1
kind: Endpoint
metadata:
  name: internal
spec:
  type: oci # Endpoint Type!
  remoteURL: dst.zot # port optional, but endpoint can only be used with plain http with helm, if port is specified
  secretRef:
    name: dst-reg-secret
  usage: PushOnly
---
apiVersion: arc.bwi.de/v1alpha1
kind: Order
metadata:
  name: example-oci-order
spec:
  defaults:
    srcRef:
      name: gcrio
    dstRef:
      name: internal
  artifacts:
    - type: oci # Artifact Type!
      spec:
        image: distroless/static:nonroot
        override: myteam/alpine:3.18-dev # default alpine:3.18
