apiVersion: arc.opendefense.cloud/v1alpha1
kind: Endpoint
metadata:
  name: gcrio
spec:
  type: oci # Endpoint Type!
  remoteURL: gcr.io
  usage: PullOnly
---
apiVersion: arc.opendefense.cloud/v1alpha1
kind: Endpoint
metadata:
  name: internal
spec:
  type: oci # Endpoint Type!
  remoteURL: dst.zot
  secretRef:
    name: dst-reg-secret
  usage: PushOnly
---
apiVersion: arc.opendefense.cloud/v1alpha1
kind: Order
metadata:
  name: example-oci-order
spec:
  defaults:
    srcRef:
      name: gcrio
    dstRef:
      name: internal
  artifacts:
    - type: oci # Artifact Type!
      spec:
        repository: distroless/static
        tag: nonroot
        override: "myteam/static:{{.tag}}-dev" # supports go templates
