---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: arc-syncagent
---
apiVersion: v1
kind: Secret
metadata:
  name: arc-syncagent-token
  annotations:
    kubernetes.io/service-account.name: arc-syncagent
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: arc-syncagent
rules:
- nonResourceURLs: ["/"]
  verbs:
  - access
- apiGroups: ["core.kcp.io"]
  resources: ["logicalclusters"]
  resourceNames: ["cluster"]
  verbs:
  - get
- apiGroups: ["apis.kcp.io"]
  resources: ["apiexports", "apiexportendpointslices", "apiresourceschemas"]
  verbs:
  - get
  - list
  - watch
- apiGroups: ["apis.kcp.io"]
  resources: ["apiexports/content"]
  resourceNames: ["arc.opendefense.cloud"]
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups: [""]
  resources: ["events"]
  verbs:
  - create
  - update
- apiGroups: [""]
  resources: ["secrets"]
  verbs:
  - "get"
  - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: arc-syncagent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: arc-syncagent
subjects:
- kind: ServiceAccount
  name: arc-syncagent
  namespace: default
