apiVersion: apps/v1
kind: Deployment
metadata:
  name: arc-controller-manager
  namespace: arc-system
spec:
  template:
    spec:
      containers:
      - name: manager
        resources:
          limits:
            memory: 128Mi
