// Copyright 2025 BWI GmbH and Artefact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	orderv1alpha1 "gitlab.opencode.de/bwi/ace/artifact-conduit/api/order/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// OrderLister helps list Orders.
// All objects returned here must be treated as read-only.
type OrderLister interface {
	// List lists all Orders in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*orderv1alpha1.Order, err error)
	// Orders returns an object that can list and get Orders.
	Orders(namespace string) OrderNamespaceLister
	OrderListerExpansion
}

// orderLister implements the OrderLister interface.
type orderLister struct {
	listers.ResourceIndexer[*orderv1alpha1.Order]
}

// NewOrderLister returns a new OrderLister.
func NewOrderLister(indexer cache.Indexer) OrderLister {
	return &orderLister{listers.New[*orderv1alpha1.Order](indexer, orderv1alpha1.Resource("order"))}
}

// Orders returns an object that can list and get Orders.
func (s *orderLister) Orders(namespace string) OrderNamespaceLister {
	return orderNamespaceLister{listers.NewNamespaced[*orderv1alpha1.Order](s.ResourceIndexer, namespace)}
}

// OrderNamespaceLister helps list and get Orders.
// All objects returned here must be treated as read-only.
type OrderNamespaceLister interface {
	// List lists all Orders in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*orderv1alpha1.Order, err error)
	// Get retrieves the Order from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*orderv1alpha1.Order, error)
	OrderNamespaceListerExpansion
}

// orderNamespaceLister implements the OrderNamespaceLister
// interface.
type orderNamespaceLister struct {
	listers.ResourceIndexer[*orderv1alpha1.Order]
}
