// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	arcv1alpha1 "go.opendefense.cloud/arc/api/arc/v1alpha1"
	applyconfigurationsarcv1alpha1 "go.opendefense.cloud/arc/client-go/applyconfigurations/arc/v1alpha1"
	scheme "go.opendefense.cloud/arc/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ArtifactWorkflowsGetter has a method to return a ArtifactWorkflowInterface.
// A group's client should implement this interface.
type ArtifactWorkflowsGetter interface {
	ArtifactWorkflows(namespace string) ArtifactWorkflowInterface
}

// ArtifactWorkflowInterface has methods to work with ArtifactWorkflow resources.
type ArtifactWorkflowInterface interface {
	Create(ctx context.Context, artifactWorkflow *arcv1alpha1.ArtifactWorkflow, opts v1.CreateOptions) (*arcv1alpha1.ArtifactWorkflow, error)
	Update(ctx context.Context, artifactWorkflow *arcv1alpha1.ArtifactWorkflow, opts v1.UpdateOptions) (*arcv1alpha1.ArtifactWorkflow, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, artifactWorkflow *arcv1alpha1.ArtifactWorkflow, opts v1.UpdateOptions) (*arcv1alpha1.ArtifactWorkflow, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*arcv1alpha1.ArtifactWorkflow, error)
	List(ctx context.Context, opts v1.ListOptions) (*arcv1alpha1.ArtifactWorkflowList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *arcv1alpha1.ArtifactWorkflow, err error)
	Apply(ctx context.Context, artifactWorkflow *applyconfigurationsarcv1alpha1.ArtifactWorkflowApplyConfiguration, opts v1.ApplyOptions) (result *arcv1alpha1.ArtifactWorkflow, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, artifactWorkflow *applyconfigurationsarcv1alpha1.ArtifactWorkflowApplyConfiguration, opts v1.ApplyOptions) (result *arcv1alpha1.ArtifactWorkflow, err error)
	ArtifactWorkflowExpansion
}

// artifactWorkflows implements ArtifactWorkflowInterface
type artifactWorkflows struct {
	*gentype.ClientWithListAndApply[*arcv1alpha1.ArtifactWorkflow, *arcv1alpha1.ArtifactWorkflowList, *applyconfigurationsarcv1alpha1.ArtifactWorkflowApplyConfiguration]
}

// newArtifactWorkflows returns a ArtifactWorkflows
func newArtifactWorkflows(c *ArcV1alpha1Client, namespace string) *artifactWorkflows {
	return &artifactWorkflows{
		gentype.NewClientWithListAndApply[*arcv1alpha1.ArtifactWorkflow, *arcv1alpha1.ArtifactWorkflowList, *applyconfigurationsarcv1alpha1.ArtifactWorkflowApplyConfiguration](
			"artifactworkflows",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *arcv1alpha1.ArtifactWorkflow { return &arcv1alpha1.ArtifactWorkflow{} },
			func() *arcv1alpha1.ArtifactWorkflowList { return &arcv1alpha1.ArtifactWorkflowList{} },
		),
	}
}
