// Copyright 2025 BWI GmbH and Artefact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	arcv1alpha1 "go.opendefense.cloud/arc/api/arc/v1alpha1"
	applyconfigurationsarcv1alpha1 "go.opendefense.cloud/arc/client-go/applyconfigurations/arc/v1alpha1"
	scheme "go.opendefense.cloud/arc/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ArtifactTypeDefinitionsGetter has a method to return a ArtifactTypeDefinitionInterface.
// A group's client should implement this interface.
type ArtifactTypeDefinitionsGetter interface {
	ArtifactTypeDefinitions(namespace string) ArtifactTypeDefinitionInterface
}

// ArtifactTypeDefinitionInterface has methods to work with ArtifactTypeDefinition resources.
type ArtifactTypeDefinitionInterface interface {
	Create(ctx context.Context, artifactTypeDefinition *arcv1alpha1.ArtifactTypeDefinition, opts v1.CreateOptions) (*arcv1alpha1.ArtifactTypeDefinition, error)
	Update(ctx context.Context, artifactTypeDefinition *arcv1alpha1.ArtifactTypeDefinition, opts v1.UpdateOptions) (*arcv1alpha1.ArtifactTypeDefinition, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, artifactTypeDefinition *arcv1alpha1.ArtifactTypeDefinition, opts v1.UpdateOptions) (*arcv1alpha1.ArtifactTypeDefinition, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*arcv1alpha1.ArtifactTypeDefinition, error)
	List(ctx context.Context, opts v1.ListOptions) (*arcv1alpha1.ArtifactTypeDefinitionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *arcv1alpha1.ArtifactTypeDefinition, err error)
	Apply(ctx context.Context, artifactTypeDefinition *applyconfigurationsarcv1alpha1.ArtifactTypeDefinitionApplyConfiguration, opts v1.ApplyOptions) (result *arcv1alpha1.ArtifactTypeDefinition, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, artifactTypeDefinition *applyconfigurationsarcv1alpha1.ArtifactTypeDefinitionApplyConfiguration, opts v1.ApplyOptions) (result *arcv1alpha1.ArtifactTypeDefinition, err error)
	ArtifactTypeDefinitionExpansion
}

// artifactTypeDefinitions implements ArtifactTypeDefinitionInterface
type artifactTypeDefinitions struct {
	*gentype.ClientWithListAndApply[*arcv1alpha1.ArtifactTypeDefinition, *arcv1alpha1.ArtifactTypeDefinitionList, *applyconfigurationsarcv1alpha1.ArtifactTypeDefinitionApplyConfiguration]
}

// newArtifactTypeDefinitions returns a ArtifactTypeDefinitions
func newArtifactTypeDefinitions(c *ArcV1alpha1Client, namespace string) *artifactTypeDefinitions {
	return &artifactTypeDefinitions{
		gentype.NewClientWithListAndApply[*arcv1alpha1.ArtifactTypeDefinition, *arcv1alpha1.ArtifactTypeDefinitionList, *applyconfigurationsarcv1alpha1.ArtifactTypeDefinitionApplyConfiguration](
			"artifacttypedefinitions",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *arcv1alpha1.ArtifactTypeDefinition { return &arcv1alpha1.ArtifactTypeDefinition{} },
			func() *arcv1alpha1.ArtifactTypeDefinitionList { return &arcv1alpha1.ArtifactTypeDefinitionList{} },
		),
	}
}
