// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	arcv1alpha1 "go.opendefense.cloud/arc/api/arc/v1alpha1"
	applyconfigurationsarcv1alpha1 "go.opendefense.cloud/arc/client-go/applyconfigurations/arc/v1alpha1"
	scheme "go.opendefense.cloud/arc/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ArtifactTypesGetter has a method to return a ArtifactTypeInterface.
// A group's client should implement this interface.
type ArtifactTypesGetter interface {
	ArtifactTypes(namespace string) ArtifactTypeInterface
}

// ArtifactTypeInterface has methods to work with ArtifactType resources.
type ArtifactTypeInterface interface {
	Create(ctx context.Context, artifactType *arcv1alpha1.ArtifactType, opts v1.CreateOptions) (*arcv1alpha1.ArtifactType, error)
	Update(ctx context.Context, artifactType *arcv1alpha1.ArtifactType, opts v1.UpdateOptions) (*arcv1alpha1.ArtifactType, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, artifactType *arcv1alpha1.ArtifactType, opts v1.UpdateOptions) (*arcv1alpha1.ArtifactType, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*arcv1alpha1.ArtifactType, error)
	List(ctx context.Context, opts v1.ListOptions) (*arcv1alpha1.ArtifactTypeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *arcv1alpha1.ArtifactType, err error)
	Apply(ctx context.Context, artifactType *applyconfigurationsarcv1alpha1.ArtifactTypeApplyConfiguration, opts v1.ApplyOptions) (result *arcv1alpha1.ArtifactType, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, artifactType *applyconfigurationsarcv1alpha1.ArtifactTypeApplyConfiguration, opts v1.ApplyOptions) (result *arcv1alpha1.ArtifactType, err error)
	ArtifactTypeExpansion
}

// artifactTypes implements ArtifactTypeInterface
type artifactTypes struct {
	*gentype.ClientWithListAndApply[*arcv1alpha1.ArtifactType, *arcv1alpha1.ArtifactTypeList, *applyconfigurationsarcv1alpha1.ArtifactTypeApplyConfiguration]
}

// newArtifactTypes returns a ArtifactTypes
func newArtifactTypes(c *ArcV1alpha1Client, namespace string) *artifactTypes {
	return &artifactTypes{
		gentype.NewClientWithListAndApply[*arcv1alpha1.ArtifactType, *arcv1alpha1.ArtifactTypeList, *applyconfigurationsarcv1alpha1.ArtifactTypeApplyConfiguration](
			"artifacttypes",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *arcv1alpha1.ArtifactType { return &arcv1alpha1.ArtifactType{} },
			func() *arcv1alpha1.ArtifactTypeList { return &arcv1alpha1.ArtifactTypeList{} },
		),
	}
}
