// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	arcv1alpha1 "go.opendefense.cloud/arc/api/arc/v1alpha1"
	applyconfigurationsarcv1alpha1 "go.opendefense.cloud/arc/client-go/applyconfigurations/arc/v1alpha1"
	scheme "go.opendefense.cloud/arc/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterEndpointsGetter has a method to return a ClusterEndpointInterface.
// A group's client should implement this interface.
type ClusterEndpointsGetter interface {
	ClusterEndpoints() ClusterEndpointInterface
}

// ClusterEndpointInterface has methods to work with ClusterEndpoint resources.
type ClusterEndpointInterface interface {
	Create(ctx context.Context, clusterEndpoint *arcv1alpha1.ClusterEndpoint, opts v1.CreateOptions) (*arcv1alpha1.ClusterEndpoint, error)
	Update(ctx context.Context, clusterEndpoint *arcv1alpha1.ClusterEndpoint, opts v1.UpdateOptions) (*arcv1alpha1.ClusterEndpoint, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, clusterEndpoint *arcv1alpha1.ClusterEndpoint, opts v1.UpdateOptions) (*arcv1alpha1.ClusterEndpoint, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*arcv1alpha1.ClusterEndpoint, error)
	List(ctx context.Context, opts v1.ListOptions) (*arcv1alpha1.ClusterEndpointList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *arcv1alpha1.ClusterEndpoint, err error)
	Apply(ctx context.Context, clusterEndpoint *applyconfigurationsarcv1alpha1.ClusterEndpointApplyConfiguration, opts v1.ApplyOptions) (result *arcv1alpha1.ClusterEndpoint, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, clusterEndpoint *applyconfigurationsarcv1alpha1.ClusterEndpointApplyConfiguration, opts v1.ApplyOptions) (result *arcv1alpha1.ClusterEndpoint, err error)
	ClusterEndpointExpansion
}

// clusterEndpoints implements ClusterEndpointInterface
type clusterEndpoints struct {
	*gentype.ClientWithListAndApply[*arcv1alpha1.ClusterEndpoint, *arcv1alpha1.ClusterEndpointList, *applyconfigurationsarcv1alpha1.ClusterEndpointApplyConfiguration]
}

// newClusterEndpoints returns a ClusterEndpoints
func newClusterEndpoints(c *ArcV1alpha1Client) *clusterEndpoints {
	return &clusterEndpoints{
		gentype.NewClientWithListAndApply[*arcv1alpha1.ClusterEndpoint, *arcv1alpha1.ClusterEndpointList, *applyconfigurationsarcv1alpha1.ClusterEndpointApplyConfiguration](
			"clusterendpoints",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *arcv1alpha1.ClusterEndpoint { return &arcv1alpha1.ClusterEndpoint{} },
			func() *arcv1alpha1.ClusterEndpointList { return &arcv1alpha1.ClusterEndpointList{} },
		),
	}
}
