// Copyright 2025 BWI GmbH and Artefact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	arcv1alpha1 "go.opendefense.cloud/arc/api/arc/v1alpha1"
	applyconfigurationsarcv1alpha1 "go.opendefense.cloud/arc/client-go/applyconfigurations/arc/v1alpha1"
	scheme "go.opendefense.cloud/arc/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// EndpointsGetter has a method to return a EndpointInterface.
// A group's client should implement this interface.
type EndpointsGetter interface {
	Endpoints(namespace string) EndpointInterface
}

// EndpointInterface has methods to work with Endpoint resources.
type EndpointInterface interface {
	Create(ctx context.Context, endpoint *arcv1alpha1.Endpoint, opts v1.CreateOptions) (*arcv1alpha1.Endpoint, error)
	Update(ctx context.Context, endpoint *arcv1alpha1.Endpoint, opts v1.UpdateOptions) (*arcv1alpha1.Endpoint, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, endpoint *arcv1alpha1.Endpoint, opts v1.UpdateOptions) (*arcv1alpha1.Endpoint, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*arcv1alpha1.Endpoint, error)
	List(ctx context.Context, opts v1.ListOptions) (*arcv1alpha1.EndpointList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *arcv1alpha1.Endpoint, err error)
	Apply(ctx context.Context, endpoint *applyconfigurationsarcv1alpha1.EndpointApplyConfiguration, opts v1.ApplyOptions) (result *arcv1alpha1.Endpoint, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, endpoint *applyconfigurationsarcv1alpha1.EndpointApplyConfiguration, opts v1.ApplyOptions) (result *arcv1alpha1.Endpoint, err error)
	EndpointExpansion
}

// endpoints implements EndpointInterface
type endpoints struct {
	*gentype.ClientWithListAndApply[*arcv1alpha1.Endpoint, *arcv1alpha1.EndpointList, *applyconfigurationsarcv1alpha1.EndpointApplyConfiguration]
}

// newEndpoints returns a Endpoints
func newEndpoints(c *ArcV1alpha1Client, namespace string) *endpoints {
	return &endpoints{
		gentype.NewClientWithListAndApply[*arcv1alpha1.Endpoint, *arcv1alpha1.EndpointList, *applyconfigurationsarcv1alpha1.EndpointApplyConfiguration](
			"endpoints",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *arcv1alpha1.Endpoint { return &arcv1alpha1.Endpoint{} },
			func() *arcv1alpha1.EndpointList { return &arcv1alpha1.EndpointList{} },
		),
	}
}
