// Copyright 2025 BWI GmbH and Artefact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	arcv1alpha1 "github.com/opendefensecloud/artifact-conduit/api/arc/v1alpha1"
	applyconfigurationsarcv1alpha1 "github.com/opendefensecloud/artifact-conduit/client-go/applyconfigurations/arc/v1alpha1"
	scheme "github.com/opendefensecloud/artifact-conduit/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// FragmentsGetter has a method to return a FragmentInterface.
// A group's client should implement this interface.
type FragmentsGetter interface {
	Fragments(namespace string) FragmentInterface
}

// FragmentInterface has methods to work with Fragment resources.
type FragmentInterface interface {
	Create(ctx context.Context, fragment *arcv1alpha1.Fragment, opts v1.CreateOptions) (*arcv1alpha1.Fragment, error)
	Update(ctx context.Context, fragment *arcv1alpha1.Fragment, opts v1.UpdateOptions) (*arcv1alpha1.Fragment, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, fragment *arcv1alpha1.Fragment, opts v1.UpdateOptions) (*arcv1alpha1.Fragment, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*arcv1alpha1.Fragment, error)
	List(ctx context.Context, opts v1.ListOptions) (*arcv1alpha1.FragmentList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *arcv1alpha1.Fragment, err error)
	Apply(ctx context.Context, fragment *applyconfigurationsarcv1alpha1.FragmentApplyConfiguration, opts v1.ApplyOptions) (result *arcv1alpha1.Fragment, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, fragment *applyconfigurationsarcv1alpha1.FragmentApplyConfiguration, opts v1.ApplyOptions) (result *arcv1alpha1.Fragment, err error)
	FragmentExpansion
}

// fragments implements FragmentInterface
type fragments struct {
	*gentype.ClientWithListAndApply[*arcv1alpha1.Fragment, *arcv1alpha1.FragmentList, *applyconfigurationsarcv1alpha1.FragmentApplyConfiguration]
}

// newFragments returns a Fragments
func newFragments(c *ArcV1alpha1Client, namespace string) *fragments {
	return &fragments{
		gentype.NewClientWithListAndApply[*arcv1alpha1.Fragment, *arcv1alpha1.FragmentList, *applyconfigurationsarcv1alpha1.FragmentApplyConfiguration](
			"fragments",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *arcv1alpha1.Fragment { return &arcv1alpha1.Fragment{} },
			func() *arcv1alpha1.FragmentList { return &arcv1alpha1.FragmentList{} },
		),
	}
}
