// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type ArtifactTypeExpansion interface{}

type ArtifactWorkflowExpansion interface{}

type EndpointExpansion interface{}

type OrderExpansion interface{}
