//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2025 BWI GmbH and Artefact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	order "gitlab.opencode.de/bwi/ace/artifact-conduit/api/order"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Order)(nil), (*order.Order)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Order_To_order_Order(a.(*Order), b.(*order.Order), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*order.Order)(nil), (*Order)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_order_Order_To_v1alpha1_Order(a.(*order.Order), b.(*Order), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OrderList)(nil), (*order.OrderList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OrderList_To_order_OrderList(a.(*OrderList), b.(*order.OrderList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*order.OrderList)(nil), (*OrderList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_order_OrderList_To_v1alpha1_OrderList(a.(*order.OrderList), b.(*OrderList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OrderSpec)(nil), (*order.OrderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OrderSpec_To_order_OrderSpec(a.(*OrderSpec), b.(*order.OrderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*order.OrderSpec)(nil), (*OrderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_order_OrderSpec_To_v1alpha1_OrderSpec(a.(*order.OrderSpec), b.(*OrderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OrderStatus)(nil), (*order.OrderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OrderStatus_To_order_OrderStatus(a.(*OrderStatus), b.(*order.OrderStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*order.OrderStatus)(nil), (*OrderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_order_OrderStatus_To_v1alpha1_OrderStatus(a.(*order.OrderStatus), b.(*OrderStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Order_To_order_Order(in *Order, out *order.Order, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_OrderSpec_To_order_OrderSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_OrderStatus_To_order_OrderStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Order_To_order_Order is an autogenerated conversion function.
func Convert_v1alpha1_Order_To_order_Order(in *Order, out *order.Order, s conversion.Scope) error {
	return autoConvert_v1alpha1_Order_To_order_Order(in, out, s)
}

func autoConvert_order_Order_To_v1alpha1_Order(in *order.Order, out *Order, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_order_OrderSpec_To_v1alpha1_OrderSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_order_OrderStatus_To_v1alpha1_OrderStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_order_Order_To_v1alpha1_Order is an autogenerated conversion function.
func Convert_order_Order_To_v1alpha1_Order(in *order.Order, out *Order, s conversion.Scope) error {
	return autoConvert_order_Order_To_v1alpha1_Order(in, out, s)
}

func autoConvert_v1alpha1_OrderList_To_order_OrderList(in *OrderList, out *order.OrderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]order.Order)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_OrderList_To_order_OrderList is an autogenerated conversion function.
func Convert_v1alpha1_OrderList_To_order_OrderList(in *OrderList, out *order.OrderList, s conversion.Scope) error {
	return autoConvert_v1alpha1_OrderList_To_order_OrderList(in, out, s)
}

func autoConvert_order_OrderList_To_v1alpha1_OrderList(in *order.OrderList, out *OrderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Order)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_order_OrderList_To_v1alpha1_OrderList is an autogenerated conversion function.
func Convert_order_OrderList_To_v1alpha1_OrderList(in *order.OrderList, out *OrderList, s conversion.Scope) error {
	return autoConvert_order_OrderList_To_v1alpha1_OrderList(in, out, s)
}

func autoConvert_v1alpha1_OrderSpec_To_order_OrderSpec(in *OrderSpec, out *order.OrderSpec, s conversion.Scope) error {
	out.RawExtension = in.RawExtension
	return nil
}

// Convert_v1alpha1_OrderSpec_To_order_OrderSpec is an autogenerated conversion function.
func Convert_v1alpha1_OrderSpec_To_order_OrderSpec(in *OrderSpec, out *order.OrderSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_OrderSpec_To_order_OrderSpec(in, out, s)
}

func autoConvert_order_OrderSpec_To_v1alpha1_OrderSpec(in *order.OrderSpec, out *OrderSpec, s conversion.Scope) error {
	out.RawExtension = in.RawExtension
	return nil
}

// Convert_order_OrderSpec_To_v1alpha1_OrderSpec is an autogenerated conversion function.
func Convert_order_OrderSpec_To_v1alpha1_OrderSpec(in *order.OrderSpec, out *OrderSpec, s conversion.Scope) error {
	return autoConvert_order_OrderSpec_To_v1alpha1_OrderSpec(in, out, s)
}

func autoConvert_v1alpha1_OrderStatus_To_order_OrderStatus(in *OrderStatus, out *order.OrderStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_OrderStatus_To_order_OrderStatus is an autogenerated conversion function.
func Convert_v1alpha1_OrderStatus_To_order_OrderStatus(in *OrderStatus, out *order.OrderStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_OrderStatus_To_order_OrderStatus(in, out, s)
}

func autoConvert_order_OrderStatus_To_v1alpha1_OrderStatus(in *order.OrderStatus, out *OrderStatus, s conversion.Scope) error {
	return nil
}

// Convert_order_OrderStatus_To_v1alpha1_OrderStatus is an autogenerated conversion function.
func Convert_order_OrderStatus_To_v1alpha1_OrderStatus(in *order.OrderStatus, out *OrderStatus, s conversion.Scope) error {
	return autoConvert_order_OrderStatus_To_v1alpha1_OrderStatus(in, out, s)
}
