// Copyright 2025 BWI GmbH and Artefact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "gitlab.opencode.de/bwi/ace/artifact-conduit/client-go/arc/versioned/typed/order/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeOrderV1alpha1 struct {
	*testing.Fake
}

func (c *FakeOrderV1alpha1) Orders(namespace string) v1alpha1.OrderInterface {
	return newFakeOrders(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeOrderV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
