//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by openapi-gen. DO NOT EDIT.

package v1alpha1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ArtifactTypeDefinition) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.ArtifactTypeDefinition"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ArtifactTypeDefinitionList) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.ArtifactTypeDefinitionList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ArtifactTypeDefinitionRules) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.ArtifactTypeDefinitionRules"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ArtifactTypeDefinitionSpec) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.ArtifactTypeDefinitionSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ArtifactTypeDefinitionStatus) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.ArtifactTypeDefinitionStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Endpoint) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.Endpoint"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EndpointList) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.EndpointList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EndpointSpec) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.EndpointSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EndpointStatus) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.EndpointStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Fragment) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.Fragment"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FragmentList) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.FragmentList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FragmentSpec) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.FragmentSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FragmentStatus) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.FragmentStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Order) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.Order"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in OrderArtifact) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.OrderArtifact"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in OrderDefaults) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.OrderDefaults"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in OrderList) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.OrderList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in OrderSpec) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.OrderSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in OrderStatus) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.OrderStatus"
}
