//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2025 BWI GmbH and Artefact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	arc "gitlab.opencode.de/bwi/ace/artifact-conduit/api/arc"
	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ArtifactTypeDefinition)(nil), (*arc.ArtifactTypeDefinition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ArtifactTypeDefinition_To_arc_ArtifactTypeDefinition(a.(*ArtifactTypeDefinition), b.(*arc.ArtifactTypeDefinition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.ArtifactTypeDefinition)(nil), (*ArtifactTypeDefinition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_ArtifactTypeDefinition_To_v1alpha1_ArtifactTypeDefinition(a.(*arc.ArtifactTypeDefinition), b.(*ArtifactTypeDefinition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ArtifactTypeDefinitionList)(nil), (*arc.ArtifactTypeDefinitionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ArtifactTypeDefinitionList_To_arc_ArtifactTypeDefinitionList(a.(*ArtifactTypeDefinitionList), b.(*arc.ArtifactTypeDefinitionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.ArtifactTypeDefinitionList)(nil), (*ArtifactTypeDefinitionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_ArtifactTypeDefinitionList_To_v1alpha1_ArtifactTypeDefinitionList(a.(*arc.ArtifactTypeDefinitionList), b.(*ArtifactTypeDefinitionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ArtifactTypeDefinitionRules)(nil), (*arc.ArtifactTypeDefinitionRules)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ArtifactTypeDefinitionRules_To_arc_ArtifactTypeDefinitionRules(a.(*ArtifactTypeDefinitionRules), b.(*arc.ArtifactTypeDefinitionRules), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.ArtifactTypeDefinitionRules)(nil), (*ArtifactTypeDefinitionRules)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_ArtifactTypeDefinitionRules_To_v1alpha1_ArtifactTypeDefinitionRules(a.(*arc.ArtifactTypeDefinitionRules), b.(*ArtifactTypeDefinitionRules), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ArtifactTypeDefinitionSpec)(nil), (*arc.ArtifactTypeDefinitionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ArtifactTypeDefinitionSpec_To_arc_ArtifactTypeDefinitionSpec(a.(*ArtifactTypeDefinitionSpec), b.(*arc.ArtifactTypeDefinitionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.ArtifactTypeDefinitionSpec)(nil), (*ArtifactTypeDefinitionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_ArtifactTypeDefinitionSpec_To_v1alpha1_ArtifactTypeDefinitionSpec(a.(*arc.ArtifactTypeDefinitionSpec), b.(*ArtifactTypeDefinitionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ArtifactTypeDefinitionStatus)(nil), (*arc.ArtifactTypeDefinitionStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ArtifactTypeDefinitionStatus_To_arc_ArtifactTypeDefinitionStatus(a.(*ArtifactTypeDefinitionStatus), b.(*arc.ArtifactTypeDefinitionStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.ArtifactTypeDefinitionStatus)(nil), (*ArtifactTypeDefinitionStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_ArtifactTypeDefinitionStatus_To_v1alpha1_ArtifactTypeDefinitionStatus(a.(*arc.ArtifactTypeDefinitionStatus), b.(*ArtifactTypeDefinitionStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Endpoint)(nil), (*arc.Endpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Endpoint_To_arc_Endpoint(a.(*Endpoint), b.(*arc.Endpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.Endpoint)(nil), (*Endpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_Endpoint_To_v1alpha1_Endpoint(a.(*arc.Endpoint), b.(*Endpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EndpointList)(nil), (*arc.EndpointList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_EndpointList_To_arc_EndpointList(a.(*EndpointList), b.(*arc.EndpointList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.EndpointList)(nil), (*EndpointList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_EndpointList_To_v1alpha1_EndpointList(a.(*arc.EndpointList), b.(*EndpointList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EndpointSpec)(nil), (*arc.EndpointSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_EndpointSpec_To_arc_EndpointSpec(a.(*EndpointSpec), b.(*arc.EndpointSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.EndpointSpec)(nil), (*EndpointSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_EndpointSpec_To_v1alpha1_EndpointSpec(a.(*arc.EndpointSpec), b.(*EndpointSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EndpointStatus)(nil), (*arc.EndpointStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_EndpointStatus_To_arc_EndpointStatus(a.(*EndpointStatus), b.(*arc.EndpointStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.EndpointStatus)(nil), (*EndpointStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_EndpointStatus_To_v1alpha1_EndpointStatus(a.(*arc.EndpointStatus), b.(*EndpointStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Fragment)(nil), (*arc.Fragment)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Fragment_To_arc_Fragment(a.(*Fragment), b.(*arc.Fragment), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.Fragment)(nil), (*Fragment)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_Fragment_To_v1alpha1_Fragment(a.(*arc.Fragment), b.(*Fragment), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FragmentList)(nil), (*arc.FragmentList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FragmentList_To_arc_FragmentList(a.(*FragmentList), b.(*arc.FragmentList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.FragmentList)(nil), (*FragmentList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_FragmentList_To_v1alpha1_FragmentList(a.(*arc.FragmentList), b.(*FragmentList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FragmentSpec)(nil), (*arc.FragmentSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FragmentSpec_To_arc_FragmentSpec(a.(*FragmentSpec), b.(*arc.FragmentSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.FragmentSpec)(nil), (*FragmentSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_FragmentSpec_To_v1alpha1_FragmentSpec(a.(*arc.FragmentSpec), b.(*FragmentSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FragmentStatus)(nil), (*arc.FragmentStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FragmentStatus_To_arc_FragmentStatus(a.(*FragmentStatus), b.(*arc.FragmentStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.FragmentStatus)(nil), (*FragmentStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_FragmentStatus_To_v1alpha1_FragmentStatus(a.(*arc.FragmentStatus), b.(*FragmentStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Order)(nil), (*arc.Order)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Order_To_arc_Order(a.(*Order), b.(*arc.Order), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.Order)(nil), (*Order)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_Order_To_v1alpha1_Order(a.(*arc.Order), b.(*Order), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OrderArtifact)(nil), (*arc.OrderArtifact)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OrderArtifact_To_arc_OrderArtifact(a.(*OrderArtifact), b.(*arc.OrderArtifact), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.OrderArtifact)(nil), (*OrderArtifact)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_OrderArtifact_To_v1alpha1_OrderArtifact(a.(*arc.OrderArtifact), b.(*OrderArtifact), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OrderDefaults)(nil), (*arc.OrderDefaults)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OrderDefaults_To_arc_OrderDefaults(a.(*OrderDefaults), b.(*arc.OrderDefaults), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.OrderDefaults)(nil), (*OrderDefaults)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_OrderDefaults_To_v1alpha1_OrderDefaults(a.(*arc.OrderDefaults), b.(*OrderDefaults), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OrderList)(nil), (*arc.OrderList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OrderList_To_arc_OrderList(a.(*OrderList), b.(*arc.OrderList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.OrderList)(nil), (*OrderList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_OrderList_To_v1alpha1_OrderList(a.(*arc.OrderList), b.(*OrderList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OrderSpec)(nil), (*arc.OrderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OrderSpec_To_arc_OrderSpec(a.(*OrderSpec), b.(*arc.OrderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.OrderSpec)(nil), (*OrderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_OrderSpec_To_v1alpha1_OrderSpec(a.(*arc.OrderSpec), b.(*OrderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OrderStatus)(nil), (*arc.OrderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OrderStatus_To_arc_OrderStatus(a.(*OrderStatus), b.(*arc.OrderStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.OrderStatus)(nil), (*OrderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_OrderStatus_To_v1alpha1_OrderStatus(a.(*arc.OrderStatus), b.(*OrderStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ArtifactTypeDefinition_To_arc_ArtifactTypeDefinition(in *ArtifactTypeDefinition, out *arc.ArtifactTypeDefinition, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ArtifactTypeDefinitionSpec_To_arc_ArtifactTypeDefinitionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ArtifactTypeDefinitionStatus_To_arc_ArtifactTypeDefinitionStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ArtifactTypeDefinition_To_arc_ArtifactTypeDefinition is an autogenerated conversion function.
func Convert_v1alpha1_ArtifactTypeDefinition_To_arc_ArtifactTypeDefinition(in *ArtifactTypeDefinition, out *arc.ArtifactTypeDefinition, s conversion.Scope) error {
	return autoConvert_v1alpha1_ArtifactTypeDefinition_To_arc_ArtifactTypeDefinition(in, out, s)
}

func autoConvert_arc_ArtifactTypeDefinition_To_v1alpha1_ArtifactTypeDefinition(in *arc.ArtifactTypeDefinition, out *ArtifactTypeDefinition, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_arc_ArtifactTypeDefinitionSpec_To_v1alpha1_ArtifactTypeDefinitionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_arc_ArtifactTypeDefinitionStatus_To_v1alpha1_ArtifactTypeDefinitionStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_arc_ArtifactTypeDefinition_To_v1alpha1_ArtifactTypeDefinition is an autogenerated conversion function.
func Convert_arc_ArtifactTypeDefinition_To_v1alpha1_ArtifactTypeDefinition(in *arc.ArtifactTypeDefinition, out *ArtifactTypeDefinition, s conversion.Scope) error {
	return autoConvert_arc_ArtifactTypeDefinition_To_v1alpha1_ArtifactTypeDefinition(in, out, s)
}

func autoConvert_v1alpha1_ArtifactTypeDefinitionList_To_arc_ArtifactTypeDefinitionList(in *ArtifactTypeDefinitionList, out *arc.ArtifactTypeDefinitionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]arc.ArtifactTypeDefinition)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ArtifactTypeDefinitionList_To_arc_ArtifactTypeDefinitionList is an autogenerated conversion function.
func Convert_v1alpha1_ArtifactTypeDefinitionList_To_arc_ArtifactTypeDefinitionList(in *ArtifactTypeDefinitionList, out *arc.ArtifactTypeDefinitionList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ArtifactTypeDefinitionList_To_arc_ArtifactTypeDefinitionList(in, out, s)
}

func autoConvert_arc_ArtifactTypeDefinitionList_To_v1alpha1_ArtifactTypeDefinitionList(in *arc.ArtifactTypeDefinitionList, out *ArtifactTypeDefinitionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ArtifactTypeDefinition)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_arc_ArtifactTypeDefinitionList_To_v1alpha1_ArtifactTypeDefinitionList is an autogenerated conversion function.
func Convert_arc_ArtifactTypeDefinitionList_To_v1alpha1_ArtifactTypeDefinitionList(in *arc.ArtifactTypeDefinitionList, out *ArtifactTypeDefinitionList, s conversion.Scope) error {
	return autoConvert_arc_ArtifactTypeDefinitionList_To_v1alpha1_ArtifactTypeDefinitionList(in, out, s)
}

func autoConvert_v1alpha1_ArtifactTypeDefinitionRules_To_arc_ArtifactTypeDefinitionRules(in *ArtifactTypeDefinitionRules, out *arc.ArtifactTypeDefinitionRules, s conversion.Scope) error {
	out.SrcTypes = *(*[]string)(unsafe.Pointer(&in.SrcTypes))
	out.DstTypes = *(*[]string)(unsafe.Pointer(&in.DstTypes))
	return nil
}

// Convert_v1alpha1_ArtifactTypeDefinitionRules_To_arc_ArtifactTypeDefinitionRules is an autogenerated conversion function.
func Convert_v1alpha1_ArtifactTypeDefinitionRules_To_arc_ArtifactTypeDefinitionRules(in *ArtifactTypeDefinitionRules, out *arc.ArtifactTypeDefinitionRules, s conversion.Scope) error {
	return autoConvert_v1alpha1_ArtifactTypeDefinitionRules_To_arc_ArtifactTypeDefinitionRules(in, out, s)
}

func autoConvert_arc_ArtifactTypeDefinitionRules_To_v1alpha1_ArtifactTypeDefinitionRules(in *arc.ArtifactTypeDefinitionRules, out *ArtifactTypeDefinitionRules, s conversion.Scope) error {
	out.SrcTypes = *(*[]string)(unsafe.Pointer(&in.SrcTypes))
	out.DstTypes = *(*[]string)(unsafe.Pointer(&in.DstTypes))
	return nil
}

// Convert_arc_ArtifactTypeDefinitionRules_To_v1alpha1_ArtifactTypeDefinitionRules is an autogenerated conversion function.
func Convert_arc_ArtifactTypeDefinitionRules_To_v1alpha1_ArtifactTypeDefinitionRules(in *arc.ArtifactTypeDefinitionRules, out *ArtifactTypeDefinitionRules, s conversion.Scope) error {
	return autoConvert_arc_ArtifactTypeDefinitionRules_To_v1alpha1_ArtifactTypeDefinitionRules(in, out, s)
}

func autoConvert_v1alpha1_ArtifactTypeDefinitionSpec_To_arc_ArtifactTypeDefinitionSpec(in *ArtifactTypeDefinitionSpec, out *arc.ArtifactTypeDefinitionSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_ArtifactTypeDefinitionRules_To_arc_ArtifactTypeDefinitionRules(&in.Rules, &out.Rules, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_OrderDefaults_To_arc_OrderDefaults(&in.Defaults, &out.Defaults, s); err != nil {
		return err
	}
	out.WorkflowTemplateRef = in.WorkflowTemplateRef
	return nil
}

// Convert_v1alpha1_ArtifactTypeDefinitionSpec_To_arc_ArtifactTypeDefinitionSpec is an autogenerated conversion function.
func Convert_v1alpha1_ArtifactTypeDefinitionSpec_To_arc_ArtifactTypeDefinitionSpec(in *ArtifactTypeDefinitionSpec, out *arc.ArtifactTypeDefinitionSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ArtifactTypeDefinitionSpec_To_arc_ArtifactTypeDefinitionSpec(in, out, s)
}

func autoConvert_arc_ArtifactTypeDefinitionSpec_To_v1alpha1_ArtifactTypeDefinitionSpec(in *arc.ArtifactTypeDefinitionSpec, out *ArtifactTypeDefinitionSpec, s conversion.Scope) error {
	if err := Convert_arc_ArtifactTypeDefinitionRules_To_v1alpha1_ArtifactTypeDefinitionRules(&in.Rules, &out.Rules, s); err != nil {
		return err
	}
	if err := Convert_arc_OrderDefaults_To_v1alpha1_OrderDefaults(&in.Defaults, &out.Defaults, s); err != nil {
		return err
	}
	out.WorkflowTemplateRef = in.WorkflowTemplateRef
	return nil
}

// Convert_arc_ArtifactTypeDefinitionSpec_To_v1alpha1_ArtifactTypeDefinitionSpec is an autogenerated conversion function.
func Convert_arc_ArtifactTypeDefinitionSpec_To_v1alpha1_ArtifactTypeDefinitionSpec(in *arc.ArtifactTypeDefinitionSpec, out *ArtifactTypeDefinitionSpec, s conversion.Scope) error {
	return autoConvert_arc_ArtifactTypeDefinitionSpec_To_v1alpha1_ArtifactTypeDefinitionSpec(in, out, s)
}

func autoConvert_v1alpha1_ArtifactTypeDefinitionStatus_To_arc_ArtifactTypeDefinitionStatus(in *ArtifactTypeDefinitionStatus, out *arc.ArtifactTypeDefinitionStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_ArtifactTypeDefinitionStatus_To_arc_ArtifactTypeDefinitionStatus is an autogenerated conversion function.
func Convert_v1alpha1_ArtifactTypeDefinitionStatus_To_arc_ArtifactTypeDefinitionStatus(in *ArtifactTypeDefinitionStatus, out *arc.ArtifactTypeDefinitionStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ArtifactTypeDefinitionStatus_To_arc_ArtifactTypeDefinitionStatus(in, out, s)
}

func autoConvert_arc_ArtifactTypeDefinitionStatus_To_v1alpha1_ArtifactTypeDefinitionStatus(in *arc.ArtifactTypeDefinitionStatus, out *ArtifactTypeDefinitionStatus, s conversion.Scope) error {
	return nil
}

// Convert_arc_ArtifactTypeDefinitionStatus_To_v1alpha1_ArtifactTypeDefinitionStatus is an autogenerated conversion function.
func Convert_arc_ArtifactTypeDefinitionStatus_To_v1alpha1_ArtifactTypeDefinitionStatus(in *arc.ArtifactTypeDefinitionStatus, out *ArtifactTypeDefinitionStatus, s conversion.Scope) error {
	return autoConvert_arc_ArtifactTypeDefinitionStatus_To_v1alpha1_ArtifactTypeDefinitionStatus(in, out, s)
}

func autoConvert_v1alpha1_Endpoint_To_arc_Endpoint(in *Endpoint, out *arc.Endpoint, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_EndpointSpec_To_arc_EndpointSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_EndpointStatus_To_arc_EndpointStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Endpoint_To_arc_Endpoint is an autogenerated conversion function.
func Convert_v1alpha1_Endpoint_To_arc_Endpoint(in *Endpoint, out *arc.Endpoint, s conversion.Scope) error {
	return autoConvert_v1alpha1_Endpoint_To_arc_Endpoint(in, out, s)
}

func autoConvert_arc_Endpoint_To_v1alpha1_Endpoint(in *arc.Endpoint, out *Endpoint, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_arc_EndpointSpec_To_v1alpha1_EndpointSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_arc_EndpointStatus_To_v1alpha1_EndpointStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_arc_Endpoint_To_v1alpha1_Endpoint is an autogenerated conversion function.
func Convert_arc_Endpoint_To_v1alpha1_Endpoint(in *arc.Endpoint, out *Endpoint, s conversion.Scope) error {
	return autoConvert_arc_Endpoint_To_v1alpha1_Endpoint(in, out, s)
}

func autoConvert_v1alpha1_EndpointList_To_arc_EndpointList(in *EndpointList, out *arc.EndpointList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]arc.Endpoint)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_EndpointList_To_arc_EndpointList is an autogenerated conversion function.
func Convert_v1alpha1_EndpointList_To_arc_EndpointList(in *EndpointList, out *arc.EndpointList, s conversion.Scope) error {
	return autoConvert_v1alpha1_EndpointList_To_arc_EndpointList(in, out, s)
}

func autoConvert_arc_EndpointList_To_v1alpha1_EndpointList(in *arc.EndpointList, out *EndpointList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Endpoint)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_arc_EndpointList_To_v1alpha1_EndpointList is an autogenerated conversion function.
func Convert_arc_EndpointList_To_v1alpha1_EndpointList(in *arc.EndpointList, out *EndpointList, s conversion.Scope) error {
	return autoConvert_arc_EndpointList_To_v1alpha1_EndpointList(in, out, s)
}

func autoConvert_v1alpha1_EndpointSpec_To_arc_EndpointSpec(in *EndpointSpec, out *arc.EndpointSpec, s conversion.Scope) error {
	out.Type = in.Type
	out.RemoteURL = in.RemoteURL
	out.SecretRef = in.SecretRef
	out.Usage = arc.EndpointUsage(in.Usage)
	return nil
}

// Convert_v1alpha1_EndpointSpec_To_arc_EndpointSpec is an autogenerated conversion function.
func Convert_v1alpha1_EndpointSpec_To_arc_EndpointSpec(in *EndpointSpec, out *arc.EndpointSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_EndpointSpec_To_arc_EndpointSpec(in, out, s)
}

func autoConvert_arc_EndpointSpec_To_v1alpha1_EndpointSpec(in *arc.EndpointSpec, out *EndpointSpec, s conversion.Scope) error {
	out.Type = in.Type
	out.RemoteURL = in.RemoteURL
	out.SecretRef = in.SecretRef
	out.Usage = EndpointUsage(in.Usage)
	return nil
}

// Convert_arc_EndpointSpec_To_v1alpha1_EndpointSpec is an autogenerated conversion function.
func Convert_arc_EndpointSpec_To_v1alpha1_EndpointSpec(in *arc.EndpointSpec, out *EndpointSpec, s conversion.Scope) error {
	return autoConvert_arc_EndpointSpec_To_v1alpha1_EndpointSpec(in, out, s)
}

func autoConvert_v1alpha1_EndpointStatus_To_arc_EndpointStatus(in *EndpointStatus, out *arc.EndpointStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_EndpointStatus_To_arc_EndpointStatus is an autogenerated conversion function.
func Convert_v1alpha1_EndpointStatus_To_arc_EndpointStatus(in *EndpointStatus, out *arc.EndpointStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_EndpointStatus_To_arc_EndpointStatus(in, out, s)
}

func autoConvert_arc_EndpointStatus_To_v1alpha1_EndpointStatus(in *arc.EndpointStatus, out *EndpointStatus, s conversion.Scope) error {
	return nil
}

// Convert_arc_EndpointStatus_To_v1alpha1_EndpointStatus is an autogenerated conversion function.
func Convert_arc_EndpointStatus_To_v1alpha1_EndpointStatus(in *arc.EndpointStatus, out *EndpointStatus, s conversion.Scope) error {
	return autoConvert_arc_EndpointStatus_To_v1alpha1_EndpointStatus(in, out, s)
}

func autoConvert_v1alpha1_Fragment_To_arc_Fragment(in *Fragment, out *arc.Fragment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_FragmentSpec_To_arc_FragmentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_FragmentStatus_To_arc_FragmentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Fragment_To_arc_Fragment is an autogenerated conversion function.
func Convert_v1alpha1_Fragment_To_arc_Fragment(in *Fragment, out *arc.Fragment, s conversion.Scope) error {
	return autoConvert_v1alpha1_Fragment_To_arc_Fragment(in, out, s)
}

func autoConvert_arc_Fragment_To_v1alpha1_Fragment(in *arc.Fragment, out *Fragment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_arc_FragmentSpec_To_v1alpha1_FragmentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_arc_FragmentStatus_To_v1alpha1_FragmentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_arc_Fragment_To_v1alpha1_Fragment is an autogenerated conversion function.
func Convert_arc_Fragment_To_v1alpha1_Fragment(in *arc.Fragment, out *Fragment, s conversion.Scope) error {
	return autoConvert_arc_Fragment_To_v1alpha1_Fragment(in, out, s)
}

func autoConvert_v1alpha1_FragmentList_To_arc_FragmentList(in *FragmentList, out *arc.FragmentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]arc.Fragment)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_FragmentList_To_arc_FragmentList is an autogenerated conversion function.
func Convert_v1alpha1_FragmentList_To_arc_FragmentList(in *FragmentList, out *arc.FragmentList, s conversion.Scope) error {
	return autoConvert_v1alpha1_FragmentList_To_arc_FragmentList(in, out, s)
}

func autoConvert_arc_FragmentList_To_v1alpha1_FragmentList(in *arc.FragmentList, out *FragmentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Fragment)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_arc_FragmentList_To_v1alpha1_FragmentList is an autogenerated conversion function.
func Convert_arc_FragmentList_To_v1alpha1_FragmentList(in *arc.FragmentList, out *FragmentList, s conversion.Scope) error {
	return autoConvert_arc_FragmentList_To_v1alpha1_FragmentList(in, out, s)
}

func autoConvert_v1alpha1_FragmentSpec_To_arc_FragmentSpec(in *FragmentSpec, out *arc.FragmentSpec, s conversion.Scope) error {
	out.Type = in.Type
	out.SrcRef = in.SrcRef
	out.DstRef = in.DstRef
	out.Spec = in.Spec
	return nil
}

// Convert_v1alpha1_FragmentSpec_To_arc_FragmentSpec is an autogenerated conversion function.
func Convert_v1alpha1_FragmentSpec_To_arc_FragmentSpec(in *FragmentSpec, out *arc.FragmentSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_FragmentSpec_To_arc_FragmentSpec(in, out, s)
}

func autoConvert_arc_FragmentSpec_To_v1alpha1_FragmentSpec(in *arc.FragmentSpec, out *FragmentSpec, s conversion.Scope) error {
	out.Type = in.Type
	out.SrcRef = in.SrcRef
	out.DstRef = in.DstRef
	out.Spec = in.Spec
	return nil
}

// Convert_arc_FragmentSpec_To_v1alpha1_FragmentSpec is an autogenerated conversion function.
func Convert_arc_FragmentSpec_To_v1alpha1_FragmentSpec(in *arc.FragmentSpec, out *FragmentSpec, s conversion.Scope) error {
	return autoConvert_arc_FragmentSpec_To_v1alpha1_FragmentSpec(in, out, s)
}

func autoConvert_v1alpha1_FragmentStatus_To_arc_FragmentStatus(in *FragmentStatus, out *arc.FragmentStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_FragmentStatus_To_arc_FragmentStatus is an autogenerated conversion function.
func Convert_v1alpha1_FragmentStatus_To_arc_FragmentStatus(in *FragmentStatus, out *arc.FragmentStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_FragmentStatus_To_arc_FragmentStatus(in, out, s)
}

func autoConvert_arc_FragmentStatus_To_v1alpha1_FragmentStatus(in *arc.FragmentStatus, out *FragmentStatus, s conversion.Scope) error {
	return nil
}

// Convert_arc_FragmentStatus_To_v1alpha1_FragmentStatus is an autogenerated conversion function.
func Convert_arc_FragmentStatus_To_v1alpha1_FragmentStatus(in *arc.FragmentStatus, out *FragmentStatus, s conversion.Scope) error {
	return autoConvert_arc_FragmentStatus_To_v1alpha1_FragmentStatus(in, out, s)
}

func autoConvert_v1alpha1_Order_To_arc_Order(in *Order, out *arc.Order, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_OrderSpec_To_arc_OrderSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_OrderStatus_To_arc_OrderStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Order_To_arc_Order is an autogenerated conversion function.
func Convert_v1alpha1_Order_To_arc_Order(in *Order, out *arc.Order, s conversion.Scope) error {
	return autoConvert_v1alpha1_Order_To_arc_Order(in, out, s)
}

func autoConvert_arc_Order_To_v1alpha1_Order(in *arc.Order, out *Order, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_arc_OrderSpec_To_v1alpha1_OrderSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_arc_OrderStatus_To_v1alpha1_OrderStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_arc_Order_To_v1alpha1_Order is an autogenerated conversion function.
func Convert_arc_Order_To_v1alpha1_Order(in *arc.Order, out *Order, s conversion.Scope) error {
	return autoConvert_arc_Order_To_v1alpha1_Order(in, out, s)
}

func autoConvert_v1alpha1_OrderArtifact_To_arc_OrderArtifact(in *OrderArtifact, out *arc.OrderArtifact, s conversion.Scope) error {
	out.Type = in.Type
	out.SrcRef = in.SrcRef
	out.DstRef = in.DstRef
	out.Spec = in.Spec
	return nil
}

// Convert_v1alpha1_OrderArtifact_To_arc_OrderArtifact is an autogenerated conversion function.
func Convert_v1alpha1_OrderArtifact_To_arc_OrderArtifact(in *OrderArtifact, out *arc.OrderArtifact, s conversion.Scope) error {
	return autoConvert_v1alpha1_OrderArtifact_To_arc_OrderArtifact(in, out, s)
}

func autoConvert_arc_OrderArtifact_To_v1alpha1_OrderArtifact(in *arc.OrderArtifact, out *OrderArtifact, s conversion.Scope) error {
	out.Type = in.Type
	out.SrcRef = in.SrcRef
	out.DstRef = in.DstRef
	out.Spec = in.Spec
	return nil
}

// Convert_arc_OrderArtifact_To_v1alpha1_OrderArtifact is an autogenerated conversion function.
func Convert_arc_OrderArtifact_To_v1alpha1_OrderArtifact(in *arc.OrderArtifact, out *OrderArtifact, s conversion.Scope) error {
	return autoConvert_arc_OrderArtifact_To_v1alpha1_OrderArtifact(in, out, s)
}

func autoConvert_v1alpha1_OrderDefaults_To_arc_OrderDefaults(in *OrderDefaults, out *arc.OrderDefaults, s conversion.Scope) error {
	out.SrcRef = in.SrcRef
	out.DstRef = in.DstRef
	return nil
}

// Convert_v1alpha1_OrderDefaults_To_arc_OrderDefaults is an autogenerated conversion function.
func Convert_v1alpha1_OrderDefaults_To_arc_OrderDefaults(in *OrderDefaults, out *arc.OrderDefaults, s conversion.Scope) error {
	return autoConvert_v1alpha1_OrderDefaults_To_arc_OrderDefaults(in, out, s)
}

func autoConvert_arc_OrderDefaults_To_v1alpha1_OrderDefaults(in *arc.OrderDefaults, out *OrderDefaults, s conversion.Scope) error {
	out.SrcRef = in.SrcRef
	out.DstRef = in.DstRef
	return nil
}

// Convert_arc_OrderDefaults_To_v1alpha1_OrderDefaults is an autogenerated conversion function.
func Convert_arc_OrderDefaults_To_v1alpha1_OrderDefaults(in *arc.OrderDefaults, out *OrderDefaults, s conversion.Scope) error {
	return autoConvert_arc_OrderDefaults_To_v1alpha1_OrderDefaults(in, out, s)
}

func autoConvert_v1alpha1_OrderList_To_arc_OrderList(in *OrderList, out *arc.OrderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]arc.Order)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_OrderList_To_arc_OrderList is an autogenerated conversion function.
func Convert_v1alpha1_OrderList_To_arc_OrderList(in *OrderList, out *arc.OrderList, s conversion.Scope) error {
	return autoConvert_v1alpha1_OrderList_To_arc_OrderList(in, out, s)
}

func autoConvert_arc_OrderList_To_v1alpha1_OrderList(in *arc.OrderList, out *OrderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Order)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_arc_OrderList_To_v1alpha1_OrderList is an autogenerated conversion function.
func Convert_arc_OrderList_To_v1alpha1_OrderList(in *arc.OrderList, out *OrderList, s conversion.Scope) error {
	return autoConvert_arc_OrderList_To_v1alpha1_OrderList(in, out, s)
}

func autoConvert_v1alpha1_OrderSpec_To_arc_OrderSpec(in *OrderSpec, out *arc.OrderSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_OrderDefaults_To_arc_OrderDefaults(&in.Defaults, &out.Defaults, s); err != nil {
		return err
	}
	out.Artifacts = *(*[]arc.OrderArtifact)(unsafe.Pointer(&in.Artifacts))
	return nil
}

// Convert_v1alpha1_OrderSpec_To_arc_OrderSpec is an autogenerated conversion function.
func Convert_v1alpha1_OrderSpec_To_arc_OrderSpec(in *OrderSpec, out *arc.OrderSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_OrderSpec_To_arc_OrderSpec(in, out, s)
}

func autoConvert_arc_OrderSpec_To_v1alpha1_OrderSpec(in *arc.OrderSpec, out *OrderSpec, s conversion.Scope) error {
	if err := Convert_arc_OrderDefaults_To_v1alpha1_OrderDefaults(&in.Defaults, &out.Defaults, s); err != nil {
		return err
	}
	out.Artifacts = *(*[]OrderArtifact)(unsafe.Pointer(&in.Artifacts))
	return nil
}

// Convert_arc_OrderSpec_To_v1alpha1_OrderSpec is an autogenerated conversion function.
func Convert_arc_OrderSpec_To_v1alpha1_OrderSpec(in *arc.OrderSpec, out *OrderSpec, s conversion.Scope) error {
	return autoConvert_arc_OrderSpec_To_v1alpha1_OrderSpec(in, out, s)
}

func autoConvert_v1alpha1_OrderStatus_To_arc_OrderStatus(in *OrderStatus, out *arc.OrderStatus, s conversion.Scope) error {
	out.Fragments = *(*map[string]v1.LocalObjectReference)(unsafe.Pointer(&in.Fragments))
	return nil
}

// Convert_v1alpha1_OrderStatus_To_arc_OrderStatus is an autogenerated conversion function.
func Convert_v1alpha1_OrderStatus_To_arc_OrderStatus(in *OrderStatus, out *arc.OrderStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_OrderStatus_To_arc_OrderStatus(in, out, s)
}

func autoConvert_arc_OrderStatus_To_v1alpha1_OrderStatus(in *arc.OrderStatus, out *OrderStatus, s conversion.Scope) error {
	out.Fragments = *(*map[string]v1.LocalObjectReference)(unsafe.Pointer(&in.Fragments))
	return nil
}

// Convert_arc_OrderStatus_To_v1alpha1_OrderStatus is an autogenerated conversion function.
func Convert_arc_OrderStatus_To_v1alpha1_OrderStatus(in *arc.OrderStatus, out *OrderStatus, s conversion.Scope) error {
	return autoConvert_arc_OrderStatus_To_v1alpha1_OrderStatus(in, out, s)
}
