//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2025 BWI GmbH and Artefact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&Order{}, func(obj interface{}) { SetObjectDefaults_Order(obj.(*Order)) })
	scheme.AddTypeDefaultingFunc(&OrderList{}, func(obj interface{}) { SetObjectDefaults_OrderList(obj.(*OrderList)) })
	return nil
}

func SetObjectDefaults_Order(in *Order) {
	SetDefaults_OrderSpec(&in.Spec)
}

func SetObjectDefaults_OrderList(in *OrderList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_Order(a)
	}
}
