//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&ArtifactType{}, func(obj interface{}) { SetObjectDefaults_ArtifactType(obj.(*ArtifactType)) })
	scheme.AddTypeDefaultingFunc(&ArtifactTypeList{}, func(obj interface{}) { SetObjectDefaults_ArtifactTypeList(obj.(*ArtifactTypeList)) })
	scheme.AddTypeDefaultingFunc(&ArtifactWorkflow{}, func(obj interface{}) { SetObjectDefaults_ArtifactWorkflow(obj.(*ArtifactWorkflow)) })
	scheme.AddTypeDefaultingFunc(&ArtifactWorkflowList{}, func(obj interface{}) { SetObjectDefaults_ArtifactWorkflowList(obj.(*ArtifactWorkflowList)) })
	scheme.AddTypeDefaultingFunc(&Endpoint{}, func(obj interface{}) { SetObjectDefaults_Endpoint(obj.(*Endpoint)) })
	scheme.AddTypeDefaultingFunc(&EndpointList{}, func(obj interface{}) { SetObjectDefaults_EndpointList(obj.(*EndpointList)) })
	scheme.AddTypeDefaultingFunc(&Order{}, func(obj interface{}) { SetObjectDefaults_Order(obj.(*Order)) })
	scheme.AddTypeDefaultingFunc(&OrderList{}, func(obj interface{}) { SetObjectDefaults_OrderList(obj.(*OrderList)) })
	return nil
}

func SetObjectDefaults_ArtifactType(in *ArtifactType) {
	SetDefaults_ArtifactTypeSpec(&in.Spec)
}

func SetObjectDefaults_ArtifactTypeList(in *ArtifactTypeList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_ArtifactType(a)
	}
}

func SetObjectDefaults_ArtifactWorkflow(in *ArtifactWorkflow) {
	SetDefaults_ArtifactWorkflowSpec(&in.Spec)
}

func SetObjectDefaults_ArtifactWorkflowList(in *ArtifactWorkflowList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_ArtifactWorkflow(a)
	}
}

func SetObjectDefaults_Endpoint(in *Endpoint) {
	SetDefaults_EndpointSpec(&in.Spec)
}

func SetObjectDefaults_EndpointList(in *EndpointList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_Endpoint(a)
	}
}

func SetObjectDefaults_Order(in *Order) {
	SetDefaults_OrderSpec(&in.Spec)
}

func SetObjectDefaults_OrderList(in *OrderList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_Order(a)
	}
}
