//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	arc "go.opendefense.cloud/arc/api/arc"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ArtifactType)(nil), (*arc.ArtifactType)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ArtifactType_To_arc_ArtifactType(a.(*ArtifactType), b.(*arc.ArtifactType), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.ArtifactType)(nil), (*ArtifactType)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_ArtifactType_To_v1alpha1_ArtifactType(a.(*arc.ArtifactType), b.(*ArtifactType), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ArtifactTypeList)(nil), (*arc.ArtifactTypeList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ArtifactTypeList_To_arc_ArtifactTypeList(a.(*ArtifactTypeList), b.(*arc.ArtifactTypeList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.ArtifactTypeList)(nil), (*ArtifactTypeList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_ArtifactTypeList_To_v1alpha1_ArtifactTypeList(a.(*arc.ArtifactTypeList), b.(*ArtifactTypeList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ArtifactTypeRules)(nil), (*arc.ArtifactTypeRules)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ArtifactTypeRules_To_arc_ArtifactTypeRules(a.(*ArtifactTypeRules), b.(*arc.ArtifactTypeRules), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.ArtifactTypeRules)(nil), (*ArtifactTypeRules)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_ArtifactTypeRules_To_v1alpha1_ArtifactTypeRules(a.(*arc.ArtifactTypeRules), b.(*ArtifactTypeRules), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ArtifactTypeSpec)(nil), (*arc.ArtifactTypeSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ArtifactTypeSpec_To_arc_ArtifactTypeSpec(a.(*ArtifactTypeSpec), b.(*arc.ArtifactTypeSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.ArtifactTypeSpec)(nil), (*ArtifactTypeSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_ArtifactTypeSpec_To_v1alpha1_ArtifactTypeSpec(a.(*arc.ArtifactTypeSpec), b.(*ArtifactTypeSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ArtifactTypeStatus)(nil), (*arc.ArtifactTypeStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ArtifactTypeStatus_To_arc_ArtifactTypeStatus(a.(*ArtifactTypeStatus), b.(*arc.ArtifactTypeStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.ArtifactTypeStatus)(nil), (*ArtifactTypeStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_ArtifactTypeStatus_To_v1alpha1_ArtifactTypeStatus(a.(*arc.ArtifactTypeStatus), b.(*ArtifactTypeStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Endpoint)(nil), (*arc.Endpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Endpoint_To_arc_Endpoint(a.(*Endpoint), b.(*arc.Endpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.Endpoint)(nil), (*Endpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_Endpoint_To_v1alpha1_Endpoint(a.(*arc.Endpoint), b.(*Endpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EndpointList)(nil), (*arc.EndpointList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_EndpointList_To_arc_EndpointList(a.(*EndpointList), b.(*arc.EndpointList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.EndpointList)(nil), (*EndpointList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_EndpointList_To_v1alpha1_EndpointList(a.(*arc.EndpointList), b.(*EndpointList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EndpointSpec)(nil), (*arc.EndpointSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_EndpointSpec_To_arc_EndpointSpec(a.(*EndpointSpec), b.(*arc.EndpointSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.EndpointSpec)(nil), (*EndpointSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_EndpointSpec_To_v1alpha1_EndpointSpec(a.(*arc.EndpointSpec), b.(*EndpointSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EndpointStatus)(nil), (*arc.EndpointStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_EndpointStatus_To_arc_EndpointStatus(a.(*EndpointStatus), b.(*arc.EndpointStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.EndpointStatus)(nil), (*EndpointStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_EndpointStatus_To_v1alpha1_EndpointStatus(a.(*arc.EndpointStatus), b.(*EndpointStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Order)(nil), (*arc.Order)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Order_To_arc_Order(a.(*Order), b.(*arc.Order), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.Order)(nil), (*Order)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_Order_To_v1alpha1_Order(a.(*arc.Order), b.(*Order), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OrderArtifact)(nil), (*arc.OrderArtifact)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OrderArtifact_To_arc_OrderArtifact(a.(*OrderArtifact), b.(*arc.OrderArtifact), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.OrderArtifact)(nil), (*OrderArtifact)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_OrderArtifact_To_v1alpha1_OrderArtifact(a.(*arc.OrderArtifact), b.(*OrderArtifact), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OrderArtifactWorkflowStatus)(nil), (*arc.OrderArtifactWorkflowStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OrderArtifactWorkflowStatus_To_arc_OrderArtifactWorkflowStatus(a.(*OrderArtifactWorkflowStatus), b.(*arc.OrderArtifactWorkflowStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.OrderArtifactWorkflowStatus)(nil), (*OrderArtifactWorkflowStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_OrderArtifactWorkflowStatus_To_v1alpha1_OrderArtifactWorkflowStatus(a.(*arc.OrderArtifactWorkflowStatus), b.(*OrderArtifactWorkflowStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OrderDefaults)(nil), (*arc.OrderDefaults)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OrderDefaults_To_arc_OrderDefaults(a.(*OrderDefaults), b.(*arc.OrderDefaults), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.OrderDefaults)(nil), (*OrderDefaults)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_OrderDefaults_To_v1alpha1_OrderDefaults(a.(*arc.OrderDefaults), b.(*OrderDefaults), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OrderList)(nil), (*arc.OrderList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OrderList_To_arc_OrderList(a.(*OrderList), b.(*arc.OrderList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.OrderList)(nil), (*OrderList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_OrderList_To_v1alpha1_OrderList(a.(*arc.OrderList), b.(*OrderList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OrderSpec)(nil), (*arc.OrderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OrderSpec_To_arc_OrderSpec(a.(*OrderSpec), b.(*arc.OrderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.OrderSpec)(nil), (*OrderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_OrderSpec_To_v1alpha1_OrderSpec(a.(*arc.OrderSpec), b.(*OrderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OrderStatus)(nil), (*arc.OrderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OrderStatus_To_arc_OrderStatus(a.(*OrderStatus), b.(*arc.OrderStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*arc.OrderStatus)(nil), (*OrderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_arc_OrderStatus_To_v1alpha1_OrderStatus(a.(*arc.OrderStatus), b.(*OrderStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ArtifactType_To_arc_ArtifactType(in *ArtifactType, out *arc.ArtifactType, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ArtifactTypeSpec_To_arc_ArtifactTypeSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ArtifactTypeStatus_To_arc_ArtifactTypeStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ArtifactType_To_arc_ArtifactType is an autogenerated conversion function.
func Convert_v1alpha1_ArtifactType_To_arc_ArtifactType(in *ArtifactType, out *arc.ArtifactType, s conversion.Scope) error {
	return autoConvert_v1alpha1_ArtifactType_To_arc_ArtifactType(in, out, s)
}

func autoConvert_arc_ArtifactType_To_v1alpha1_ArtifactType(in *arc.ArtifactType, out *ArtifactType, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_arc_ArtifactTypeSpec_To_v1alpha1_ArtifactTypeSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_arc_ArtifactTypeStatus_To_v1alpha1_ArtifactTypeStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_arc_ArtifactType_To_v1alpha1_ArtifactType is an autogenerated conversion function.
func Convert_arc_ArtifactType_To_v1alpha1_ArtifactType(in *arc.ArtifactType, out *ArtifactType, s conversion.Scope) error {
	return autoConvert_arc_ArtifactType_To_v1alpha1_ArtifactType(in, out, s)
}

func autoConvert_v1alpha1_ArtifactTypeList_To_arc_ArtifactTypeList(in *ArtifactTypeList, out *arc.ArtifactTypeList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]arc.ArtifactType)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ArtifactTypeList_To_arc_ArtifactTypeList is an autogenerated conversion function.
func Convert_v1alpha1_ArtifactTypeList_To_arc_ArtifactTypeList(in *ArtifactTypeList, out *arc.ArtifactTypeList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ArtifactTypeList_To_arc_ArtifactTypeList(in, out, s)
}

func autoConvert_arc_ArtifactTypeList_To_v1alpha1_ArtifactTypeList(in *arc.ArtifactTypeList, out *ArtifactTypeList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ArtifactType)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_arc_ArtifactTypeList_To_v1alpha1_ArtifactTypeList is an autogenerated conversion function.
func Convert_arc_ArtifactTypeList_To_v1alpha1_ArtifactTypeList(in *arc.ArtifactTypeList, out *ArtifactTypeList, s conversion.Scope) error {
	return autoConvert_arc_ArtifactTypeList_To_v1alpha1_ArtifactTypeList(in, out, s)
}

func autoConvert_v1alpha1_ArtifactTypeRules_To_arc_ArtifactTypeRules(in *ArtifactTypeRules, out *arc.ArtifactTypeRules, s conversion.Scope) error {
	out.SrcTypes = *(*[]string)(unsafe.Pointer(&in.SrcTypes))
	out.DstTypes = *(*[]string)(unsafe.Pointer(&in.DstTypes))
	return nil
}

// Convert_v1alpha1_ArtifactTypeRules_To_arc_ArtifactTypeRules is an autogenerated conversion function.
func Convert_v1alpha1_ArtifactTypeRules_To_arc_ArtifactTypeRules(in *ArtifactTypeRules, out *arc.ArtifactTypeRules, s conversion.Scope) error {
	return autoConvert_v1alpha1_ArtifactTypeRules_To_arc_ArtifactTypeRules(in, out, s)
}

func autoConvert_arc_ArtifactTypeRules_To_v1alpha1_ArtifactTypeRules(in *arc.ArtifactTypeRules, out *ArtifactTypeRules, s conversion.Scope) error {
	out.SrcTypes = *(*[]string)(unsafe.Pointer(&in.SrcTypes))
	out.DstTypes = *(*[]string)(unsafe.Pointer(&in.DstTypes))
	return nil
}

// Convert_arc_ArtifactTypeRules_To_v1alpha1_ArtifactTypeRules is an autogenerated conversion function.
func Convert_arc_ArtifactTypeRules_To_v1alpha1_ArtifactTypeRules(in *arc.ArtifactTypeRules, out *ArtifactTypeRules, s conversion.Scope) error {
	return autoConvert_arc_ArtifactTypeRules_To_v1alpha1_ArtifactTypeRules(in, out, s)
}

func autoConvert_v1alpha1_ArtifactTypeSpec_To_arc_ArtifactTypeSpec(in *ArtifactTypeSpec, out *arc.ArtifactTypeSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_ArtifactTypeRules_To_arc_ArtifactTypeRules(&in.Rules, &out.Rules, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_OrderDefaults_To_arc_OrderDefaults(&in.Defaults, &out.Defaults, s); err != nil {
		return err
	}
	out.WorkflowTemplateRef = in.WorkflowTemplateRef
	return nil
}

// Convert_v1alpha1_ArtifactTypeSpec_To_arc_ArtifactTypeSpec is an autogenerated conversion function.
func Convert_v1alpha1_ArtifactTypeSpec_To_arc_ArtifactTypeSpec(in *ArtifactTypeSpec, out *arc.ArtifactTypeSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ArtifactTypeSpec_To_arc_ArtifactTypeSpec(in, out, s)
}

func autoConvert_arc_ArtifactTypeSpec_To_v1alpha1_ArtifactTypeSpec(in *arc.ArtifactTypeSpec, out *ArtifactTypeSpec, s conversion.Scope) error {
	if err := Convert_arc_ArtifactTypeRules_To_v1alpha1_ArtifactTypeRules(&in.Rules, &out.Rules, s); err != nil {
		return err
	}
	if err := Convert_arc_OrderDefaults_To_v1alpha1_OrderDefaults(&in.Defaults, &out.Defaults, s); err != nil {
		return err
	}
	out.WorkflowTemplateRef = in.WorkflowTemplateRef
	return nil
}

// Convert_arc_ArtifactTypeSpec_To_v1alpha1_ArtifactTypeSpec is an autogenerated conversion function.
func Convert_arc_ArtifactTypeSpec_To_v1alpha1_ArtifactTypeSpec(in *arc.ArtifactTypeSpec, out *ArtifactTypeSpec, s conversion.Scope) error {
	return autoConvert_arc_ArtifactTypeSpec_To_v1alpha1_ArtifactTypeSpec(in, out, s)
}

func autoConvert_v1alpha1_ArtifactTypeStatus_To_arc_ArtifactTypeStatus(in *ArtifactTypeStatus, out *arc.ArtifactTypeStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_ArtifactTypeStatus_To_arc_ArtifactTypeStatus is an autogenerated conversion function.
func Convert_v1alpha1_ArtifactTypeStatus_To_arc_ArtifactTypeStatus(in *ArtifactTypeStatus, out *arc.ArtifactTypeStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ArtifactTypeStatus_To_arc_ArtifactTypeStatus(in, out, s)
}

func autoConvert_arc_ArtifactTypeStatus_To_v1alpha1_ArtifactTypeStatus(in *arc.ArtifactTypeStatus, out *ArtifactTypeStatus, s conversion.Scope) error {
	return nil
}

// Convert_arc_ArtifactTypeStatus_To_v1alpha1_ArtifactTypeStatus is an autogenerated conversion function.
func Convert_arc_ArtifactTypeStatus_To_v1alpha1_ArtifactTypeStatus(in *arc.ArtifactTypeStatus, out *ArtifactTypeStatus, s conversion.Scope) error {
	return autoConvert_arc_ArtifactTypeStatus_To_v1alpha1_ArtifactTypeStatus(in, out, s)
}

func autoConvert_v1alpha1_Endpoint_To_arc_Endpoint(in *Endpoint, out *arc.Endpoint, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_EndpointSpec_To_arc_EndpointSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_EndpointStatus_To_arc_EndpointStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Endpoint_To_arc_Endpoint is an autogenerated conversion function.
func Convert_v1alpha1_Endpoint_To_arc_Endpoint(in *Endpoint, out *arc.Endpoint, s conversion.Scope) error {
	return autoConvert_v1alpha1_Endpoint_To_arc_Endpoint(in, out, s)
}

func autoConvert_arc_Endpoint_To_v1alpha1_Endpoint(in *arc.Endpoint, out *Endpoint, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_arc_EndpointSpec_To_v1alpha1_EndpointSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_arc_EndpointStatus_To_v1alpha1_EndpointStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_arc_Endpoint_To_v1alpha1_Endpoint is an autogenerated conversion function.
func Convert_arc_Endpoint_To_v1alpha1_Endpoint(in *arc.Endpoint, out *Endpoint, s conversion.Scope) error {
	return autoConvert_arc_Endpoint_To_v1alpha1_Endpoint(in, out, s)
}

func autoConvert_v1alpha1_EndpointList_To_arc_EndpointList(in *EndpointList, out *arc.EndpointList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]arc.Endpoint)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_EndpointList_To_arc_EndpointList is an autogenerated conversion function.
func Convert_v1alpha1_EndpointList_To_arc_EndpointList(in *EndpointList, out *arc.EndpointList, s conversion.Scope) error {
	return autoConvert_v1alpha1_EndpointList_To_arc_EndpointList(in, out, s)
}

func autoConvert_arc_EndpointList_To_v1alpha1_EndpointList(in *arc.EndpointList, out *EndpointList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Endpoint)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_arc_EndpointList_To_v1alpha1_EndpointList is an autogenerated conversion function.
func Convert_arc_EndpointList_To_v1alpha1_EndpointList(in *arc.EndpointList, out *EndpointList, s conversion.Scope) error {
	return autoConvert_arc_EndpointList_To_v1alpha1_EndpointList(in, out, s)
}

func autoConvert_v1alpha1_EndpointSpec_To_arc_EndpointSpec(in *EndpointSpec, out *arc.EndpointSpec, s conversion.Scope) error {
	out.Type = in.Type
	out.RemoteURL = in.RemoteURL
	out.SecretRef = in.SecretRef
	out.Usage = arc.EndpointUsage(in.Usage)
	return nil
}

// Convert_v1alpha1_EndpointSpec_To_arc_EndpointSpec is an autogenerated conversion function.
func Convert_v1alpha1_EndpointSpec_To_arc_EndpointSpec(in *EndpointSpec, out *arc.EndpointSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_EndpointSpec_To_arc_EndpointSpec(in, out, s)
}

func autoConvert_arc_EndpointSpec_To_v1alpha1_EndpointSpec(in *arc.EndpointSpec, out *EndpointSpec, s conversion.Scope) error {
	out.Type = in.Type
	out.RemoteURL = in.RemoteURL
	out.SecretRef = in.SecretRef
	out.Usage = EndpointUsage(in.Usage)
	return nil
}

// Convert_arc_EndpointSpec_To_v1alpha1_EndpointSpec is an autogenerated conversion function.
func Convert_arc_EndpointSpec_To_v1alpha1_EndpointSpec(in *arc.EndpointSpec, out *EndpointSpec, s conversion.Scope) error {
	return autoConvert_arc_EndpointSpec_To_v1alpha1_EndpointSpec(in, out, s)
}

func autoConvert_v1alpha1_EndpointStatus_To_arc_EndpointStatus(in *EndpointStatus, out *arc.EndpointStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_EndpointStatus_To_arc_EndpointStatus is an autogenerated conversion function.
func Convert_v1alpha1_EndpointStatus_To_arc_EndpointStatus(in *EndpointStatus, out *arc.EndpointStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_EndpointStatus_To_arc_EndpointStatus(in, out, s)
}

func autoConvert_arc_EndpointStatus_To_v1alpha1_EndpointStatus(in *arc.EndpointStatus, out *EndpointStatus, s conversion.Scope) error {
	return nil
}

// Convert_arc_EndpointStatus_To_v1alpha1_EndpointStatus is an autogenerated conversion function.
func Convert_arc_EndpointStatus_To_v1alpha1_EndpointStatus(in *arc.EndpointStatus, out *EndpointStatus, s conversion.Scope) error {
	return autoConvert_arc_EndpointStatus_To_v1alpha1_EndpointStatus(in, out, s)
}

func autoConvert_v1alpha1_Order_To_arc_Order(in *Order, out *arc.Order, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_OrderSpec_To_arc_OrderSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_OrderStatus_To_arc_OrderStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Order_To_arc_Order is an autogenerated conversion function.
func Convert_v1alpha1_Order_To_arc_Order(in *Order, out *arc.Order, s conversion.Scope) error {
	return autoConvert_v1alpha1_Order_To_arc_Order(in, out, s)
}

func autoConvert_arc_Order_To_v1alpha1_Order(in *arc.Order, out *Order, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_arc_OrderSpec_To_v1alpha1_OrderSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_arc_OrderStatus_To_v1alpha1_OrderStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_arc_Order_To_v1alpha1_Order is an autogenerated conversion function.
func Convert_arc_Order_To_v1alpha1_Order(in *arc.Order, out *Order, s conversion.Scope) error {
	return autoConvert_arc_Order_To_v1alpha1_Order(in, out, s)
}

func autoConvert_v1alpha1_OrderArtifact_To_arc_OrderArtifact(in *OrderArtifact, out *arc.OrderArtifact, s conversion.Scope) error {
	out.Type = in.Type
	out.SrcRef = in.SrcRef
	out.DstRef = in.DstRef
	out.Spec = in.Spec
	return nil
}

// Convert_v1alpha1_OrderArtifact_To_arc_OrderArtifact is an autogenerated conversion function.
func Convert_v1alpha1_OrderArtifact_To_arc_OrderArtifact(in *OrderArtifact, out *arc.OrderArtifact, s conversion.Scope) error {
	return autoConvert_v1alpha1_OrderArtifact_To_arc_OrderArtifact(in, out, s)
}

func autoConvert_arc_OrderArtifact_To_v1alpha1_OrderArtifact(in *arc.OrderArtifact, out *OrderArtifact, s conversion.Scope) error {
	out.Type = in.Type
	out.SrcRef = in.SrcRef
	out.DstRef = in.DstRef
	out.Spec = in.Spec
	return nil
}

// Convert_arc_OrderArtifact_To_v1alpha1_OrderArtifact is an autogenerated conversion function.
func Convert_arc_OrderArtifact_To_v1alpha1_OrderArtifact(in *arc.OrderArtifact, out *OrderArtifact, s conversion.Scope) error {
	return autoConvert_arc_OrderArtifact_To_v1alpha1_OrderArtifact(in, out, s)
}

func autoConvert_v1alpha1_OrderArtifactWorkflowStatus_To_arc_OrderArtifactWorkflowStatus(in *OrderArtifactWorkflowStatus, out *arc.OrderArtifactWorkflowStatus, s conversion.Scope) error {
	out.ArtifactIndex = in.ArtifactIndex
	out.Phase = arc.WorkflowPhase(in.Phase)
	return nil
}

// Convert_v1alpha1_OrderArtifactWorkflowStatus_To_arc_OrderArtifactWorkflowStatus is an autogenerated conversion function.
func Convert_v1alpha1_OrderArtifactWorkflowStatus_To_arc_OrderArtifactWorkflowStatus(in *OrderArtifactWorkflowStatus, out *arc.OrderArtifactWorkflowStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_OrderArtifactWorkflowStatus_To_arc_OrderArtifactWorkflowStatus(in, out, s)
}

func autoConvert_arc_OrderArtifactWorkflowStatus_To_v1alpha1_OrderArtifactWorkflowStatus(in *arc.OrderArtifactWorkflowStatus, out *OrderArtifactWorkflowStatus, s conversion.Scope) error {
	out.ArtifactIndex = in.ArtifactIndex
	out.Phase = WorkflowPhase(in.Phase)
	return nil
}

// Convert_arc_OrderArtifactWorkflowStatus_To_v1alpha1_OrderArtifactWorkflowStatus is an autogenerated conversion function.
func Convert_arc_OrderArtifactWorkflowStatus_To_v1alpha1_OrderArtifactWorkflowStatus(in *arc.OrderArtifactWorkflowStatus, out *OrderArtifactWorkflowStatus, s conversion.Scope) error {
	return autoConvert_arc_OrderArtifactWorkflowStatus_To_v1alpha1_OrderArtifactWorkflowStatus(in, out, s)
}

func autoConvert_v1alpha1_OrderDefaults_To_arc_OrderDefaults(in *OrderDefaults, out *arc.OrderDefaults, s conversion.Scope) error {
	out.SrcRef = in.SrcRef
	out.DstRef = in.DstRef
	return nil
}

// Convert_v1alpha1_OrderDefaults_To_arc_OrderDefaults is an autogenerated conversion function.
func Convert_v1alpha1_OrderDefaults_To_arc_OrderDefaults(in *OrderDefaults, out *arc.OrderDefaults, s conversion.Scope) error {
	return autoConvert_v1alpha1_OrderDefaults_To_arc_OrderDefaults(in, out, s)
}

func autoConvert_arc_OrderDefaults_To_v1alpha1_OrderDefaults(in *arc.OrderDefaults, out *OrderDefaults, s conversion.Scope) error {
	out.SrcRef = in.SrcRef
	out.DstRef = in.DstRef
	return nil
}

// Convert_arc_OrderDefaults_To_v1alpha1_OrderDefaults is an autogenerated conversion function.
func Convert_arc_OrderDefaults_To_v1alpha1_OrderDefaults(in *arc.OrderDefaults, out *OrderDefaults, s conversion.Scope) error {
	return autoConvert_arc_OrderDefaults_To_v1alpha1_OrderDefaults(in, out, s)
}

func autoConvert_v1alpha1_OrderList_To_arc_OrderList(in *OrderList, out *arc.OrderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]arc.Order)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_OrderList_To_arc_OrderList is an autogenerated conversion function.
func Convert_v1alpha1_OrderList_To_arc_OrderList(in *OrderList, out *arc.OrderList, s conversion.Scope) error {
	return autoConvert_v1alpha1_OrderList_To_arc_OrderList(in, out, s)
}

func autoConvert_arc_OrderList_To_v1alpha1_OrderList(in *arc.OrderList, out *OrderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Order)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_arc_OrderList_To_v1alpha1_OrderList is an autogenerated conversion function.
func Convert_arc_OrderList_To_v1alpha1_OrderList(in *arc.OrderList, out *OrderList, s conversion.Scope) error {
	return autoConvert_arc_OrderList_To_v1alpha1_OrderList(in, out, s)
}

func autoConvert_v1alpha1_OrderSpec_To_arc_OrderSpec(in *OrderSpec, out *arc.OrderSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_OrderDefaults_To_arc_OrderDefaults(&in.Defaults, &out.Defaults, s); err != nil {
		return err
	}
	out.Artifacts = *(*[]arc.OrderArtifact)(unsafe.Pointer(&in.Artifacts))
	return nil
}

// Convert_v1alpha1_OrderSpec_To_arc_OrderSpec is an autogenerated conversion function.
func Convert_v1alpha1_OrderSpec_To_arc_OrderSpec(in *OrderSpec, out *arc.OrderSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_OrderSpec_To_arc_OrderSpec(in, out, s)
}

func autoConvert_arc_OrderSpec_To_v1alpha1_OrderSpec(in *arc.OrderSpec, out *OrderSpec, s conversion.Scope) error {
	if err := Convert_arc_OrderDefaults_To_v1alpha1_OrderDefaults(&in.Defaults, &out.Defaults, s); err != nil {
		return err
	}
	out.Artifacts = *(*[]OrderArtifact)(unsafe.Pointer(&in.Artifacts))
	return nil
}

// Convert_arc_OrderSpec_To_v1alpha1_OrderSpec is an autogenerated conversion function.
func Convert_arc_OrderSpec_To_v1alpha1_OrderSpec(in *arc.OrderSpec, out *OrderSpec, s conversion.Scope) error {
	return autoConvert_arc_OrderSpec_To_v1alpha1_OrderSpec(in, out, s)
}

func autoConvert_v1alpha1_OrderStatus_To_arc_OrderStatus(in *OrderStatus, out *arc.OrderStatus, s conversion.Scope) error {
	out.ArtifactWorkflows = *(*map[string]arc.OrderArtifactWorkflowStatus)(unsafe.Pointer(&in.ArtifactWorkflows))
	return nil
}

// Convert_v1alpha1_OrderStatus_To_arc_OrderStatus is an autogenerated conversion function.
func Convert_v1alpha1_OrderStatus_To_arc_OrderStatus(in *OrderStatus, out *arc.OrderStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_OrderStatus_To_arc_OrderStatus(in, out, s)
}

func autoConvert_arc_OrderStatus_To_v1alpha1_OrderStatus(in *arc.OrderStatus, out *OrderStatus, s conversion.Scope) error {
	out.ArtifactWorkflows = *(*map[string]OrderArtifactWorkflowStatus)(unsafe.Pointer(&in.ArtifactWorkflows))
	return nil
}

// Convert_arc_OrderStatus_To_v1alpha1_OrderStatus is an autogenerated conversion function.
func Convert_arc_OrderStatus_To_v1alpha1_OrderStatus(in *arc.OrderStatus, out *OrderStatus, s conversion.Scope) error {
	return autoConvert_arc_OrderStatus_To_v1alpha1_OrderStatus(in, out, s)
}
