//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by openapi-gen. DO NOT EDIT.

package v1alpha1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ArtifactType) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.ArtifactType"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ArtifactTypeList) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.ArtifactTypeList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ArtifactTypeRules) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.ArtifactTypeRules"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ArtifactTypeSpec) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.ArtifactTypeSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ArtifactTypeStatus) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.ArtifactTypeStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ArtifactWorkflow) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.ArtifactWorkflow"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ArtifactWorkflowList) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.ArtifactWorkflowList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ArtifactWorkflowSpec) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.ArtifactWorkflowSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ArtifactWorkflowStatus) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.ArtifactWorkflowStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Endpoint) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.Endpoint"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EndpointList) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.EndpointList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EndpointSpec) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.EndpointSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EndpointStatus) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.EndpointStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Order) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.Order"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in OrderArtifact) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.OrderArtifact"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in OrderArtifactWorkflowStatus) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.OrderArtifactWorkflowStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in OrderDefaults) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.OrderDefaults"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in OrderList) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.OrderList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in OrderSpec) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.OrderSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in OrderStatus) OpenAPIModelName() string {
	return "de.bwi.arc.v1alpha1.OrderStatus"
}
