// Copyright BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiarcv1alpha1 "go.opendefense.cloud/arc/api/arc/v1alpha1"
	versioned "go.opendefense.cloud/arc/client-go/clientset/versioned"
	internalinterfaces "go.opendefense.cloud/arc/client-go/informers/externalversions/internalinterfaces"
	arcv1alpha1 "go.opendefense.cloud/arc/client-go/listers/arc/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ArtifactTypeInformer provides access to a shared informer and lister for
// ArtifactTypes. Prefer using the type-safe variant (see [TypedArtifactTypeInformer]).
type ArtifactTypeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() arcv1alpha1.ArtifactTypeLister
}

// TypedArtifactTypeInformer provides access to a shared informer and lister for
// ArtifactTypes, including the type-safe TypedInformer variant.
// It is a superset of ArtifactTypeInformer.
type TypedArtifactTypeInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() ArtifactTypeIndexInformer
	Lister() arcv1alpha1.ArtifactTypeLister
}

// ArtifactTypeIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type ArtifactTypeIndexInformer cache.TypedSharedIndexInformer[*apiarcv1alpha1.ArtifactType]

// ArtifactTypeHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for ArtifactType.
type ArtifactTypeHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apiarcv1alpha1.ArtifactType]

// ArtifactTypeDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for ArtifactType.
type ArtifactTypeDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apiarcv1alpha1.ArtifactType]

// ArtifactTypeFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for ArtifactType.
type ArtifactTypeFilteringHandler = cache.TypedFilteringResourceEventHandler[*apiarcv1alpha1.ArtifactType]

// ArtifactTypeIndexers is a specialization of [cache.TypedIndexers] for ArtifactType.
type ArtifactTypeIndexers = cache.TypedIndexers[*apiarcv1alpha1.ArtifactType]

// DeletedArtifactType is a specialization of [cache.DeletedObject] for ArtifactType.
type DeletedArtifactType = cache.DeletedObject[*apiarcv1alpha1.ArtifactType]

type artifactTypeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewArtifactTypeInformer constructs a new informer for ArtifactType type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedArtifactTypeInformer]).
func NewArtifactTypeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewArtifactTypeInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedArtifactTypeInformer constructs a new informer for ArtifactType type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedArtifactTypeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers ArtifactTypeIndexers) ArtifactTypeIndexInformer {
	return NewTypedArtifactTypeInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredArtifactTypeInformer constructs a new informer for ArtifactType type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredArtifactTypeInformer]).
func NewFilteredArtifactTypeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedArtifactTypeInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredArtifactTypeInformer constructs a new informer for ArtifactType type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredArtifactTypeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers ArtifactTypeIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) ArtifactTypeIndexInformer {
	return NewTypedArtifactTypeInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewArtifactTypeInformerWithOptions constructs a new informer for ArtifactType type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedArtifactTypeInformerWithOptions]).
func NewArtifactTypeInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedArtifactTypeInformerWithOptions(client, namespace, options)
}

// NewTypedArtifactTypeInformerWithOptions constructs a new informer for ArtifactType type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedArtifactTypeInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) ArtifactTypeIndexInformer {
	gvr := schema.GroupVersionResource{Group: "arc.opendefense.cloud", Version: "v1alpha1", Resource: "artifacttypes"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apiarcv1alpha1.ArtifactType](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.ArcV1alpha1().ArtifactTypes(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.ArcV1alpha1().ArtifactTypes(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.ArcV1alpha1().ArtifactTypes(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.ArcV1alpha1().ArtifactTypes(namespace).Watch(ctx, opts)
			},
		}, client),
		&apiarcv1alpha1.ArtifactType{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *artifactTypeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedArtifactTypeInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *artifactTypeInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *artifactTypeInformer) TypedInformer() ArtifactTypeIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apiarcv1alpha1.ArtifactType](f.factory.InformerFor(&apiarcv1alpha1.ArtifactType{}, f.defaultInformer))
}

func (f *artifactTypeInformer) Lister() arcv1alpha1.ArtifactTypeLister {
	return arcv1alpha1.NewArtifactTypeLister(f.Informer().GetIndexer())
}

// ToTypedArtifactTypeInformer converts an untyped informer into a TypedArtifactTypeInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *ArtifactType. If that is not the case, calling type-safe methods of the returned
// TypedArtifactTypeInformer leads to runtime panics. A safer alternative is to pass
// around a TypedArtifactTypeInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedArtifactTypeInformer(informer ArtifactTypeInformer) TypedArtifactTypeInformer {
	if informer, ok := informer.(TypedArtifactTypeInformer); ok {
		return informer
	}
	return &artifactTypeTypedInformerAdapter{informer}
}

type artifactTypeTypedInformerAdapter struct {
	ArtifactTypeInformer
}

func (a *artifactTypeTypedInformerAdapter) TypedInformer() ArtifactTypeIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apiarcv1alpha1.ArtifactType](a.Informer())
}

// ToArtifactTypeIndexInformer converts an untyped informer into a ArtifactTypeIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *ArtifactType. If that is not the case, calling type-safe methods of the returned
// ArtifactTypeIndexInformer leads to runtime panics. A safer alternative is to pass
// around a ArtifactTypeIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToArtifactTypeIndexInformer(informer cache.SharedIndexInformer) ArtifactTypeIndexInformer {
	if informer, ok := informer.(ArtifactTypeIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apiarcv1alpha1.ArtifactType](informer)
}
