// Copyright 2025 BWI GmbH and Artefact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiarcv1alpha1 "github.com/opendefensecloud/artifact-conduit/api/arc/v1alpha1"
	versioned "github.com/opendefensecloud/artifact-conduit/client-go/clientset/versioned"
	internalinterfaces "github.com/opendefensecloud/artifact-conduit/client-go/informers/externalversions/internalinterfaces"
	arcv1alpha1 "github.com/opendefensecloud/artifact-conduit/client-go/listers/arc/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ArtifactTypeDefinitionInformer provides access to a shared informer and lister for
// ArtifactTypeDefinitions.
type ArtifactTypeDefinitionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() arcv1alpha1.ArtifactTypeDefinitionLister
}

type artifactTypeDefinitionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewArtifactTypeDefinitionInformer constructs a new informer for ArtifactTypeDefinition type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewArtifactTypeDefinitionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredArtifactTypeDefinitionInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredArtifactTypeDefinitionInformer constructs a new informer for ArtifactTypeDefinition type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredArtifactTypeDefinitionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ArcV1alpha1().ArtifactTypeDefinitions(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ArcV1alpha1().ArtifactTypeDefinitions(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ArcV1alpha1().ArtifactTypeDefinitions(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ArcV1alpha1().ArtifactTypeDefinitions(namespace).Watch(ctx, options)
			},
		},
		&apiarcv1alpha1.ArtifactTypeDefinition{},
		resyncPeriod,
		indexers,
	)
}

func (f *artifactTypeDefinitionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredArtifactTypeDefinitionInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *artifactTypeDefinitionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiarcv1alpha1.ArtifactTypeDefinition{}, f.defaultInformer)
}

func (f *artifactTypeDefinitionInformer) Lister() arcv1alpha1.ArtifactTypeDefinitionLister {
	return arcv1alpha1.NewArtifactTypeDefinitionLister(f.Informer().GetIndexer())
}
