// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiarcv1alpha1 "go.opendefense.cloud/arc/api/arc/v1alpha1"
	versioned "go.opendefense.cloud/arc/client-go/clientset/versioned"
	internalinterfaces "go.opendefense.cloud/arc/client-go/informers/externalversions/internalinterfaces"
	arcv1alpha1 "go.opendefense.cloud/arc/client-go/listers/arc/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ArtifactWorkflowInformer provides access to a shared informer and lister for
// ArtifactWorkflows.
type ArtifactWorkflowInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() arcv1alpha1.ArtifactWorkflowLister
}

type artifactWorkflowInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewArtifactWorkflowInformer constructs a new informer for ArtifactWorkflow type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewArtifactWorkflowInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredArtifactWorkflowInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredArtifactWorkflowInformer constructs a new informer for ArtifactWorkflow type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredArtifactWorkflowInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ArcV1alpha1().ArtifactWorkflows(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ArcV1alpha1().ArtifactWorkflows(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ArcV1alpha1().ArtifactWorkflows(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ArcV1alpha1().ArtifactWorkflows(namespace).Watch(ctx, options)
			},
		},
		&apiarcv1alpha1.ArtifactWorkflow{},
		resyncPeriod,
		indexers,
	)
}

func (f *artifactWorkflowInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredArtifactWorkflowInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *artifactWorkflowInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiarcv1alpha1.ArtifactWorkflow{}, f.defaultInformer)
}

func (f *artifactWorkflowInformer) Lister() arcv1alpha1.ArtifactWorkflowLister {
	return arcv1alpha1.NewArtifactWorkflowLister(f.Informer().GetIndexer())
}
