// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiarcv1alpha1 "go.opendefense.cloud/arc/api/arc/v1alpha1"
	versioned "go.opendefense.cloud/arc/client-go/clientset/versioned"
	internalinterfaces "go.opendefense.cloud/arc/client-go/informers/externalversions/internalinterfaces"
	arcv1alpha1 "go.opendefense.cloud/arc/client-go/listers/arc/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterEndpointInformer provides access to a shared informer and lister for
// ClusterEndpoints.
type ClusterEndpointInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() arcv1alpha1.ClusterEndpointLister
}

type clusterEndpointInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewClusterEndpointInformer constructs a new informer for ClusterEndpoint type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterEndpointInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterEndpointInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredClusterEndpointInformer constructs a new informer for ClusterEndpoint type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterEndpointInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ArcV1alpha1().ClusterEndpoints().List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ArcV1alpha1().ClusterEndpoints().Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ArcV1alpha1().ClusterEndpoints().List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ArcV1alpha1().ClusterEndpoints().Watch(ctx, options)
			},
		},
		&apiarcv1alpha1.ClusterEndpoint{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterEndpointInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterEndpointInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterEndpointInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiarcv1alpha1.ClusterEndpoint{}, f.defaultInformer)
}

func (f *clusterEndpointInformer) Lister() arcv1alpha1.ClusterEndpointLister {
	return arcv1alpha1.NewClusterEndpointLister(f.Informer().GetIndexer())
}
