// Copyright 2025 BWI GmbH and Artefact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "gitlab.opencode.de/bwi/ace/artifact-conduit/client-go/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ArtifactTypeDefinitions returns a ArtifactTypeDefinitionInformer.
	ArtifactTypeDefinitions() ArtifactTypeDefinitionInformer
	// Endpoints returns a EndpointInformer.
	Endpoints() EndpointInformer
	// Fragments returns a FragmentInformer.
	Fragments() FragmentInformer
	// Orders returns a OrderInformer.
	Orders() OrderInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// ArtifactTypeDefinitions returns a ArtifactTypeDefinitionInformer.
func (v *version) ArtifactTypeDefinitions() ArtifactTypeDefinitionInformer {
	return &artifactTypeDefinitionInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Endpoints returns a EndpointInformer.
func (v *version) Endpoints() EndpointInformer {
	return &endpointInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Fragments returns a FragmentInformer.
func (v *version) Fragments() FragmentInformer {
	return &fragmentInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Orders returns a OrderInformer.
func (v *version) Orders() OrderInformer {
	return &orderInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
