// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "go.opendefense.cloud/arc/client-go/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ArtifactTypes returns a ArtifactTypeInformer.
	ArtifactTypes() ArtifactTypeInformer
	// ArtifactWorkflows returns a ArtifactWorkflowInformer.
	ArtifactWorkflows() ArtifactWorkflowInformer
	// Endpoints returns a EndpointInformer.
	Endpoints() EndpointInformer
	// Orders returns a OrderInformer.
	Orders() OrderInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// ArtifactTypes returns a ArtifactTypeInformer.
func (v *version) ArtifactTypes() ArtifactTypeInformer {
	return &artifactTypeInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ArtifactWorkflows returns a ArtifactWorkflowInformer.
func (v *version) ArtifactWorkflows() ArtifactWorkflowInformer {
	return &artifactWorkflowInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Endpoints returns a EndpointInformer.
func (v *version) Endpoints() EndpointInformer {
	return &endpointInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Orders returns a OrderInformer.
func (v *version) Orders() OrderInformer {
	return &orderInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
