// SPDX-FileCopyrightText: 2025 BWI GmbH and Artefact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	orderv1alpha1 "gitlab.opencode.de/bwi/ace/artifact-conduit/api/order/v1alpha1"
	applyconfigurationsorderv1alpha1 "gitlab.opencode.de/bwi/ace/artifact-conduit/client-go/applyconfigurations/order/v1alpha1"
	scheme "gitlab.opencode.de/bwi/ace/artifact-conduit/client-go/arc/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// OrdersGetter has a method to return a OrderInterface.
// A group's client should implement this interface.
type OrdersGetter interface {
	Orders(namespace string) OrderInterface
}

// OrderInterface has methods to work with Order resources.
type OrderInterface interface {
	Create(ctx context.Context, order *orderv1alpha1.Order, opts v1.CreateOptions) (*orderv1alpha1.Order, error)
	Update(ctx context.Context, order *orderv1alpha1.Order, opts v1.UpdateOptions) (*orderv1alpha1.Order, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, order *orderv1alpha1.Order, opts v1.UpdateOptions) (*orderv1alpha1.Order, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*orderv1alpha1.Order, error)
	List(ctx context.Context, opts v1.ListOptions) (*orderv1alpha1.OrderList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *orderv1alpha1.Order, err error)
	Apply(ctx context.Context, order *applyconfigurationsorderv1alpha1.OrderApplyConfiguration, opts v1.ApplyOptions) (result *orderv1alpha1.Order, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, order *applyconfigurationsorderv1alpha1.OrderApplyConfiguration, opts v1.ApplyOptions) (result *orderv1alpha1.Order, err error)
	OrderExpansion
}

// orders implements OrderInterface
type orders struct {
	*gentype.ClientWithListAndApply[*orderv1alpha1.Order, *orderv1alpha1.OrderList, *applyconfigurationsorderv1alpha1.OrderApplyConfiguration]
}

// newOrders returns a Orders
func newOrders(c *OrderV1alpha1Client, namespace string) *orders {
	return &orders{
		gentype.NewClientWithListAndApply[*orderv1alpha1.Order, *orderv1alpha1.OrderList, *applyconfigurationsorderv1alpha1.OrderApplyConfiguration](
			"orders",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *orderv1alpha1.Order { return &orderv1alpha1.Order{} },
			func() *orderv1alpha1.OrderList { return &orderv1alpha1.OrderList{} },
		),
	}
}
