apiVersion: arc.opendefense.cloud/v1alpha1
kind: ArtifactWorkflow
metadata:
  name: example-frag
spec:
  workflowTemplateRef: # based on Artifact Type used in Order
    name: oci-workflow-template
  srcSecretRef:
    name: mysrc-creds
  dstSecretRef:
    name: mydst-creds
  parameters:
    - name: srcType
      value: oci
      # ...
