apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: oci-workflow-template
spec:
  entrypoint: oci-workflow
  templates:
    - name: oci-workflow
      steps:
        - - name: pull
            template: oci-pull
        # - - name: scan
        #     template: oci-scan
        - - name: push
            template: oci-push
    - name: oci-pull
      container:
        image: registry.opencode.de/bwi/ace/artifact-conduit/arcctl:latest
        command: [arcctl]
        args:
          [
            "oci",
            "pull",
            "-c",
            "/etc/oci-workflow-config/config.yaml",
            "--tmp-dir",
            "/tmp/artifact",
          ]
        volumeMounts:
          - name: workflow-config
            mountPath: /etc/oci-workflow-config
          - name: workdir
            mountPath: /tmp/artifact
    # - name: oci-scan
    #   container:
    #     image: aquasec/trivy:latest
    #     command: [trivy]
    #     args: ["--input", "/tmp/artifact/oci.tar"]
    #     volumeMounts:
    #       - name: workflow-config
    #         mountPath: /etc/oci-workflow-config
    #       - name: workdir
    #         mountPath: /tmp/artifact
    - name: oci-push
      container:
        image: registry.opencode.de/bwi/ace/artifact-conduit/arcctl:latest
        command: [arcctl]
        args:
          [
            "oci",
            "push",
            "-c",
            "/etc/workflow-config/config.yaml",
            "--tmp-dir",
            "/tmp/artifact",
          ]
        volumeMounts:
          - name: workflow-config
            mountPath: /etc/oci-workflow-config
          - name: workdir
            mountPath: /tmp/artifact
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: oci-workflow-alpine-123123
spec:
  entrypoint: oci-workflow
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
  volumes:
    - name: workflow-config
      secret:
        secretName: oci-workflow-config
    - name: oci-workflow-tmp
      emptyDir: {}
  templates:
    - name: oci-workflow
      steps:
        - - name: oci-workflow
            templateRef:
              name: oci-workflow-template
              template: oci-workflow
