apiVersion: arc.bwi.de/v1alpha1
kind: ClusterArtifactType
metadata:
  name: helm
spec:
  rules:
    srcTypes: # Endpoint Types
      - oci
      - helm
    dstTypes:
      - oci
  parameters:
    - name: scanSeverity
      value: HIGH,CRITICAL
    - name: dstPlainHTTP
      value: "true"
  workflowTemplateRef: # argo.Workflow
    name: helm-chart-pipeline
