apiVersion: arc.opendefense.cloud/v1alpha1
kind: ClusterArtifactType
metadata:
  name: helm
spec:
  rules:
    srcTypes: # Endpoint Types
      - oci
      - helm
    dstTypes:
      - oci
  parameters:
    - name: scanSeverity
      value: HIGH,CRITICAL
  workflowTemplateRef: # argo.Workflow
    name: helm-chart-pipeline
