---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arc.opendefense.cloud
  resources:
  - artifacttypes
  - clusterartifacttypes
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - arc.opendefense.cloud
  resources:
  - artifactworkflows
  - orders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arc.opendefense.cloud
  resources:
  - artifactworkflows/finalizers
  - orders/finalizers
  verbs:
  - update
- apiGroups:
  - arc.opendefense.cloud
  resources:
  - artifactworkflows/status
  - orders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - argoproj.io
  resources:
  - cronworkflows
  - workflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
