// Copyright 2025 BWI GmbH and Artefact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "gitlab.opencode.de/bwi/ace/artifact-conduit/api/order/v1alpha1"
	orderv1alpha1 "gitlab.opencode.de/bwi/ace/artifact-conduit/client-go/applyconfigurations/order/v1alpha1"
	typedorderv1alpha1 "gitlab.opencode.de/bwi/ace/artifact-conduit/client-go/clientset/versioned/typed/order/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeOrders implements OrderInterface
type fakeOrders struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.Order, *v1alpha1.OrderList, *orderv1alpha1.OrderApplyConfiguration]
	Fake *FakeOrderV1alpha1
}

func newFakeOrders(fake *FakeOrderV1alpha1, namespace string) typedorderv1alpha1.OrderInterface {
	return &fakeOrders{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.Order, *v1alpha1.OrderList, *orderv1alpha1.OrderApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("orders"),
			v1alpha1.SchemeGroupVersion.WithKind("Order"),
			func() *v1alpha1.Order { return &v1alpha1.Order{} },
			func() *v1alpha1.OrderList { return &v1alpha1.OrderList{} },
			func(dst, src *v1alpha1.OrderList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.OrderList) []*v1alpha1.Order { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.OrderList, items []*v1alpha1.Order) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
