// Copyright 2025 BWI GmbH and Artefact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfigurations

import (
	v1alpha1 "go.opendefense.cloud/arc/api/arc/v1alpha1"
	arcv1alpha1 "go.opendefense.cloud/arc/client-go/applyconfigurations/arc/v1alpha1"
	internal "go.opendefense.cloud/arc/client-go/applyconfigurations/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=arc.bwi.de, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("ArtifactTypeDefinition"):
		return &arcv1alpha1.ArtifactTypeDefinitionApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ArtifactTypeDefinitionRules"):
		return &arcv1alpha1.ArtifactTypeDefinitionRulesApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ArtifactTypeDefinitionSpec"):
		return &arcv1alpha1.ArtifactTypeDefinitionSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Endpoint"):
		return &arcv1alpha1.EndpointApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("EndpointSpec"):
		return &arcv1alpha1.EndpointSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Fragment"):
		return &arcv1alpha1.FragmentApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FragmentSpec"):
		return &arcv1alpha1.FragmentSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Order"):
		return &arcv1alpha1.OrderApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("OrderArtifact"):
		return &arcv1alpha1.OrderArtifactApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("OrderDefaults"):
		return &arcv1alpha1.OrderDefaultsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("OrderSpec"):
		return &arcv1alpha1.OrderSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("OrderStatus"):
		return &arcv1alpha1.OrderStatusApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
