// Copyright 2025 BWI GmbH and Artefact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "gitlab.opencode.de/bwi/ace/artifact-conduit/api/arc/v1alpha1"
	arcv1alpha1 "gitlab.opencode.de/bwi/ace/artifact-conduit/client-go/applyconfigurations/arc/v1alpha1"
	typedarcv1alpha1 "gitlab.opencode.de/bwi/ace/artifact-conduit/client-go/clientset/versioned/typed/arc/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeFragments implements FragmentInterface
type fakeFragments struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.Fragment, *v1alpha1.FragmentList, *arcv1alpha1.FragmentApplyConfiguration]
	Fake *FakeArcV1alpha1
}

func newFakeFragments(fake *FakeArcV1alpha1, namespace string) typedarcv1alpha1.FragmentInterface {
	return &fakeFragments{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.Fragment, *v1alpha1.FragmentList, *arcv1alpha1.FragmentApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("fragments"),
			v1alpha1.SchemeGroupVersion.WithKind("Fragment"),
			func() *v1alpha1.Fragment { return &v1alpha1.Fragment{} },
			func() *v1alpha1.FragmentList { return &v1alpha1.FragmentList{} },
			func(dst, src *v1alpha1.FragmentList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.FragmentList) []*v1alpha1.Fragment { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.FragmentList, items []*v1alpha1.Fragment) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
