// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.opendefense.cloud/arc/client-go/clientset/versioned/typed/arc/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeArcV1alpha1 struct {
	*testing.Fake
}

func (c *FakeArcV1alpha1) ArtifactTypes(namespace string) v1alpha1.ArtifactTypeInterface {
	return newFakeArtifactTypes(c, namespace)
}

func (c *FakeArcV1alpha1) ArtifactWorkflows(namespace string) v1alpha1.ArtifactWorkflowInterface {
	return newFakeArtifactWorkflows(c, namespace)
}

func (c *FakeArcV1alpha1) Endpoints(namespace string) v1alpha1.EndpointInterface {
	return newFakeEndpoints(c, namespace)
}

func (c *FakeArcV1alpha1) Orders(namespace string) v1alpha1.OrderInterface {
	return newFakeOrders(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeArcV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
