// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.opendefense.cloud/arc/api/arc/v1alpha1"
	arcv1alpha1 "go.opendefense.cloud/arc/client-go/applyconfigurations/arc/v1alpha1"
	typedarcv1alpha1 "go.opendefense.cloud/arc/client-go/clientset/versioned/typed/arc/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeArtifactTypes implements ArtifactTypeInterface
type fakeArtifactTypes struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.ArtifactType, *v1alpha1.ArtifactTypeList, *arcv1alpha1.ArtifactTypeApplyConfiguration]
	Fake *FakeArcV1alpha1
}

func newFakeArtifactTypes(fake *FakeArcV1alpha1, namespace string) typedarcv1alpha1.ArtifactTypeInterface {
	return &fakeArtifactTypes{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.ArtifactType, *v1alpha1.ArtifactTypeList, *arcv1alpha1.ArtifactTypeApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("artifacttypes"),
			v1alpha1.SchemeGroupVersion.WithKind("ArtifactType"),
			func() *v1alpha1.ArtifactType { return &v1alpha1.ArtifactType{} },
			func() *v1alpha1.ArtifactTypeList { return &v1alpha1.ArtifactTypeList{} },
			func(dst, src *v1alpha1.ArtifactTypeList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ArtifactTypeList) []*v1alpha1.ArtifactType {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ArtifactTypeList, items []*v1alpha1.ArtifactType) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
