// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.opendefense.cloud/arc/api/arc/v1alpha1"
	arcv1alpha1 "go.opendefense.cloud/arc/client-go/applyconfigurations/arc/v1alpha1"
	typedarcv1alpha1 "go.opendefense.cloud/arc/client-go/clientset/versioned/typed/arc/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeArtifactWorkflows implements ArtifactWorkflowInterface
type fakeArtifactWorkflows struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.ArtifactWorkflow, *v1alpha1.ArtifactWorkflowList, *arcv1alpha1.ArtifactWorkflowApplyConfiguration]
	Fake *FakeArcV1alpha1
}

func newFakeArtifactWorkflows(fake *FakeArcV1alpha1, namespace string) typedarcv1alpha1.ArtifactWorkflowInterface {
	return &fakeArtifactWorkflows{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.ArtifactWorkflow, *v1alpha1.ArtifactWorkflowList, *arcv1alpha1.ArtifactWorkflowApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("artifactworkflows"),
			v1alpha1.SchemeGroupVersion.WithKind("ArtifactWorkflow"),
			func() *v1alpha1.ArtifactWorkflow { return &v1alpha1.ArtifactWorkflow{} },
			func() *v1alpha1.ArtifactWorkflowList { return &v1alpha1.ArtifactWorkflowList{} },
			func(dst, src *v1alpha1.ArtifactWorkflowList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ArtifactWorkflowList) []*v1alpha1.ArtifactWorkflow {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ArtifactWorkflowList, items []*v1alpha1.ArtifactWorkflow) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
