// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.opendefense.cloud/arc/api/arc/v1alpha1"
	arcv1alpha1 "go.opendefense.cloud/arc/client-go/applyconfigurations/arc/v1alpha1"
	typedarcv1alpha1 "go.opendefense.cloud/arc/client-go/clientset/versioned/typed/arc/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeClusterArtifactTypes implements ClusterArtifactTypeInterface
type fakeClusterArtifactTypes struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.ClusterArtifactType, *v1alpha1.ClusterArtifactTypeList, *arcv1alpha1.ClusterArtifactTypeApplyConfiguration]
	Fake *FakeArcV1alpha1
}

func newFakeClusterArtifactTypes(fake *FakeArcV1alpha1) typedarcv1alpha1.ClusterArtifactTypeInterface {
	return &fakeClusterArtifactTypes{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.ClusterArtifactType, *v1alpha1.ClusterArtifactTypeList, *arcv1alpha1.ClusterArtifactTypeApplyConfiguration](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("clusterartifacttypes"),
			v1alpha1.SchemeGroupVersion.WithKind("ClusterArtifactType"),
			func() *v1alpha1.ClusterArtifactType { return &v1alpha1.ClusterArtifactType{} },
			func() *v1alpha1.ClusterArtifactTypeList { return &v1alpha1.ClusterArtifactTypeList{} },
			func(dst, src *v1alpha1.ClusterArtifactTypeList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ClusterArtifactTypeList) []*v1alpha1.ClusterArtifactType {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ClusterArtifactTypeList, items []*v1alpha1.ClusterArtifactType) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
