// Copyright 2025 BWI GmbH and Artefact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/opendefensecloud/artifact-conduit/api/arc/v1alpha1"
	arcv1alpha1 "github.com/opendefensecloud/artifact-conduit/client-go/applyconfigurations/arc/v1alpha1"
	typedarcv1alpha1 "github.com/opendefensecloud/artifact-conduit/client-go/clientset/versioned/typed/arc/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeEndpoints implements EndpointInterface
type fakeEndpoints struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.Endpoint, *v1alpha1.EndpointList, *arcv1alpha1.EndpointApplyConfiguration]
	Fake *FakeArcV1alpha1
}

func newFakeEndpoints(fake *FakeArcV1alpha1, namespace string) typedarcv1alpha1.EndpointInterface {
	return &fakeEndpoints{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.Endpoint, *v1alpha1.EndpointList, *arcv1alpha1.EndpointApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("endpoints"),
			v1alpha1.SchemeGroupVersion.WithKind("Endpoint"),
			func() *v1alpha1.Endpoint { return &v1alpha1.Endpoint{} },
			func() *v1alpha1.EndpointList { return &v1alpha1.EndpointList{} },
			func(dst, src *v1alpha1.EndpointList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.EndpointList) []*v1alpha1.Endpoint { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.EndpointList, items []*v1alpha1.Endpoint) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
