// Copyright 2025 BWI GmbH and Artefact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.opendefense.cloud/arc/api/arc/v1alpha1"
	arcv1alpha1 "go.opendefense.cloud/arc/client-go/applyconfigurations/arc/v1alpha1"
	typedarcv1alpha1 "go.opendefense.cloud/arc/client-go/clientset/versioned/typed/arc/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeArtifactTypeDefinitions implements ArtifactTypeDefinitionInterface
type fakeArtifactTypeDefinitions struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.ArtifactTypeDefinition, *v1alpha1.ArtifactTypeDefinitionList, *arcv1alpha1.ArtifactTypeDefinitionApplyConfiguration]
	Fake *FakeArcV1alpha1
}

func newFakeArtifactTypeDefinitions(fake *FakeArcV1alpha1, namespace string) typedarcv1alpha1.ArtifactTypeDefinitionInterface {
	return &fakeArtifactTypeDefinitions{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.ArtifactTypeDefinition, *v1alpha1.ArtifactTypeDefinitionList, *arcv1alpha1.ArtifactTypeDefinitionApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("artifacttypedefinitions"),
			v1alpha1.SchemeGroupVersion.WithKind("ArtifactTypeDefinition"),
			func() *v1alpha1.ArtifactTypeDefinition { return &v1alpha1.ArtifactTypeDefinition{} },
			func() *v1alpha1.ArtifactTypeDefinitionList { return &v1alpha1.ArtifactTypeDefinitionList{} },
			func(dst, src *v1alpha1.ArtifactTypeDefinitionList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ArtifactTypeDefinitionList) []*v1alpha1.ArtifactTypeDefinition {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ArtifactTypeDefinitionList, items []*v1alpha1.ArtifactTypeDefinition) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
