// Copyright 2025 BWI GmbH and Artefact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.opendefense.cloud/arc/client-go/clientset/versioned/typed/arc/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeArcV1alpha1 struct {
	*testing.Fake
}

func (c *FakeArcV1alpha1) ArtifactTypeDefinitions(namespace string) v1alpha1.ArtifactTypeDefinitionInterface {
	return newFakeArtifactTypeDefinitions(c, namespace)
}

func (c *FakeArcV1alpha1) Endpoints(namespace string) v1alpha1.EndpointInterface {
	return newFakeEndpoints(c, namespace)
}

func (c *FakeArcV1alpha1) Fragments(namespace string) v1alpha1.FragmentInterface {
	return newFakeFragments(c, namespace)
}

func (c *FakeArcV1alpha1) Orders(namespace string) v1alpha1.OrderInterface {
	return newFakeOrders(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeArcV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
