// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.opendefense.cloud/arc/api/arc/v1alpha1"
	arcv1alpha1 "go.opendefense.cloud/arc/client-go/applyconfigurations/arc/v1alpha1"
	typedarcv1alpha1 "go.opendefense.cloud/arc/client-go/clientset/versioned/typed/arc/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeClusterEndpoints implements ClusterEndpointInterface
type fakeClusterEndpoints struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.ClusterEndpoint, *v1alpha1.ClusterEndpointList, *arcv1alpha1.ClusterEndpointApplyConfiguration]
	Fake *FakeArcV1alpha1
}

func newFakeClusterEndpoints(fake *FakeArcV1alpha1) typedarcv1alpha1.ClusterEndpointInterface {
	return &fakeClusterEndpoints{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.ClusterEndpoint, *v1alpha1.ClusterEndpointList, *arcv1alpha1.ClusterEndpointApplyConfiguration](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("clusterendpoints"),
			v1alpha1.SchemeGroupVersion.WithKind("ClusterEndpoint"),
			func() *v1alpha1.ClusterEndpoint { return &v1alpha1.ClusterEndpoint{} },
			func() *v1alpha1.ClusterEndpointList { return &v1alpha1.ClusterEndpointList{} },
			func(dst, src *v1alpha1.ClusterEndpointList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ClusterEndpointList) []*v1alpha1.ClusterEndpoint {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ClusterEndpointList, items []*v1alpha1.ClusterEndpoint) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
